### ISSUE TITLE
debugging for the arduino uno

### ISSUE THREAD

**Issue by andrewmurphy83** [platformio/platformio-core#3310] opened 2019-12-18 06:56 UTC
What kind of issue is this?

- [ ] **Question**.
      is there going be update to support the debugging feature to support for debugging for arduino uno 
      

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      I am trying to figure why i can debug my arduino uno code 
- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: windows 10 

**PlatformIO Version** (`platformio --version`):
platformio core 4.1.0 and home 3.0.1
### Description of problem
I try to debug my code for the arduino uno using the debug fuction on the vscode  using the platformio and it keep saying the debug does not support the arduino uno board

#### Steps to Reproduce

1.
2.
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by ivankravets** [comment] 2019-12-21 13:54
Duplicate of https://github.com/platformio/platform-atmelavr/issues/95

**Closed by ivankravets** 2019-12-21 13:54 UTC
