### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by ondrabeni** [platformio/platformio-core#1123] opened 2017-10-16 18:34 UTC
Server error - defult location is null.

**Comment by ivankravets** [comment] 2017-10-17 23:09
Please open PlatformIO IDE Terminal and type
```
pio home
```

Now, it should be opened in your browser. Do you see any errors in a console?

**Comment by ivankravets** [comment] 2017-10-19 10:58
Duplicate of https://github.com/platformio/platformio-core/issues/1063

**Closed by ivankravets** 2017-10-19 10:58 UTC
Labels: help wanted, home
