### ISSUE TITLE
nrf5340-DK hardware support

### ISSUE THREAD

**Issue by JonasForssell** [platformio/platformio-core#4079] opened 2021-10-10 17:37 UTC
**Feature Request**.

I would like to request support for the new nrf5340 - DK board from Nordic Semiconductor

https://www.nordicsemi.com/Products/Development-hardware/nRF5340-DK

Official supported with Zephyr but can also be programmed using the nrfx libraries which is a more traditional low-level approach.

https://github.com/NordicSemiconductor/nrfx

**Comment by domhardt** [comment] 2022-02-09 09:17
Why was this issue closed? It seems that the [nRF5340](https://www.nordicsemi.com/Products/nRF5340) ist still unsupported.

**Comment by ivankravets** [comment] 2022-04-02 20:17
Duplicate of https://github.com/platformio/platformio-core/issues/3978

**Closed by ivankravets** 2022-04-02 20:17 UTC
Labels: board, platform, feature
