### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by MariusLaurinaitis** [platformio/platformio-core#1417] opened 2018-03-06 08:41 UTC
TypeError: Cannot read property 'name' of null
    at http://127.0.0.1:8010/0fe71ff5b710e32b7725.min.js:6:43388
    at Array.map (native)
    at b (http://127.0.0.1:8010/0fe71ff5b710e32b7725.min.js:6:43259)
    at http://127.0.0.1:8010/0fe71ff5b710e32b7725.min.js:6:43778
    at Array.map (native)
    at _ (http://127.0.0.1:8010/0fe71ff5b710e32b7725.min.js:6:43718)
    at Function.a [as mapToProps] (http://127.0.0.1:8010/0fe71ff5b710e32b7725.min.js:33:191188)
    at r (http://127.0.0.1:8010/0fe71ff5b710e32b7725.min.js:6:10781)
    at l (http://127.0.0.1:8010/0fe71ff5b710e32b7725.min.js:6:12169)
    at u (http://127.0.0.1:8010/0fe71ff5b710e32b7725.min.js:6:12287)

**Comment by ivankravets** [comment] 2018-03-06 10:11
Duplicate of https://github.com/platformio/platformio-core/issues/1305

**Closed by ivankravets** 2018-03-06 10:11 UTC
Labels: duplicate
