### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by thricebeau** [platformio/platformio-core#1994] opened 2018-12-27 14:17 UTC
Server error: {"message":"No module named _dumbwin32proc","args":["No module named _dumbwin32proc"],"type":"ImportError"}

Attempt to start a new project. Computer just started. Intel i7-7500, 16GB RAM, Windows 10 x64.

**Comment by ivankravets** [comment] 2018-12-27 22:13
Duplicate of https://github.com/platformio/platformio-core/issues/1993

**Closed by ivankravets** 2018-12-27 22:13 UTC
