### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by davood-dorostkar** [platformio/platformio-core#2801] opened 2019-07-17 05:33 UTC
PIO Core Call Error: "The current working directory C:\\Users\\Davood\\Documents\\Sanatbazar\\03-Github\\pro will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\Davood\\Documents\\Sanatbazar\\03-Github\\pro\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing genericSTM32F103CB (platform: ststm32; board: genericSTM32F103CB; framework: libopencm3)\n-------------------------------------------------------------------------------\nPackageManager: Installing framework-libopencm3 @ ~1.1.0\nframework-libopencm3 @ 1.1.0 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103CB.html\nPLATFORM: ST STM32 5.4.3 > STM32F103CB (20k RAM. 128k Flash)\nHARDWARE: STM32F103CBT6 72MHz, 20KB RAM, 128KB Flash\nDEBUG: Current (blackmagic) External (blackmagic, jlink, stlink)\nPACKAGES: framework-libopencm3 1.1.0, toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)\nIOError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Davood\\\\.platformio\\\\packages\\\\framework-libopencm3\\\\lib\\\\Makefile':\n  File \"C:\\Users\\Davood\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 126:\n    env.SConscript(\"$BUILD_SCRIPT\")\n  File \"C:\\Users\\Davood\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"C:\\Users\\Davood\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\n    exec _file_ in call_stack[-1].globals\n  File \"C:\\Users\\Davood\\.platformio\\platforms\\ststm32\\builder\\main.py\", line 91:\n    target_elf = env.BuildProgram()\n  File \"C:\\Users\\Davood\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"C:\\Users\\Davood\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 112:\n    env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\n  File \"C:\\Users\\Davood\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"C:\\Users\\Davood\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 326:\n    SConscript(env.GetFrameworkScript(f), exports=\"env\")\n  File \"C:\\Users\\Davood\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 604:\n    return method(*args, **kw)\n  File \"C:\\Users\\Davood\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"C:\\Users\\Davood\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\n    exec _file_ in call_stack[-1].globals\n  File \"C:\\Users\\Davood\\.platformio\\platforms\\ststm32\\builder\\frameworks\\libopencm3\\libopencm3.py\", line 181:\n    get_source_files(root_dir)\n  File \"C:\\Users\\Davood\\.platformio\\platforms\\ststm32\\builder\\frameworks\\libopencm3\\libopencm3.py\", line 100:\n    mkdata = parse_makefile_data(join(src_dir, \"Makefile\"))\n  File \"C:\\Users\\Davood\\.platformio\\platforms\\ststm32\\builder\\frameworks\\libopencm3\\libopencm3.py\", line 77:\n    with open(makefile) as f:\n========================= [ERROR] Took 13.02 seconds ========================="

**Comment by ivankravets** [comment] 2019-07-17 09:58
Duplicate of https://github.com/platformio/platform-ststm32/issues/232

**Closed by ivankravets** 2019-07-17 09:58 UTC
