### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by czecht** [platformio/platformio-core#2323] opened 2019-04-16 01:40 UTC
Server error: {"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\ARDUINO\\\\Documents\\\\PlatformIO'","args":[2,"The system cannot find the file specified"],"type":"WindowsError"}
Updated software and created new and get this error!

**Comment by ivankravets** [comment] 2019-04-17 17:17
Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Closed by ivankravets** 2019-04-17 17:17 UTC
