### ISSUE TITLE
Error: Currently, PlatformIO does not support debugging for `ATmega328P/PA`.

### ISSUE THREAD

**Issue by jxsl13** [platformio/platformio-core#3250] opened 2019-11-05 19:07 UTC
I'm o VS Code and getting this error:

Error: Currently, PlatformIO does not support debugging for `ATmega328P/PA`.

```ini
[platformio]
default_envs = myAVR_Board_MK2_2.20

[common]

default_src_filter = 
  +<*> 
  -<.git/> 
  -<.svn/> 
  -<example/> 
  -<examples/> 
  -<test/> 
  -<tests/> 
  -<target/>
  -<shared/>

# C++17 is needed for inline static definitions.
build_flags =
  -std=c++1z
  -std=gnu++1z

# platformIO seems to have an inconsistent behaviour in regard to the
# starting directory. sometimes target/ needs to be prefixed with src/ 
# and sometimes it doesn't need to

[env:stm32f407vg]
platform = ststm32
board = disco_f407vg
;framework = cmsis

src_filter = 
  ${common.default_src_filter} 
  +<target/STM32F407VG/>

build_type = debug
build_flags = 
  ${common.build_flags}
  -D STM32F407VG
  -D DEBUG
 ;-Wl,-T"scripts/target/STM32F407VG/STM32F407VG.ld"

upload_protocol = stlink
upload_port = /dev/cu.usbmodem14103
debug_tool = stlink


[env:lpc1768]
platform = nxplpc
board = lpc1768

src_filter = 
  ${common.default_src_filter} 
  +<target/MCB1760/>

build_type = debug
build_flags = 
  ${common.build_flags}
  -Wl,-T"scripts/target/MCB1760/LPC1768.ld"
  -D MCB1760 
  -D DEBUG

extra_scripts = scripts/target/MCB1760/firmware_patch.py

# J-Link Probe
upload_protocol = jlink-jtag
debug_tool = jlink


# ULINK-ME Probe
;upload_protocol = custom
;upload_flags =
;    -f
;    scripts/interface/cmsis-dap.cfg
;    -f
;    scripts/board/mcb1700.cfg
;
;debug_tool = custom
;debug_server =
;    $PLATFORMIO_CORE_DIR/packages/tool-openocd/bin/openocd
;    -f
;    ../scripts/interface/cmsis-dap.cfg
;    -f
;    ../scripts/board/mcb1700.cfg


# Blackmagic Probe
;upload_protocol = blackmagic
;upload_port = /dev/cu.usbmodem79AC68971
;
;debug_tool = custom
;debug_port = /dev/cu.usbmodem79AC68971
;debug_init_cmds =
;  target extended-remote $DEBUG_PORT
;  monitor swdp_scan
;  attach 1
;  set mem inaccessible-by-default off
;  $INIT_BREAK
;  $LOAD_CMDS


[env:myAVR_Board_MK2_2.20]
platform = atmelavr
board = ATmega328P

src_filter = 
  ${common.default_src_filter} 
  +<target/MYAVR_BOARD_MK2/>

build_type = debug
# build and debugging flags
build_flags = 
  ${common.build_flags}
  -D MYAVR_BOARD_MK2
  -D DEBUG

# upload port.
upload_port = /dev/cu.SLAB_USBtoUART
upload_protocol = avr911
upload_speed = 19200
upload_flags = -e



[env:Arduino_UNO]
platform = atmelavr
board = uno

src_filter = 
  ${common.default_src_filter} 
  +<target/ARDUINO_UNO/>

build_type = debug
# build and debugging flags
build_flags = 
  ${common.build_flags}
  -D ARDUINO_UNO
  -D DEBUG

# upload port.
upload_port = /dev/cu.usbmodem14101


```

**Comment by ivankravets** [comment] 2019-11-06 11:00
Duplicate of https://github.com/platformio/platform-atmelavr/issues/95

**Closed by ivankravets** 2019-11-06 11:00 UTC
