### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by zazzazzaz** [platformio/platformio-core#2476] opened 2019-05-10 14:47 UTC
PIO Core Call Error: "<Exception instance at 0x5714b88 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u015f' in position 115: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-05-11 17:17
Duplicate of https://github.com/platformio/platformio-core/issues/2078

**Closed by ivankravets** 2019-05-11 17:17 UTC
