### ISSUE TITLE
Home: Could not load project examples

### ISSUE THREAD

**Issue by yiweisong** [platformio/platformio-core#2815] opened 2019-07-22 01:57 UTC
'ascii' codec can't decode byte 0xe2 in position 199: ordinal not in range(128)

**Comment by ivankravets** [comment] 2019-07-23 15:24
Duplicate of https://github.com/platformio/platformio-core/issues/2796

**Comment by ivankravets** [comment] 2019-07-23 15:25
What is your OS? Locale?

**Closed by ivankravets** 2019-07-23 15:24 UTC
