### ISSUE TITLE
Why PIO not Support Pic Microcontroller with 8 Bit or 16 Bit or 32 Bit

### ISSUE THREAD

**Issue by MaxBayne** [platformio/platformio-core#4101] opened 2021-11-05 11:47 UTC
i try to use PIO for programming PIC MCU
like 8 Bit Called PIC16F877A
but i cant to do it , any help for that and need answer why PIO Not Support PIC MCU LIke AVR MCU
Thanks

**Comment by ivankravets** [comment] 2021-11-05 12:15
Duplicate of https://github.com/platformio/platformio-core/issues/704

**Closed by ivankravets** 2021-11-05 12:15 UTC

**Comment by s-celles** [comment] 2025-07-16 08:16
@MaxBayne It's a bit late but you may be interested by https://github.com/platformio/platformio-core/issues/704#issuecomment-3075061143 (still very experimental)
