### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by DannyRavi** [platformio/platformio-core#2510] opened 2019-05-18 11:47 UTC
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\Server\\Documents\\PlatformIO\\Projects\\rddr\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: You are not connected to the Internet.\r\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains."

I think about this problem : poor connection Internet to load something.

**Comment by ivankravets** [comment] 2019-05-23 21:20
Duplicate of https://github.com/platformio/platformio-core/issues/2088

**Closed by ivankravets** 2019-05-23 21:20 UTC
