### ISSUE TITLE
Home: Libraries: Search

### ISSUE THREAD

**Issue by PHPJJ** [platformio/platformio-core#2456] opened 2019-05-05 15:21 UTC
PIO Core Call Error: "Error: [API] Internal server error"

I wanted a library that I used before from;
https://github.com/esp8266/Arduino/tree/master/libraries

Cannot load it by giving the URL

**Comment by ivankravets** [comment] 2019-05-06 15:35
Duplicate of https://github.com/platformio/platformio-core/issues/2426

**Closed by ivankravets** 2019-05-06 15:35 UTC
Labels: help wanted
