### ISSUE TITLE
OSError: [Errno 13] Permission denied on nixos

### ISSUE THREAD

**Issue by ShiroUsagi-san** [platformio/platformio-core#1610] opened 2018-05-05 13:39 UTC
Hi, 
I've recently installed platformio on my nixos. the platformio's package comes from the unstable nixpkgs channel and it has the 3.5.2 version. but I'm facing a issue:
when I try to use either platformio home or platformio login, there is no problem but then, I try to use the `platformio test -e uno --verbose` command and I'm having this issue:
```
Warning! Please install `99-platformio-udev.rules` and check that your board's PID and VID are listed in the rules.
http://docs.platformio.org/en/latest/faq.html#platformio-udev-rules
Auto-detected: /dev/ttyACM0
*** [upload] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'
============================================================================================= [ERROR] Took 1.83 seconds ============================================================================================
```
So I said myself "whatever, I'll use sudo to try it out". So I retried with `sudo` before, and then an other strange error appende:
```
Error: Traceback (most recent call last):
  File "/nix/store/wj6ilh98l2kznndq4jzigq0wwqnvappf-python2.7-platformio-3.5.2/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/nix/store/p06yl6rhj9fmlql89py09n7r64awmryb-python2.7-click-5.1/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/p06yl6rhj9fmlql89py09n7r64awmryb-python2.7-click-5.1/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/nix/store/p06yl6rhj9fmlql89py09n7r64awmryb-python2.7-click-5.1/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/p06yl6rhj9fmlql89py09n7r64awmryb-python2.7-click-5.1/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/p06yl6rhj9fmlql89py09n7r64awmryb-python2.7-click-5.1/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/wj6ilh98l2kznndq4jzigq0wwqnvappf-python2.7-platformio-3.5.2/lib/python2.7/site-packages/platformio/commands/test.py", line 67, in cli
    pioplus_call(sys.argv[1:])
  File "/nix/store/wj6ilh98l2kznndq4jzigq0wwqnvappf-python2.7-platformio-3.5.2/lib/python2.7/site-packages/platformio/managers/core.py", line 113, in pioplus_call
    code = subprocess.call([pioplus_path] + args, **kwargs)
  File "/nix/store/l9j2jsc9flrbmpf799nw9wdq59gpwms8-python-2.7.14/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/nix/store/l9j2jsc9flrbmpf799nw9wdq59gpwms8-python-2.7.14/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/nix/store/l9j2jsc9flrbmpf799nw9wdq59gpwms8-python-2.7.14/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
```
a root permission denied?!. I don't get it. I linked my `platform.ini` file too:
```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
```
Thanks helping me on this issue, I'm stuck.

**Comment by ivankravets** [comment] 2018-06-18 16:42
Duplicate of https://github.com/platformio/platformio-core/issues/1638

**Closed by ivankravets** 2018-06-18 16:42 UTC
Labels: PLUS, bug
