### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by SteelPh0enix** [platformio/platformio-core#2587] opened 2019-05-30 06:38 UTC
PIO Core Call Error: "<Exception instance at 0x5ec5348 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\Phoenix\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u0119' in position 123: ordinal not in range(128)\n>"

Happened when i launched VSCode with PIO today. First time, out of the blue.

**Comment by ivankravets** [comment] 2019-05-30 20:16
Duplicate of #2473

**Closed by ivankravets** 2019-05-30 20:16 UTC
