### ISSUE TITLE
Home: Could not load installed platforms

### ISSUE THREAD

**Issue by lodziu** [platformio/platformio-core#2359] opened 2019-04-21 13:26 UTC
Server error: {"message":"No module named _dumbwin32proc","args":["No module named _dumbwin32proc"],"type":"ImportError"}

**Comment by ivankravets** [comment] 2019-04-22 18:13
Duplicate of https://github.com/platformio/platformio-core/issues/2346

Could you provide more details? What is your Windows OS version?

**Closed by ivankravets** 2019-04-22 18:13 UTC
