### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by aemmenet** [platformio/platformio-core#1648] opened 2018-06-01 11:41 UTC
PIO Core Call Error: Platform C:\Users\AemmeNet\.platformio\platforms\espressif32@src-5f117260f75b328038ec9d3fd0e14a68
--------
Updating espressif32                     @ fd9ed71        [Fixed]

Error: Unknown development platform 'espressif32@src-5f117260f75b328038ec9d3fd0e14a68'

**Comment by ivankravets** [comment] 2018-06-01 15:10
Duplicate of https://github.com/platformio/platformio-core/issues/1346

**Closed by ivankravets** 2018-06-01 15:10 UTC
Labels: duplicate
