### ISSUE TITLE
Home: Could not load mDNS services

### ISSUE THREAD

**Issue by nikvla** [platformio/platformio-core#1651] opened 2018-06-02 07:59 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 3 column 119 (char 1916 - 2034)

I get this error when trying to enumerate devices via multicastDNS in VSC on Windows 10 Pro

**Comment by ivankravets** [comment] 2018-06-04 11:55
Duplicate of https://github.com/platformio/platformio-core/issues/1311

**Closed by ivankravets** 2018-06-04 11:55 UTC
