### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by ahmetunlu** [platformio/platformio-core#2039] opened 2019-01-14 09:51 UTC
PIO Core Call Error: "<Exception instance at 0x54b0d48 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xdc' in position 63: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-01-23 17:08
Duplicate of https://github.com/platformio/platformio-core/issues/2038

**Closed by ivankravets** 2019-01-23 17:08 UTC
