### ISSUE TITLE
Home: Platforms: Registry

### ISSUE THREAD

**Issue by serpek** [platformio/platformio-core#2466] opened 2019-05-08 07:54 UTC
PIO Core Call Error: "<Exception instance at 0x773e648 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\******\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 1851-1854: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-05-08 09:43
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Closed by ivankravets** 2019-05-08 09:43 UTC
