### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by thbui** [platformio/platformio-core#1587] opened 2018-04-21 18:55 UTC
PIO Core Call Error: Error: Unknown development platform 'atmelavr@1.8.1'

Got this message while trying to update atmel avr platform

**Comment by ivankravets** [comment] 2018-04-21 23:39
Duplicate of https://github.com/platformio/platformio-core/issues/1346

**Closed by ivankravets** 2018-04-21 23:39 UTC
