### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by garygrub** [platformio/platformio-core#1489] opened 2018-03-23 02:26 UTC
PlatformIO serial monitor finds my Arduino MEGA2560 without issue. However, when I attemp to create a project it can't find the boards list

**Comment by ivankravets** [comment] 2018-03-23 08:08
Duplicate of https://github.com/platformio/platformio-core/issues/1482

**Closed by ivankravets** 2018-03-23 08:08 UTC
