### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by domingosliraneto** [platformio/platformio-core#1060] opened 2017-09-12 00:53 UTC
PIO Core Call Error: got stderr: "sh: module: line 1: syntax error: unexpected end of file\nsh: error importing function definition for `module'\nsh: scl: line 1: syntax error: unexpected end of file\nsh: error importing function definition for `scl'\n"

**Comment by ivankravets** [comment] 2017-09-13 11:06
What is your OS?

**Comment by ivankravets** [comment] 2017-09-13 11:14
Duplicate of https://github.com/platformio/platformio-core/issues/1054

**Closed by ivankravets** 2017-09-13 11:14 UTC
Labels: help wanted, home
