### ISSUE TITLE
Generate "compile_commands.json" for LSP ready IDEs

### ISSUE THREAD

**Issue by pvonmoradi** [platformio/platformio-core#3735] opened 2020-11-12 20:17 UTC
The following command generates the requires files for LSP for plugins like coc-nvim:  
`pio project init --board my_board --ide vim --project-option "framework=arduino"`
Problem is, after mutating the `platformio.ini` and adding libraries, the `.ccls` file is not kept updated.  
How to make it so that all these auxiliary helper files get updated when project dependencies change? I was able to do it with  
`init`ing again.   
Aside from that, I don't think the `.ccls` file should be dependent on project libs alone. Maybe the source does not use a library, so its deps should not be handled by ccls.

**Comment by ivankravets** [comment] 2020-11-13 17:09
Duplicate of https://github.com/platformio/platformio-core/issues/364

**Comment by pvonmoradi** [comment] 2020-11-13 19:26
@ivankravets Thanks. So it is a known issue.  
Is generating the `compile_commands.json` via the post: script and compiledb command, a good alternative? (meaning pointing LSPs to compile_commands.json instead of .ccls)

**Comment by ivankravets** [comment] 2020-11-14 11:29
I updated the title. It is a very good idea to generate `compile_commands.json` for all compatible IDEs. Thanks!

**Comment by pvonmoradi** [comment] 2020-11-14 12:36
@ivankravets But isn't this already implemented? [https://docs.platformio.org/en/latest/integration/compile_commands.html](https://docs.platformio.org/en/latest/integration/compile_commands.html)
Or you mean you are planning the --ide switches to generate this in the project root?

**Comment by ivankravets** [comment] 2020-11-14 12:40
Yes, it makes sense to generate `compile_commands.json` in the root of project.

**Comment by yunuscukran** [comment] 2021-03-14 02:57
> Yes, it makes sense to generate `compile_commands.json` in the root of project.

From my experience, `compile_commands.json` being in the root is required to make `clangd` work properly. As far as ı can tell, this seems like a pre-req for the clangd integration at https://github.com/platformio/platformio-vscode-ide/issues/1802. 

Any timeline for this change?

**Comment by ivankravets** [comment] 2021-03-14 12:38
You can temporarily fix it on your side https://docs.platformio.org/en/latest/integration/compile_commands.html
Just override `COMPILATIONDB_PATH`.

**Closed** 2022-04-09 09:53 UTC
Labels: feature, integration

**Comment by ivankravets** [comment] 2022-04-09 09:55
See updated docs https://docs.platformio.org/en/latest/integration/compile_commands.html

Key changes:

1) The latest PlatformIO Core generates a compilation database in the project root 
2) The new build environment was added to include toolchain paths. See docs for details.

Please confirm that it works now upgrading to the latest development version of PIO Core using `pio upgrade --dev`. Thanks!

**Comment by pvonmoradi** [comment] 2022-04-09 10:46
@ivankravets confirmed that `pio run -t compiledb` creates a `compile_db.json` which is dependent on libraries included that project ini file. clang is able to jump to definition of library functions/methods.
Thanks.

**Comment by ivankravets** [comment] 2022-04-09 12:06
Happy coding with PlatformIO!
