### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by moi65** [platformio/platformio-core#2350] opened 2019-04-20 05:13 UTC
PIO Core Call Error: "<Exception instance at 0x5e1c0a8 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\allam\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe8' in position 664: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-04-20 08:42
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Closed by ivankravets** 2019-04-20 08:42 UTC
