### ISSUE TITLE
platformio remote with multiple test folders: just last one is executed

### ISSUE THREAD

**Issue by peterus** [platformio/platformio-core#3590] opened 2020-07-11 14:25 UTC
- [X] **PlatformIO Core**.

------------------------------------------------------------------

### Configuration

**PlatformIO Version** (`platformio --version`):
PlatformIO, version 4.3.4

### Description of problem
I would like to run multiple test folders via remote command.
First all tests are compiled, than the *last* compiled one is running multiple times on the target.

Example: I have 3 folders: A, B, C
Alle 3 test folders are first compiled into the same build directory.
The last test which was compiled (C) is than tested 3 times on the target as the other compiled firmware was overwritten.

The commands are not very fancy, just the basic ones.
The project is an AVR one.

**Comment by ivankravets** [comment] 2020-07-11 17:03
Duplicate of https://github.com/platformio/platformio-core/issues/3270

**Closed by ivankravets** 2020-07-11 17:03 UTC
