### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by mahmoudnr** [platformio/platformio-core#2850] opened 2019-07-30 16:06 UTC
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\Administrator\\\\Documents\\\\PlatformIO'","type":"WindowsError"}

**Comment by ivankravets** [comment] 2019-08-17 20:01
Do have antivirus tools in a system? They block PlatformIO.

Duplicate of #2321

**Closed by ivankravets** 2019-08-17 20:01 UTC
