### ISSUE TITLE
Support for DA14683

### ISSUE THREAD

**Issue by Kubson320** [platformio/platformio-core#4402] opened 2022-08-27 12:14 UTC
What kind of issue is this?

- [ ] **Feature Request**.
------------------------------------------------------------------
Hello,
Can You add support of DA14683, please.
https://www.renesas.com/eu/en/products/interface-connectivity/wireless-communications/bluetooth-low-energy/da14683-smartbond-bluetooth-low-energy-50-soc-enhanced-security

**Comment by ivankravets** [comment] 2022-08-29 07:45
Duplicate of https://github.com/platformio/platformio-core/issues/4028.

Please vote 👍  for https://github.com/platformio/platformio-core/issues/4028

**Closed** 2022-08-29 07:45 UTC
