### ISSUE TITLE
st-flash: error while loading shared libraries: libstlink-shared.so.1:

### ISSUE THREAD

**Issue by sunqi1993** [platformio/platformio-core#1019] opened 2017-08-18 16:13 UTC
```
$ platformio run --target upload
[Sat Aug 19 00:07:55 2017] Processing stm32f103zet6 (monitor_baud: 115200; platform: ststm32; upload_protocol: stlink; board: stm32f103zet6; framework: stm32cube)
------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Warning! Cannot find a linker script for the required board! Firmware will be linked with a default linker script!
Collected 0 compatible libraries
Looking for dependencies...
No dependencies
Uploading .pioenvs/stm32f103zet6/firmware.bin
st-flash: error while loading shared libraries: libstlink-shared.so.1: cannot open shared object file: No such file or directory
*** [upload] Error 127

```
but in the `/home/sunqi/.platformio/packages/tool-stlink/lib` dir, i can find `libstlink-shared.so.1`

**Comment by ivankravets** [comment] 2017-08-18 17:36
Duplicate of https://github.com/platformio/platform-ststm32/issues/58

**Closed by ivankravets** 2017-08-18 17:36 UTC
Labels: duplicate
