### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by alpellegri** [platformio/platformio-core#1049] opened 2017-09-08 17:19 UTC
PIO Core Call Error: got stderr: 'From https://github.com/esp8266/Arduino\n   fe6f3cc..2ffcb3e  master     -> origin/master\n'

**Comment by ivankravets** [comment] 2017-09-08 19:23
Duplicate of https://github.com/platformio/platformio-core/issues/1038

**Closed by ivankravets** 2017-09-08 19:23 UTC
