### ISSUE TITLE
Board Support: REALTEK AMB82-Mini

### ISSUE THREAD

**Issue by whittenator** [platformio/platformio-core#4809] opened 2023-12-18 23:24 UTC
Requesting support for the Seeed Studio Realtek AMB82-Mini: https://www.seeedstudio.com/AMB82-MINI-RTL8735B-IoT-AI-Camera-Dev-Board-p-5584.html

**Comment by ivankravets** [comment] 2023-12-19 16:59
Duplicate of https://github.com/platformio/platformio-core/issues/769

**Closed by ivankravets** 2023-12-19 16:59 UTC
