### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by KhaledElprince** [platformio/platformio-core#2139] opened 2019-02-18 02:39 UTC
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: /Users/Khaled_El-Prince/Documents/PlatformIO/Projects/espressif-mqtt-publiah/platformio.ini\n\t[line 18]: 'ArduinoJson@5.13.1 \\n''","args":["File contains parsing errors: /Users/Khaled_El-Prince/Documents/PlatformIO/Projects/espressif-mqtt-publiah/platformio.ini\n\t[line 18]: 'ArduinoJson@5.13.1 \\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment] 2019-02-22 23:08
Duplicate of https://github.com/platformio/platformio-core/issues/2074

**Closed by ivankravets** 2019-02-22 23:08 UTC
