### ISSUE TITLE
Generate project main

### ISSUE THREAD

**Issue by KevinOI** [platformio/platformio-core#3337] opened 2020-01-10 08:46 UTC
It would be nice to redefine the main.cpp file.

In **platformio-core\platformio\commands\home\rpc\handlers\project.py** there is a method (**_generate_project_main()**) to generate de default main.cpp.

I have a custom framework and I would like to create a default main.cpp.

Is it possible ?

**Comment by ivankravets** [comment] 2020-01-10 12:53
What will be inside `main.cpp`?

**Comment by KevinOI** [comment] 2020-01-10 13:37
Something like that:

#include "OpenIndus.h"

int main(void)
{

   while(1)
   {
   }
}

I wish I could customize the main.cpp file when I create the project.





Le ven. 10 janv. 2020 à 13:53, Ivan Kravets <notifications@github.com> a
écrit :

**Comment by ivankravets** [comment] 2020-02-06 17:32
Duplicate of https://github.com/platformio/platformio-core/issues/446

**Closed by ivankravets** 2020-02-06 17:32 UTC
Labels: help wanted
