### ISSUE TITLE
Platformio bare framework incorrectly applies C compiler build options to AS

### ISSUE THREAD

**Issue by InnovativeIdeas** [platformio/platformio-core#3513] opened 2020-05-18 13:29 UTC
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

**PlatformIO Version** (`platformio --version`):

#### Steps to Reproduce

1.
2.
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by InnovativeIdeas** [comment] 2020-05-18 13:35
PlatformIO Version 3.2.2

When building projects with assembler code  .S source files build correctly as the GCC compiler is called with assembler option ( -x) and C build options are appended 

BUT , when a .s source is used the GNU assembler is called , but the same C build options are appended , but AS dosnt not recognised these command line options and these fail 

The issue is the line in _pare.py 

"# copy CCFLAGS to ASFLAGS (-x assembler-with-cpp mode)
env.Append(ASFLAGS=env.get("CCFLAGS", [])[:])"

which is incorrect if AS is invoked

**Comment by ivankravets** [comment] 2020-05-19 07:30
1. Please upgrade PIO Core to the latest version via `pio upgrade` command. 
2. This is normal behavior, you need to use .S extension to have build flags from .c

**Comment by InnovativeIdeas** [comment] 2020-05-19 08:50
I don’t think you’ve followed my point , as I said it works as you expect with .S. However if yiu have a .s file , platformio invokes AS directly yet still feeds it C build flags which it doesn’t understand and the assembler faults

**Comment by ivankravets** [comment] 2022-04-02 20:10
Duplicate of https://github.com/platformio/platformio-core/issues/3917

**Closed by ivankravets** 2022-04-02 20:10 UTC
Labels: help wanted, build system
