### ISSUE TITLE
Please add support for the LinkIt 7697

### ISSUE THREAD

**Issue by mikeq3** [platformio/platformio-core#4325] opened 2022-06-17 13:32 UTC
Please add support for the LinkIt 7697.
I see that support is available for the LinkIt Smart 7688 Duo.
Can the LinkIt 7697 be added as well?
I have a couple of these boards and would really like to use platformio to develop with those.

Thanks

**Comment by ivankravets** [comment] 2022-06-17 13:58
Duplicate of https://github.com/platformio/platformio-core/issues/3560

**Closed by ivankravets** 2022-06-17 13:58 UTC
Labels: board, platform, feature
