### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by s3abrz** [platformio/platformio-core#2582] opened 2019-05-29 18:06 UTC
PIO Core Call Error: "CorePackageManager: Installing tool-pioplus @ ^2.3.0\n\n[Error 5] : 'C:\\\\Users\\\\solbianca\\\\.platformio\\\\packages\\\\tool-pioplus\\\\pioplus.exe' \r\nPlease manually remove the file `C:\\Users\\solbianca\\.platformio\\packages\\tool-pioplus\\pioplus.exe`\r\n[Error 5] : 'C:\\\\Users\\\\solbianca\\\\.platformio\\\\packages\\\\tool-pioplus' \r\nPlease manually remove the file `C:\\Users\\solbianca\\.platformio\\packages\\tool-pioplus`\r\nError: Could not install 'tool-pioplus' with version requirements '^2.3.0' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment] 2019-05-30 20:16
Duplicate of #2473

**Closed by ivankravets** 2019-05-30 20:16 UTC
