### ISSUE TITLE
BL808 RISC-V support

### ISSUE THREAD

**Issue by pauljurczak** [platformio/platformio-core#4491] opened 2022-12-12 00:39 UTC
This is a repost of https://community.platformio.org/t/bl808-risc-v-support/30892. 

There are new RISC-V boards popping out almost daily with great price/performance ratio, e.g. Sipeed M1s Dock [M1s DOCK - Sipeed Wiki](https://wiki.sipeed.com/hardware/en/maix/m1s/m1s_dock.html), which is using BL808 RISC-V MCU. It is very likely that the BL602/BL604, BL702/BL704/BL706, BL616/BL618, BL808 family supported by bl_mcu_sdk (https://github.com/bouffalolab/bl_mcu_sdk) will be very popular among makers, and it would be great to have PlatformIO support.

**Comment by ivankravets** [comment] 2022-12-12 12:40
Duplicate of https://github.com/platformio/platformio-core/issues/4046

**Closed by ivankravets** 2022-12-12 12:40 UTC
