### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by polarapfel** [platformio/platformio-core#1461] opened 2018-03-19 18:52 UTC
PIO Core Call Error: Platform /home/polarapfel/.platformio/platforms/ststm32@src-15e0e87f41a00aa2f9602f71367ac29c
--------
Updating ststm32                         @ 29edb61        [b7b27fe]
git version 2.7.4

fatal: Not a git repository: /home/polarapfel/.platformio/platforms/_tmp_installing-JvInPZ-package/.git/modules/builder/frameworks/libopencm3
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment] 2018-03-20 17:34
Duplicate of https://github.com/platformio/platformio-core/issues/1223

**Closed by ivankravets** 2018-03-20 17:34 UTC
