### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by iamaooddy** [platformio/platformio-core#2427] opened 2019-04-28 00:26 UTC
PIO Core Call Error: "Error: Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: /home/evga/Documents/PlatformIO/Projects/ESP32 Experiment/platformio.ini\n\t[line 26]: 'Microgear ESP32 \\n'\n\t[line 29]: 'ArduinoJson@<6.0\\n''"

**Comment by ivankravets** [comment] 2019-05-03 10:36
Duplicate of https://github.com/platformio/platformio-core/issues/2260

**Closed by ivankravets** 2019-05-03 10:36 UTC
