### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by TiniTinyTerminator** [platformio/platformio-core#2141] opened 2019-02-18 10:11 UTC
PIO Core Call Error: "The next files/directories have been created in D:\\OneDrive - Stichting Hogeschool Utrecht\\programmeren\\arduino\\stm32 deltarobot\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing nucleo_f767zi (platform: ststm32; board: nucleo_f767zi; framework: mbed)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/nucleo_f767zi.html\r\nPLATFORM: ST STM32 > ST Nucleo F767ZI\r\nHARDWARE: STM32F767ZIT6 216MHz 512KB RAM (2MB Flash)\r\nDEBUG: CURRENT(stlink) ON-BOARD(stlink) EXTERNAL(blackmagic, jlink)\r\nmbed build API internal error\r\npath is on drive C:, start on drive D:\r\n [ERROR] Took 1.49 seconds"

**Comment by ivankravets** [comment] 2019-02-23 17:00
Duplicate of https://github.com/platformio/platform-ststm32/issues/203

Could you reproduce with the latest version of dev/platform? Please PIO Home  > Platforms > Updates

**Closed by ivankravets** 2019-02-23 17:00 UTC
