### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by samsmith94** [platformio/platformio-core#2297] opened 2019-04-07 14:06 UTC
PIO Core Call Error: "<Exception instance at 0x5d4f448 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe1' in position 60: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-04-17 17:18
Duplicate of https://github.com/platformio/platformio-core/issues/2078

**Closed by ivankravets** 2019-04-17 17:18 UTC
