### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by miki105** [platformio/platformio-core#2258] opened 2019-03-27 16:00 UTC
TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.t.title (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:21892)
    at http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:65718
    at Array.map (<anonymous>)
    at w (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:65694)
    at t.selectLibraryData (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:154910)
    at Function.t.default.osOpenUrl [as mapToProps] (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:63:248622)
    at r (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:17716)
    at m (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:18977)
    at http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:19049
    at Object.run (http://127.0.0.1:8010/8e0671cf68e6dada91e1.min.js:12:15671)

**Comment by ivankravets** [comment] 2019-03-27 21:36
Duplicate of https://github.com/platformio/platformio-core/issues/2033

**Closed by ivankravets** 2019-03-27 21:36 UTC
