### ISSUE TITLE
PlatformIO Core installation script no longer available at indicated URL

### ISSUE THREAD

**Issue by rbergen** [platformio/platformio-core#4715] opened 2023-08-14 07:49 UTC
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide any information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Ubuntu 22.04

**PlatformIO Version** (`platformio --version`): unkown

### Description of problem

The installer script mentioned in the [PlatformIO Core installation instructions](https://docs.platformio.org/en/stable/core/installation/methods/installer-script.html) is no longer available. Attempts to retrieve it from the indicated URL yield an HTTP 404 error.

#### Steps to Reproduce

1. Run the following command in an Ubuntu shell: `python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"`

### Actual Results

The following message is shown: `curl: (22) The requested URL returned error: 404`

### Expected Results

Download of the installer script, followed by the installation of PlatformIO Core.

**Comment by ivankravets** [comment] 2023-08-14 08:01
Duplicate of https://github.com/platformio/platformio-docs/pull/314

Thanks for the report!

**Closed by ivankravets** 2023-08-14 08:02 UTC
