### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by okeokeokeokeoke** [platformio/platformio-core#2415] opened 2019-04-25 16:48 UTC
PIO Core Call Error: "CorePackageManager: Installing tool-pioplus @ ^2.1.4\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\n\n[Error 5] Access is denied: 'C:\\\\Users\\\\agus\\\\.platformio\\\\packages\\\\tool-pioplus\\\\pioplus.exe' \r\nPlease manually remove the file `C:\\Users\\agus\\.platformio\\packages\\tool-pioplus\\pioplus.exe`\r\n[Error 5] Access is denied: 'C:\\\\Users\\\\agus\\\\.platformio\\\\packages\\\\tool-pioplus' \r\nPlease manually remove the file `C:\\Users\\agus\\.platformio\\packages\\tool-pioplus`\r\nError: Could not install 'tool-pioplus' with version requirements '^2.1.4' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment] 2019-04-25 22:17
Duplicate of #2369

**Closed by ivankravets** 2019-04-25 22:17 UTC
