### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by patrikooo1** [platformio/platformio-core#2446] opened 2019-05-02 19:25 UTC
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: /Users/Patrik/Documents/PlatformIO/Projects/Display/platformio.ini, line: 6\n'LiquidCrystal_I2C lcd(0x3F, 16, 2);\\n''","args":["File contains no section headers.\nfile: /Users/Patrik/Documents/PlatformIO/Projects/Display/platformio.ini, line: 6\n'LiquidCrystal_I2C lcd(0x3F, 16, 2);\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment] 2019-05-03 09:58
Duplicate of https://github.com/platformio/platformio-core/issues/2260

**Closed by ivankravets** 2019-05-03 09:58 UTC
