### ISSUE TITLE
test port not automatically recognized in My Esp32 while using GoogleTest

### ISSUE THREAD

**Issue by HareshPrajapati** [platformio/platformio-core#4263] opened 2022-05-14 10:34 UTC
What kind of issue is this?

- [ ] **Development Platform or Board**.
     - Esp32dev or esp32doit-devkit-v1

### Configuration

**Operating system** : 
   - Windows

**PlatformIO Version** (`platformio --version`):    
   - 6.0.0

### Description of problem
 I am trying to do Google test using `esp32dev` board but somehow board doesn't recognised port 
**if i Set it in  `platformio.ini` file than it works fine.**.
Documentation describe that If test_port isn’t specified, then PlatformIO will try to detect it automatically ([here](https://docs.platformio.org/en/stable/projectconf/section_env_test.html#test-port))

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:native]
platform = native
test_framework = googletest

[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32dev
test_framework = googletest
```

**Source file to reproduce issue:**
```cpp
#include <gtest/gtest.h>

TEST(DummyTest, ShouldPass)
{
    EXPECT_EQ(1, 1);
}

void Sub1(int n)
{
    EXPECT_EQ(n, 1);
}

TEST(FooTest, Bar)
{
    {
        SCOPED_TRACE("A"); // This trace point will be included in
                           // every failure in this scope.
        Sub1(1);
    }

    Sub1(1);
}

TEST(SkipTest, DoesSkip)
{
    GTEST_SKIP() << "Skipping single test";
    EXPECT_EQ(0, 1); // Won't fail; it won't be executed
}

#if defined(ARDUINO)
#include <Arduino.h>

void setup()
{   
    delay(5000);
    Serial.begin(115200);
    delay(1000);
    ::testing::InitGoogleTest();
    if (RUN_ALL_TESTS());
}

void loop()
{
    // nothing to be done here.
    delay(100);
}

#else
int main(int argc, char **argv)
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
#endif
```

**Comment by ivankravets** [comment] 2022-05-14 16:45
Sorry, that disturb you. This is issue is duplicate of https://github.com/platformio/platformio-core/issues/4076 
I've just reopened original #4076

**Closed by ivankravets** 2022-05-14 16:45 UTC
Labels: enhancement, unit testing
