### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by mogplus8** [platformio/platformio-core#1184] opened 2017-11-13 08:53 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 4 column 52 (char 142001 - 142101)
Found the problem. There is a file called /etc/host-conf, which has two lines in it, "nospoof on" and "spoofalert on". I commented these two lines out and now it all works fine. I don't know what the file does. There are only two other lines in it, "order hosts,bind" and "multi on". So I guess I'll have to wait and see if anything else odd happens... 
;-) Ian

**Comment by ivankravets** [comment] 2017-11-16 12:55
Do you see any errors when you type `pio boards --json-output` in PIO IDE Terminal?

**Comment by ivankravets** [comment] 2017-11-26 18:29
Duplicate of https://github.com/platformio/platformio-core/issues/1164

**Closed by ivankravets** 2017-11-26 18:29 UTC
Labels: help wanted, home
