### ISSUE TITLE
ValueError: Invalid simple block '0.8.0 ]'

### ISSUE THREAD

**Issue by cjrunner** [platformio/platformio-core#4377] opened 2022-08-02 19:03 UTC
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.
NOTE ===>>>> I installed LoRa.h using the following command line sequence:
wren:LoRa_Receiver cjc$ /Users/cjc/.platformio/penv/bin/pio pkg install --library "sandeepmistry/LoRa@^0.8.0"
Resolving ttgo-lora32-v1 dependencies...
Library Manager: Installing sandeepmistry/LoRa @ ^0.8.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%
Library Manager: LoRa@0.8.0 has been installed!

I then tried to compile my program with the following results:
Processing ttgo-lora32-v1 (platform: platformio/espressif32@5.1.0; board: ttgo-lora32-v1; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Removing unused dependencies...
Error: Traceback (most recent call last):
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/run/cli.py", line 144, in cli
    process_env(
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/run/cli.py", line 201, in process_env
    result = {"env": name, "duration": time(), "succeeded": ep.process()}
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/run/processor.py", line 83, in process
    install_project_env_dependencies(
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/commands/install.py", line 132, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/commands/install.py", line 204, in _install_project_env_libraries
    _uninstall_project_unused_libdeps(project_env, options)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/commands/install.py", line 280, in _uninstall_project_unused_libdeps
    lm.uninstall(spec)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/manager/_uninstall.py", line 29, in uninstall
    return self._uninstall(spec, skip_dependencies)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/manager/_uninstall.py", line 34, in _uninstall
    pkg = self.get_package(spec)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/manager/base.py", line 263, in get_package
    spec = self.ensure_spec(spec)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/manager/base.py", line 133, in ensure_spec
    return spec if isinstance(spec, PackageSpec) else PackageSpec(spec)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/meta.py", line 184, in __init__
    self._parse(self.raw)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/meta.py", line 291, in _parse
    raw = parser(raw)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/meta.py", line 316, in _parse_requirements
    self.requirements = tokens[1].strip()
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/platformio/package/meta.py", line 231, in requirements
    else semantic_version.SimpleSpec(str(value))
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/semantic_version/base.py", line 647, in __init__
    self.clause = self._parse_to_clause(expression)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/semantic_version/base.py", line 1043, in _parse_to_clause
    return cls.Parser.parse(expression)
  File "/Users/cjc/.platformio/penv/lib/python3.10/site-packages/semantic_version/base.py", line 1063, in parse
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block '0.8.0 ]'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================ 

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

**PlatformIO Version** (`platformio --version`):

#### Steps to Reproduce

1.
2.
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

### Additional info

NOTE ===>>>> Source code looks like:
#include <Arduino.h> 

/*********
  Rui Santos
  Complete project details at https://RandomNerdTutorials.com/ttgo-lora32-sx1276-arduino-ide/
*********/

//Libraries for LoRa
#include <SPI.h>
// #include <LoRa.h>
#include <LoRa.h>
//Libraries for OLED Display
#include <Wire.h>
// #include <Adafruit_GFX.h>

// #include <Adafruit_SSD1306.h>
#include <Adafruit_SSD1306.h>
#include <Adafruit_BusIO_Register.h>
#include <Adafruit_I2CDevice.h>
#include <Adafruit_I2CRegister.h>
#include <Adafruit_SPIDevice.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
//define the pins used by the LoRa transceiver module
#define SCK 5
#define MISO 19
#define MOSI 27
#define SS 18
#define RST 14
#define DIO0 26

//433E6 for Asia
//866E6 for Europe
//915E6 for North America
#define BAND 866E6

//OLED pins
#define OLED_SDA 4
#define OLED_SCL 15 
#define OLED_RST 16
#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 64 // OLED display height, in pixels

Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RST);

String LoRaData;

void setup() { 
  //initialize Serial Monitor
  Serial.begin(115200);
  
  //reset OLED display via software
  pinMode(OLED_RST, OUTPUT);
  digitalWrite(OLED_RST, LOW);
  delay(20);
  digitalWrite(OLED_RST, HIGH);
  
  //initialize OLED
  Wire.begin(OLED_SDA, OLED_SCL);
  if(!display.begin(SSD1306_SWITCHCAPVCC, 0x3c, false, false)) { // Address 0x3C for 128x32
    Serial.println(F("SSD1306 allocation failed"));
    for(;;); // Don't proceed, loop forever
  }

  display.clearDisplay();
  display.setTextColor(WHITE);
  display.setTextSize(1);
  display.setCursor(0,0);
  display.print("LORA RECEIVER ");
  display.display();

  Serial.println("LoRa Receiver Test");
  
  //SPI LoRa pins
  SPI.begin(SCK, MISO, MOSI, SS);
  //setup LoRa transceiver module
  LoRa.setPins(SS, RST, DIO0);

  if (!LoRa.begin(BAND)) {
    Serial.println("Starting LoRa failed!");
    while (1);
  }
  Serial.println("LoRa Initializing OK!");
  display.setCursor(0,10);
  display.println("LoRa Initializing OK!");
  display.display();  
}

void loop() {

  //try to parse packet
  int packetSize = LoRa.parsePacket();
  if (packetSize) {
    //received a packet
    Serial.print("Received packet ");

    //read packet
    while (LoRa.available()) {
      LoRaData = LoRa.readString();
      Serial.print(LoRaData);
    }

    //print RSSI of packet
    int rssi = LoRa.packetRssi();
    Serial.print(" with RSSI ");    
    Serial.println(rssi);

   // Dsiplay information
   display.clearDisplay();
   display.setCursor(0,0);
   display.print("LORA RECEIVER");
   display.setCursor(0,20);
   display.print("Received packet:");
   display.setCursor(0,30);
   display.print(LoRaData);
   display.setCursor(0,40);
   display.print("RSSI:");
   display.setCursor(30,40);
   display.print(rssi);
   display.display();   
  }
}
 

NOTE ===>>>> platformio.ini looks like:
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ttgo-lora32-v1]
platform = platformio/espressif32@5.1.0
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200
lib_deps = adafruit/Adafruit SSD1306@^2.5.6

NOTE ===>>>> c_cpp_properties.json looks like:
//
// !!! WARNING !!! AUTO-GENERATED FILE!
// PLEASE DO NOT MODIFY IT AND USE "platformio.ini":
// https://docs.platformio.org/page/projectconf/section_env_build.html#build-flags
//
{
    "configurations": [
        {
            "name": "PlatformIO",
            "includePath": [
                "/Users/cjc/arduino/heltec/esp32/libraries/LoRa/src",
                "/Users/cjc/arduino/Adafruit_GFX_Library-1.11.3",
                "/Users/cjc/arduino/Adafruit_SSD1306-2.5.6",
                "/Users/cjc/arduino/Adafruit_BusIO-master",
                "/Users/cjc/arduino/heltec/esp32/libraries/LoRa/src",
                "/Users/cjc/Documents/PlatformIO/Projects/LoRa_Receiver/include",
                "/Users/cjc/Documents/PlatformIO/Projects/LoRa_Receiver/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/config",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/app_trace",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/app_update",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/asio",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/bootloader_support",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/bt",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/coap",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/console",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/driver",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/efuse",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp-tls",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp32",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_adc_cal",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_event",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_http_client",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_http_server",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_https_ota",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_https_server",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_ringbuf",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_websocket_client",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/espcoredump",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/ethernet",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/expat",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/fatfs",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/freemodbus",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/freertos",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/heap",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/idf_test",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/jsmn",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/json",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/libsodium",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/log",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/lwip",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/mbedtls",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/mdns",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/micro-ecc",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/mqtt",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/nghttp",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/nvs_flash",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/openssl",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/protobuf-c",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/protocomm",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/pthread",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/sdmmc",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/smartconfig_ack",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/soc",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/spi_flash",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/spiffs",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/tcp_transport",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/tcpip_adapter",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/ulp",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/unity",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/vfs",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/wear_levelling",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/wifi_provisioning",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/wpa_supplicant",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/xtensa-debug-module",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp-face",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp32-camera",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/fb_gfx",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/cores/esp32",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/variants/ttgo-lora32-v1",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/ArduinoOTA/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/AsyncUDP/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/AzureIoT/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/BLE/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/BluetoothSerial/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/DNSServer/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/EEPROM/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/ESP32/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/ESPmDNS/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/FFat/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/FS/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/HTTPUpdate/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/HTTPUpdateServer/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/NetBIOS/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/Preferences/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/SD/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/SD_MMC/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/SPI/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/SPIFFS/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/SimpleBLE/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/Ticker/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/Update/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/WebServer/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/WiFiProv/src",
                "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/Wire/src",
                ""
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "path": [
                    "/Users/cjc/Documents/PlatformIO/Projects/LoRa_Receiver/include",
                    "/Users/cjc/Documents/PlatformIO/Projects/LoRa_Receiver/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/config",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/app_trace",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/app_update",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/asio",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/bootloader_support",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/bt",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/coap",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/console",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/driver",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/efuse",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp-tls",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp32",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_adc_cal",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_event",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_http_client",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_http_server",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_https_ota",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_https_server",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_ringbuf",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_websocket_client",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/espcoredump",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/ethernet",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/expat",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/fatfs",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/freemodbus",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/freertos",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/heap",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/idf_test",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/jsmn",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/json",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/libsodium",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/log",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/lwip",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/mbedtls",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/mdns",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/micro-ecc",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/mqtt",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/nghttp",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/nvs_flash",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/openssl",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/protobuf-c",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/protocomm",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/pthread",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/sdmmc",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/smartconfig_ack",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/soc",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/spi_flash",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/spiffs",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/tcp_transport",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/tcpip_adapter",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/ulp",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/unity",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/vfs",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/wear_levelling",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/wifi_provisioning",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/wpa_supplicant",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/xtensa-debug-module",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp-face",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp32-camera",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/fb_gfx",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/cores/esp32",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/variants/ttgo-lora32-v1",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/ArduinoOTA/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/AsyncUDP/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/AzureIoT/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/BLE/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/BluetoothSerial/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/DNSServer/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/EEPROM/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/ESP32/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/ESPmDNS/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/FFat/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/FS/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/HTTPUpdate/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/HTTPUpdateServer/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/NetBIOS/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/Preferences/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/SD/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/SD_MMC/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/SPI/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/SPIFFS/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/SimpleBLE/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/Ticker/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/Update/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/WebServer/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/WiFiProv/src",
                    "/Users/cjc/.platformio/packages/framework-arduinoespressif32/libraries/Wire/src",
                    ""
                ]
            },
            "defines": [
                "PLATFORMIO=60101",
                "ARDUINO_TTGO_LoRa32_V1",
                "ESP32",
                "ESP_PLATFORM",
                "F_CPU=240000000L",
                "HAVE_CONFIG_H",
                "MBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"",
                "ARDUINO=10805",
                "ARDUINO_ARCH_ESP32",
                "ARDUINO_VARIANT=\"ttgo-lora32-v1\"",
                "ARDUINO_BOARD=\"TTGO LoRa32-OLED V1\"",
                ""
            ],
            "cStandard": "c99",
            "cppStandard": "c++11",
            "compilerPath": "/Users/cjc/.platformio/packages/toolchain-xtensa32@2.50200.97/bin/xtensa-esp32-elf-gcc",
            "compilerArgs": [
                "-mlongcalls",
                ""
            ]
        }
    ],
    "version": 4
}

**Comment by ivankravets** [comment] 2022-08-02 19:05
It looks like a duplicate of https://github.com/platformio/platformio-core/issues/4344

Could you remove `.pio` folder from a project and build it again?

**Closed** 2022-08-03 15:30 UTC
Labels: help wanted
