### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by ilyamordasov** [platformio/platformio-core#1450] opened 2018-03-15 06:07 UTC
TypeError: Cannot read property 'name' of null
    at http://127.0.0.1:8010/0fce13c15ea1c9f96851.min.js:6:47094
    at Array.map (native)
    at b (http://127.0.0.1:8010/0fce13c15ea1c9f96851.min.js:6:46965)
    at http://127.0.0.1:8010/0fce13c15ea1c9f96851.min.js:6:47484
    at Array.map (native)
    at _ (http://127.0.0.1:8010/0fce13c15ea1c9f96851.min.js:6:47424)
    at Function.a [as mapToProps] (http://127.0.0.1:8010/0fce13c15ea1c9f96851.min.js:17:244163)
    at r (http://127.0.0.1:8010/0fce13c15ea1c9f96851.min.js:6:10153)
    at l (http://127.0.0.1:8010/0fce13c15ea1c9f96851.min.js:6:11523)
    at u (http://127.0.0.1:8010/0fce13c15ea1c9f96851.min.js:6:11641)

**Comment by ivankravets** [comment] 2018-03-15 12:35
Duplicate of https://github.com/platformio/platformio-core/issues/1305

Did #1305 help you?

**Closed by ivankravets** 2018-03-15 12:35 UTC
