### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by leiyu1139** [platformio/platformio-core#3234] opened 2019-11-03 06:42 UTC
PIO Core Call Error: "The current working directory E:\\Users\\Administrator\\Documents\\PlatformIO\\Projects\\NY_ESP8266_RTOS_SDK_APP will be used for the project.\r\n\r\nThe next files/directories have been created in E:\\Users\\Administrator\\Documents\\PlatformIO\\Projects\\NY_ESP8266_RTOS_SDK_APP\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Detected unknown package 'framework-esp8266-rtos-sdk'"

**Comment by ivankravets** [comment] 2019-11-05 15:20
Duplicate of https://github.com/platformio/platformio-core/issues/3116

**Closed by ivankravets** 2019-11-05 15:20 UTC
