### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by aluisagaspar** [platformio/platformio-core#1938] opened 2018-11-22 14:36 UTC
PIO Core Call Error: Library Storage: C:\Users\aluis\Documents\PlatformIO\Projects\181115-232843-mbed-blink\.piolibdeps
LibraryManager: Installing id=360
Downloading...
Unpacking
Unpacking
microbit-dal @ 2.0.0-rc4.build3 has been successfully installed!
Installing dependencies
LibraryManager: Installing ble

Error: Please install Git client from https://git-scm.com/downloads

**Comment by ivankravets** [comment] 2018-11-27 12:16
Duplicate of https://github.com/platformio/platformio-core/issues/1939

**Closed by ivankravets** 2018-11-27 12:16 UTC
