### ISSUE TITLE
quest for a 

### ISSUE THREAD

**Issue by trimchess** [platformio/platformio-core#1975] opened 2018-12-15 13:49 UTC
- [x] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform
------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`): 3.6.x

### Description of problem 
**Request of PlatformIO suport for the MKR Vidor 4000 board.**

**Comment by ivankravets** [comment] 2018-12-18 17:46
Duplicate of https://github.com/platformio/platform-atmelsam/issues/37

**Closed by ivankravets** 2018-12-18 17:46 UTC
