### ISSUE TITLE
Home: 'utf8' codec can't decode byte

### ISSUE THREAD

**Issue by mihail240461** [platformio/platformio-core#2068] opened 2019-01-24 04:38 UTC
'utf8' codec can't decode byte 0xcd in position 24: invalid continuation byte

**Comment by ivankravets** [comment] 2019-01-29 19:12
What is your Windows version and locale?

**Comment by ivankravets** [comment] 2019-03-07 11:52
Duplicate of https://github.com/platformio/platformio-core/issues/1959

**Closed by ivankravets** 2019-03-07 11:52 UTC
Labels: help wanted, home
