### ISSUE TITLE
Platformio website is down?

### ISSUE THREAD

**Issue by MaliMrav** [platformio/platformio-core#2118] opened 2019-02-12 01:52 UTC
Is the PlatformIO site down?
I cannot connect to the site https://platformio.org

**Comment by honzakucera** [comment] 2019-02-12 01:59
See #2117

**Comment by ivankravets** [comment] 2019-02-23 16:55
Duplicate of https://github.com/platformio/platformio-core/issues/2117

**Closed by ivankravets** 2019-02-23 16:55 UTC

**Comment by diversit** [comment] 2019-10-06 13:12
Website is down again. Or at least not reachable from NL.
docs.platformio.org does seem to work.
Why are you having so much trouble keeping a simple website up?

**Comment by ivankravets** [comment] 2019-10-06 13:45
Everything is online since 2014. 
Could you provide `traceroute PlatformIo.org`?

**Comment by diversit** [comment] 2019-10-14 06:02
Sorry, already resolved.
Apparently it's hosted from Ukraine and I had everything from Ukraine blocked in my firewall.
