### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by bukurat** [platformio/platformio-core#1421] opened 2018-03-07 00:39 UTC
Server error

New install on new install of VS Code after uninstalling atom.

Loading... icon continually rotates.

also PlatformIO: IntelliSense Index failed: Error: Traceback (most recent call last):

**Comment by ivankravets** [comment] 2018-03-07 09:52
Duplicate of https://github.com/platformio/platformio-core/issues/1420

**Closed by ivankravets** 2018-03-07 09:52 UTC
