### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Minzp** [platformio/platformio-core#1811] opened 2018-08-26 15:19 UTC
PIO Core Call Error: The next files/directories have been created in /home/min/Documents/PlatformIO/Projects/LED
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error:

**Comment by ivankravets** [comment] 2018-08-27 17:52
Duplicate of https://github.com/platformio/platformio-core/issues/1616

**Comment by ivankravets** [comment] 2018-08-27 17:52
Which board did you select?

**Closed by ivankravets** 2018-08-27 17:52 UTC

**Comment by Minzp** [comment] 2018-08-28 04:56
Sorry, this is my first time using VScode, also is my first time using Github, and my English is not good, so, I'm very sorry that I didn't reply you in time.

**Comment by Minzp** [comment] 2018-08-28 05:02
STM32F407VET6

**Comment by Minzp** [comment] 2018-08-28 05:12
I'm sorry, I'm using MDK now.
