### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by ed1385** [platformio/platformio-core#1631] opened 2018-05-19 13:53 UTC
PIO Core Call Error: Error: Unknown development platform 'ststm32@3.8.0'

**Comment by ed1385** [comment] 2018-05-19 13:53
ed

**Comment by ivankravets** [comment] 2018-05-22 19:55
Duplicate of https://github.com/platformio/platformio-core/issues/1346

**Closed by ivankravets** 2018-05-22 19:55 UTC
