### ISSUE TITLE
Publish IDE to https://open-vsx.org

### ISSUE THREAD

**Issue by balajib-b** [platformio/platformio-core#4844] opened 2024-01-28 17:25 UTC
What kind of issue is this?

- [ ] **Feature Request**.
publishing to https://open-vsx.org/ would be a good idea for users who use cloud IDE's for programming  and desktop IDE like VScodium(vscode fork without telemetry )

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

**PlatformIO Version** (`platformio --version`):

#### Steps to Reproduce

1.
2.
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by ivankravets** [comment] 2024-01-28 17:26
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/1802

**Closed by ivankravets** 2024-01-28 17:26 UTC
