### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by boykod** [platformio/platformio-core#1374] opened 2018-02-17 17:29 UTC
PIO Core Call Error: Platform /home/dmitry/.platformio/platforms/espressif8266@src-d2f6a4ecb96f34425e5e701de09dc0a9
--------
Updating espressif8266                   @ 3039807        [Up-to-date]
Updating tool-mkspiffs                   @ 1.200.0        [Up-to-date]
Updating tool-esptool                    @ 1.409.0        [Up-to-date]
Updating tool-espotapy                   @ 1.1.0          [Up-to-date]
Updating framework-arduinoespressif8266  @ c3bd91a        [ad42ab6]
git version 2.16.1

From https://github.com/esp8266/Arduino
   c3bd91a..ad42ab6  master     -> origin/master
fatal: Not a git repository: /home/dmitry/.platformio/packages/_tmp_installing-DtYVEq-package/.git/modules/lwip2
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment] 2018-02-17 17:36
Duplicate of https://github.com/platformio/platformio-core/issues/1223

**Closed by ivankravets** 2018-02-17 17:36 UTC
