### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by AndreyGrand** [platformio/platformio-core#2112] opened 2019-02-09 20:05 UTC
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\Users\\Gerankin-EIS\\Documents\\PlatformIO\\Projects\\STM32-habr\\platformio.ini\n\t[line 21]: 'include''","args":["File contains parsing errors: C:\\Users\\Gerankin-EIS\\Documents\\PlatformIO\\Projects\\STM32-habr\\platformio.ini\n\t[line 21]: 'include'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment] 2019-02-22 23:08
Duplicate of https://github.com/platformio/platformio-core/issues/2074

**Closed by ivankravets** 2019-02-22 23:08 UTC
