### ISSUE TITLE
Redboard Artemis ATP

### ISSUE THREAD

**Issue by maximax88** [platformio/platformio-core#4665] opened 2023-06-17 22:19 UTC
Hello, 

I tried to use an Artemis ATP redboard from sparkfun with a Raspberry pi 4 and arduino or platformio and it doesn't work.

Is there something I make wrong?

Sorry for my english.

------------------------------------------------------------------

I have openplotter on Raspberry pi 4.

**Comment by ivankravets** [comment] 2023-06-19 13:51
Duplicate of https://github.com/platformio/platformio-core/issues/2709

**Closed by ivankravets** 2023-06-19 13:52 UTC
