### ISSUE TITLE
Home: Could not list directory/Users/USERNAME/Documents/PlatformIO/Projects

### ISSUE THREAD

**Issue by engali94** [platformio/platformio-core#2169] opened 2019-02-26 11:39 UTC
Invalid params: {"type":"TypeError","args":["'cmp' is an invalid keyword argument for this function"],"message":"'cmp' is an invalid keyword argument for this function"}

**Comment by ivankravets** [comment] 2019-03-04 18:04
Could you reproduce this issue after IDE restart?

**Comment by ivankravets** [comment] 2019-03-07 11:54
Please reopen if you still need help

**Comment by ivankravets** [comment] 2019-04-17 17:24
Duplicate of https://github.com/platformio/platformio-core/issues/2327

**Closed** 2019-04-17 17:26 UTC
Labels: help wanted
