### ISSUE TITLE
[BUG] PlatformIO Registry links to nonexistent release notes

### ISSUE THREAD

**Issue by marcelstoer** [platformio/platformio-core#4878] opened 2024-03-20 07:17 UTC
What kind of issue is this?

- [x] **PlatformIO Registry**.

The Registry site links to release notes on the versions page. 
Example: https://registry.platformio.org/libraries/thingpulse/ESP8266%20and%20ESP32%20OLED%20driver%20for%20SSD1306%20displays/versions.

The "Release Notes" links use `xxx/releases/tag/v<version>` as a pattern - note the 'v' prefix. The `version` in `library.json`, however, specifies the version without the 'v' prefix. Hence, the link is dead.

**Comment by ivankravets** [comment] 2024-03-20 14:16
Duplicate of https://github.com/platformio/platformio-registry/issues/39

**Closed by ivankravets** 2024-03-20 14:16 UTC
