### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by nmaas87** [platformio/platformio-core#1041] opened 2017-09-05 19:15 UTC
PIO Core Call Error: got stderr: "Error: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'windows_x86'\r\n"

Trying to install Linux ARM on Windows 10

**Comment by nmaas87** [comment] 2017-09-05 19:18
Seems like it could not install 

toolchain-gccarmlinuxgnueabi | toolchain |   | ~1.40802.0

**Comment by ivankravets** [comment] 2017-09-05 19:24
Duplicate of https://github.com/platformio/platform-linux_arm/issues/2

Sorry, we don't have toolchain for cross-compilation for ARM desktop.

**Closed by ivankravets** 2017-09-05 19:24 UTC
