### ISSUE TITLE
**Feature Request** Arduino Nano Every (ATMega4809)

### ISSUE THREAD

**Issue by tinutac** [platformio/platformio-core#2895] opened 2019-08-11 17:43 UTC
- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

Hi, 
Is there any plan to add Arduino Nano Every to PlatformIO?
Thanks!

**Comment by ivankravets** [comment] 2019-08-17 20:40
Duplicate of https://github.com/platformio/platform-atmelavr/issues/112

**Closed by ivankravets** 2019-08-17 20:40 UTC
