### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by gonraul** [platformio/platformio-core#2487] opened 2019-05-12 14:12 UTC
PIO Core Call Error: "CorePackageManager: Installing tool-pioplus @ ^2.1.4\r\nDownloading...\r\nUnpacking...\n\n[Error 5] Acceso denegado: 'C:\\\\Users\\\\grele\\\\.platformio\\\\packages\\\\tool-pioplus\\\\pioplus.exe' \r\nPlease manually remove the file `C:\\Users\\grele\\.platformio\\packages\\tool-pioplus\\pioplus.exe`\r\n[Error 5] Acceso denegado: 'C:\\\\Users\\\\grele\\\\.platformio\\\\packages\\\\tool-pioplus' \r\nPlease manually remove the file `C:\\Users\\grele\\.platformio\\packages\\tool-pioplus`\r\nError: Could not install 'tool-pioplus' with version requirements '^2.1.4' for your system 'windows_x86'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment] 2019-05-13 21:49
Duplicate of #2473

**Closed by ivankravets** 2019-05-13 21:49 UTC
