### ISSUE TITLE
"Missed J-Link Device ID for malyanM200v2

### ISSUE THREAD

**Issue by salfter** [platformio/platformio-core#2249] opened 2019-03-24 22:16 UTC
This popup occurred when I opened the PlatformIO homepage in VSCode (on Gentoo Linux, if it matters):

Server error: {"message":"Missed J-Link Device ID for malyanM200v2","args":["Missed J-Link Device ID for malyanM200v2"],"type":"AssertionError"}

**Comment by ivankravets** [comment] 2019-03-27 21:40
what is malyanM200v2? Where did you find it?

**Comment by ivankravets** [comment] 2019-03-27 21:41
Duplicate of https://github.com/platformio/platformio-core/issues/1990

**Closed by ivankravets** 2019-03-27 21:41 UTC
Labels: help wanted

**Comment by salfter** [comment] 2019-03-28 05:21
Whatever was causing the problem seems to have been fixed, as it's no longer occurring.
