### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by mogplus8** [platformio/platformio-core#1769] opened 2018-07-26 07:17 UTC
PIO Core Call Error: The next files/directories have been created in /home/ian/PlatformIO/Pro mini
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Processing pro16MHzatmega328 (platform: atmelavr; board: pro16MHzatmega328; framework: arduino)
--------------------------------------------------------------------------------
Traceback (most recent call last):
File "/home/ian/.platformio/packages/tool-scons/script/scons", line 97, in <module>
import pkg_resources
File "/home/ian/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 950, in <module>
class Environment:
File "/home/ian/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 954, in Environment
self, search_path=None, platform=get_supported_platform(),
File "/home/ian/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 183, in get_supported_platform
plat = get_build_platform()
File "/home/ian/.platformio/penv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 383, in get_build_platform
from sysconfig import get_platform
File "/usr/lib/python2.7/sysconfig.py", line 10, in <module>
'stdlib': '{base}/'+sys.lib+'/python{py_version_short}',
AttributeError: 'module' object has no attribute 'lib'
========================== [ERROR] Took 0.11 seconds ==========================

**Comment by ivankravets** [comment] 2018-07-26 21:30
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/210

**Closed by ivankravets** 2018-07-26 21:30 UTC
