### ISSUE TITLE
Feature Request - ESP32 board LilyGO-T-ETH-POE

### ISSUE THREAD

**Issue by malvavgtu** [platformio/platformio-core#4579] opened 2023-03-22 15:28 UTC
I would like suppport for the ESP32 board LilyGO-T-ETH-POE.
Thanks

**Comment by ivankravets** [comment] 2023-03-22 15:56
Duplicate of https://github.com/platformio/platform-espressif32/issues/475

**Closed by ivankravets** 2023-03-22 15:56 UTC

**Comment by malvavgtu** [comment] 2023-03-22 16:35
It is not in the boards list.
