### ISSUE TITLE
Removal of library dependancy when they are external

### ISSUE THREAD

**Issue by freedib** [platformio/platformio-core#3800] opened 2021-01-15 02:26 UTC
What kind of issue is this?

- [ X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Linux Ubuntu 20.04.1 LTS

**PlatformIO Version** (`platformio --version`): 5.0.4

### Description of problem

When a library depends on an external library (defined on github), it install the dependency correctly but is unable to uninstall it.

It seems to be a SemVer error on the version of the dependency library. Once installed, if I remove the version of the dependency library, the library manager it is able to remove it.

1. in library.json of uni-ws2812.git (full version at the end)
       .....
        "dependencies": [{
                "name": "uni-esp",
                "version": "https://github.com/freedib/uni-esp.git#1.0.0"
        }]

2. Manual installation of libraries
     pio lib install https://github.com/freedib/uni-ws2812.git#1.0.0
         uni-ws2812 @ 1.0.0+sha.efa2472 has been installed!
         uni-esp @ 1.0.0+sha.88730a2 has been installed!
3. Manual removal of libraries
     pio lib uninstall uni-ws2812@1.0.0
         Removing uni-ws2812 @ 1.0.0+sha.efa2472
         Library Manager: Removing dependencies...
         ...crash...

### Actual Results
  The last lines of the dump are:

  File ".../python3.8/site-packages/platformio/package/meta.py", line 117, in __init__
    self.requirements = requirements
  File ".../python3.8/site-packages/platformio/package/meta.py", line 162, in requirements
    else semantic_version.SimpleSpec(str(value))
  File ".../python3.8/site-packages/semantic_version/base.py", line 618, in __init__
    self.clause = self._parse_to_clause(expression)
  File ".../python3.8/site-packages/semantic_version/base.py", line 1014, in _parse_to_clause
    return cls.Parser.parse(expression)
  File ".../python3.8/site-packages/semantic_version/base.py", line 1034, in parse
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block 'uni-esp'

#### Steps to Reproduce

Just issue the 2 following commands (same problem with a project and no --global)
    pio lib --global install https://github.com/freedib/uni-ws2812.git#1.0.0
    pio lib --global uninstall uni-ws2812@1.0.0
    ... crash ...

The dependent library can be uninstalled without problem.
    pio lib --global uninstall uni-esp@1.0.0

### Expected Results

No crash :-)

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

### Additional info

https://github.com/freedib/uni-ws2812.git#1.0.0 / library.json

{
	"name": "uni-ws2812",
	"keywords": "neopixel,ws2812,uart,esp8266",
	"description": "Module to control WS2812 Neopixel thru UART of ESP8266",
	"version": "1.0.0",
	"authors": {
		"name": "Didier Bertrand",
		"email": "diblibre@gmail.com",
		"maintainer": true
	},
	"frameworks": "arduino, esp8266-nonos-sdk, esp8266-rtos-sdk",
	"platforms": "*",
	"dependencies":
		[
		    {
		        "name": "uni-esp",
		        "version": "https://github.com/freedib/uni-esp#1.0.0"
		    }
		]
}

https://github.com/freedib/uni-esp.git#1.0.0 / library.json

{
	"name": "uni-esp",
	"keywords": "system,esp8266",
	"description": "ESP8266 frameworks unification",
	"version": "1.0.0",
	"authors": {
		"name": "Didier Bertrand",
		"email": "diblibre@gmail.com",
		"maintainer": true
	},
	"frameworks": "arduino, esp8266-nonos-sdk, esp8266-rtos-sdk",
	"platforms": "*"
}

**Comment by ivankravets** [comment] 2021-01-26 17:10
Duplicate of https://github.com/platformio/platformio-core/issues/3816

Please re-test with `pio upgrade --dev`.

**Closed by ivankravets** 2021-01-26 17:10 UTC
Labels: package management
