### ISSUE TITLE
Add support for parsing `platform.txt` directly.

### ISSUE THREAD

**Issue by skorokithakis** [platformio/platformio-core#750] opened 2016-08-18 11:30 UTC
Parsing `platform.txt` directly from the frameworks' source tree would allow people to just clone the library and have it work, even if there have been linker flag changes. It would be great if support for this could be added.

**Comment by comino** [comment] 2016-08-22 15:43
+1

**Comment by ivankravets** [comment] 2018-06-02 13:33
Duplicate of https://github.com/platformio/platformio-core/issues/969

**Closed by ivankravets** 2018-06-02 13:33 UTC
Labels: enhancement, vendor:arduino
