### ISSUE TITLE
Feature request: submit to Open-VSX

### ISSUE THREAD

**Issue by sdaitzman** [platformio/platformio-core#3679] opened 2020-09-22 14:55 UTC
**Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

### Description of problem
Because Platform-IO is not listed in the Open VSX store, it doesn't show up in VSCodium.

### Additional Information

https://github.com/VSCodium/vscodium/issues/508

**Comment by ivankravets** [comment] 2020-09-22 18:07
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/1802

**Closed by ivankravets** 2020-09-22 18:07 UTC
