### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by cathymcintosh** [platformio/platformio-core#1453] opened 2018-03-15 22:07 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 3 column 92 (char 3184 - 3275)

**Comment by ivankravets** [comment] 2018-03-16 15:42
Duplicate of https://github.com/platformio/platformio-core/issues/1311

**Closed by ivankravets** 2018-03-16 15:42 UTC
