### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by doriade** [platformio/platformio-core#2432] opened 2019-04-28 23:31 UTC
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: /Users/Kz02/Documents/PlatformIO/Projects/slot/platformio.ini\n\t[line 15]: '1''","args":["File contains parsing errors: /Users/Kz02/Documents/PlatformIO/Projects/slot/platformio.ini\n\t[line 15]: '1'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment] 2019-05-03 09:58
Duplicate of https://github.com/platformio/platformio-core/issues/2260

**Closed by ivankravets** 2019-05-03 09:58 UTC
