### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by chrinchiva** [platformio/platformio-core#2059] opened 2019-01-22 16:33 UTC
Server error: {"message":"invalid literal for int() with base 10: ''","args":["invalid literal for int() with base 10: ''"],"type":"ValueError"}

**Comment by ivankravets** [comment] 2019-01-22 19:15
Duplicate of https://github.com/platformio/platformio-core/issues/2058

**Closed by ivankravets** 2019-01-22 19:15 UTC
