### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Troupal** [platformio/platformio-core#1856] opened 2018-09-22 08:52 UTC
'ascii' codec can't encode character u'\xc9' in position 44: ordinal not in range(128)

**Comment by ivankravets** [comment] 2018-09-26 13:44
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Closed by ivankravets** 2018-09-26 13:44 UTC

**Comment by Troupal** [comment] 2018-09-30 13:10
I am not on Windows OS but on GNU/Linux Manjaro. Which doesn't seem to match the issue 143.

**Comment by ivankravets** [comment] 2018-10-03 13:33
Do you have non-ascii chars in the path?
