### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by Schmithtrigger** [platformio/platformio-core#2420] opened 2019-04-26 08:16 UTC
PIO Core Call Error: "CorePackageManager: Installing tool-pioplus @ ^2.0.0\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\n\n[Error 5] Acesso negado: 'C:\\\\Users\\\\schmith\\\\.platformio\\\\packages\\\\tool-pioplus\\\\pioplus.exe' \r\nPlease manually remove the file `C:\\Users\\schmith\\.platformio\\packages\\tool-pioplus\\pioplus.exe`\r\n[Error 5] Acesso negado: 'C:\\\\Users\\\\schmith\\\\.platformio\\\\packages\\\\tool-pioplus' \r\nPlease manually remove the file `C:\\Users\\schmith\\.platformio\\packages\\tool-pioplus`\r\nError: Could not install 'tool-pioplus' with version requirements '^2.0.0' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment] 2019-04-27 12:24
Duplicate of #2369

**Closed by ivankravets** 2019-04-27 12:24 UTC
