### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by lgLindstrom** [platformio/platformio-core#1851] opened 2018-09-20 15:08 UTC
'ascii' codec can't encode character u'\xf6' in position 45: ordinal not in range(128)

**Comment by dontsovcmc** [comment] 2018-09-20 18:33
same with: https://github.com/platformio/platformio-core/issues/1845

**Comment by ivankravets** [comment] 2018-09-21 17:02
Duplicate of https://github.com/platformio/platformio-core/issues/1845

**Closed by ivankravets** 2018-09-21 17:02 UTC
