### ISSUE TITLE
cannot import name 'threadpool' from 'twisted.python

### ISSUE THREAD

**Issue by marcus266** [platformio/platformio-core#3176] opened 2019-10-21 13:55 UTC
PIO Core Call Error: "cannot import name 'threadpool' from 'twisted.python' (unknown location)"

**Comment by ivankravets** [comment] 2019-10-24 16:21
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment] 2019-10-28 12:21
Duplicate of https://github.com/platformio/platformio-core/issues/3189

**Closed by ivankravets** 2019-10-28 12:21 UTC
Labels: help wanted
