### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by Philip64** [platformio/platformio-core#2412] opened 2019-04-25 13:43 UTC
PIO Core Call Error: "<Exception instance at 0x5998fc8 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\DEVELOPER\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe1' in position 722: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-05-03 10:43
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Closed by ivankravets** 2019-05-03 10:43 UTC
