### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Tinyblack** [platformio/platformio-core#2135] opened 2019-02-15 01:38 UTC
PIO Core Call Error: "The next files/directories have been created in H:\\TDPS\\Novel Feature\\Code File\\TDPS_NOVEL\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing disco_f100rb (platform: ststm32; board: disco_f100rb; framework: mbed)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/disco_f100rb.html\r\nPLATFORM: ST STM32 > ST STM32VLDISCOVERY\r\nHARDWARE: STM32F100RBT6 24MHz 8KB RAM (128KB Flash)\r\nDEBUG: CURRENT(stlink) ON-BOARD(stlink) EXTERNAL(blackmagic, jlink)\r\nmbed build API internal error\r\npath is on drive I:, start on drive H:\r\n [ERROR] Took 2.79 seconds"

**Comment by ivankravets** [comment] 2019-02-23 17:00
Duplicate of https://github.com/platformio/platform-ststm32/issues/203

Could you reproduce with the latest version of dev/platform? Please PIO Home  > Platforms > Updates

**Closed by ivankravets** 2019-02-23 17:00 UTC
