### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by IP-Daemon** [platformio/platformio-core#2416] opened 2019-04-25 18:10 UTC
'utf8' codec can't decode byte 0xc8 in position 9: invalid continuation byte

**Comment by IP-Daemon** [comment] 2019-04-25 18:13
Platformio:
Home 2.0.2 Core 3.6.7 

VSC:
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.3.9600

in progress of loading recent project

**Comment by ivankravets** [comment] 2019-04-25 22:18
Do projects contain non-ascii chars?

**Comment by ivankravets** [comment] 2019-05-03 10:43
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Closed by ivankravets** 2019-05-03 10:43 UTC
Labels: help wanted
