### ISSUE TITLE
Home: Could not list directory/Users/luyuan/Documents/PlatformIO/Projects

### ISSUE THREAD

**Issue by Echanging** [platformio/platformio-core#3166] opened 2019-10-20 11:33 UTC
Server error: {"args":[1,"Operation not permitted"],"message":"[Errno 1] Operation not permitted: '/Users/luyuan/Documents/PlatformIO/Projects'","type":"PermissionError"}

**Comment by ivankravets** [comment] 2019-10-20 11:56
Duplicate of https://github.com/platformio/platformio-core/issues/3167

**Closed by ivankravets** 2019-10-20 11:56 UTC
