### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by TechnoElectro** [platformio/platformio-core#2923] opened 2019-08-19 08:54 UTC
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\BDB1\\\\Documents\\\\PlatformIO'","type":"WindowsError"}

**Comment by ivankravets** [comment] 2019-08-19 09:53
Duplicate of https://github.com/platformio/platformio-core/issues/2321

Could you try to turn off Antivirus tools for PlatformIO? Does it work now?

**Closed by ivankravets** 2019-08-19 09:53 UTC
