### ISSUE TITLE
Home: Could not load mDNS services

### ISSUE THREAD

**Issue by brezuicabogdan** [platformio/platformio-core#1582] opened 2018-04-19 12:53 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 3 column 142 (char 13461 - 13602)

**Comment by ivankravets** [comment] 2018-04-20 12:57
What is your OS?

**Comment by brezuicabogdan** [comment] 2018-04-20 13:34
Windows 10 Pro updated to latest version. The problem went away after reading installing the vs code plugin and restarting the computer

**Comment by ivankravets** [comment] 2018-04-20 13:39
Please reopen if you still need help

**Comment by ivankravets** [comment] 2018-11-19 17:21
Duplicate of https://github.com/platformio/platformio-core/issues/1311

**Closed by ivankravets** 2018-11-19 17:21 UTC
Labels: home, known issue
