### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by exothink** [platformio/platformio-core#1086] opened 2017-09-26 17:55 UTC
PIO Core Call Error: Usage: platformio lib [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "-d" / "--storage-dir": Directory "C:\Users\je\Documents\PlatformIO\Projects\_4sqBase111216\~\Documents\Arduino\libraries" does not exist.

**Comment by exothink** [comment] 2017-09-26 17:57
Using PIO Home to update the libraries.  It appears that it is appending the library path to the current project path instead of just using the library path.

**Comment by ivankravets** [comment] 2017-09-27 10:00
Duplicate of https://github.com/platformio/platformio-core/issues/1085

**Closed by ivankravets** 2017-09-27 10:00 UTC
