### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by hop666** [platformio/platformio-core#2179] opened 2019-03-02 12:12 UTC
PIO Core Call Error: "The next files/directories have been created in /Users/hop/Documents/PlatformIO/Projects/ReClock\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Processing nucleo_l011k4 (platform: ststm32; board: nucleo_l011k4; framework: mbed)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/nucleo_l011k4.html\nPLATFORM: ST STM32 > ST Nucleo L011K4\nHARDWARE: STM32L011K4T6 32MHz 2KB RAM (16KB Flash)\nDEBUG: CURRENT(stlink) ON-BOARD(stlink) EXTERNAL(blackmagic, jlink)\nmbed build API internal error\nTarget NUCLEO_L011K4 is not supported by toolchain GCC_ARM\n========================== [ERROR] Took 0.60 seconds =========================="

**Comment by ivankravets** [comment] 2019-03-03 17:09
Duplicate of https://github.com/platformio/platformio-core/issues/2178

**Closed by ivankravets** 2019-03-03 17:09 UTC
