### ISSUE TITLE
Support for Ameba Arduino: [RTL8195] [RTL8710]

### ISSUE THREAD

**Issue by ebergmundur** [platformio/platformio-core#1119] opened 2017-10-14 10:57 UTC
What kind of issue is this?

- [X] PlatformIO Core. If you’ve found a bug, please provide an information below.

Support for Ameba Arduino: [RTL8195] [RTL8710] would be much appreciated 

https://www.amebaiot.com/en/ameba-sdk-boards/

**Comment by ivankravets** [comment] 2017-10-16 10:25
Duplicate of https://github.com/platformio/platformio-core/issues/769

**Closed by ivankravets** 2017-10-16 10:25 UTC
