### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by rocketstrong600** [platformio/platformio-core#2262] opened 2019-03-28 07:19 UTC
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\12102376\\Documents\\PlatformIO\\Projects\\test\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing stm8sblue (platform: ststm8; board: stm8sblue; framework: spl)\r\n\r\nPackageManager: Installing framework-ststm8spl @ 0.20301.181217\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm8/stm8sblue.html\r\nPLATFORM: ST STM8 > ST STM8S103F3 Breakout Board\r\nHARDWARE: STM8S103F3P6 16MHz 1KB RAM (8KB Flash)\r\nError: Could not parse library files for the target.\r\nstm8s.h:2723:25: fatal error: stm8s_conf.h: No such file or directory\r\n\r\n********************************************************************\r\n* Looking for stm8s_conf.h dependency? Check our library registry!\r\n*\r\n* CLI  > platformio lib search \"header:stm8s_conf.h\"\r\n* Web  > https://platformio.org/lib/search?query=header:stm8s_conf.h\r\n*\r\n********************************************************************\r\n\r\ncompilation terminated.\r\n [ERROR] Took 154.03 seconds"

**Comment by ivankravets** [comment] 2019-03-29 18:22
Duplicate of https://github.com/platformio/platform-ststm8/issues/8

**Closed by ivankravets** 2019-03-29 18:22 UTC
