### ISSUE TITLE
Error de inicialización de CLR: 800736b1 (platformio-ide-terminal v 2.7.0 / atom 1.22.1 x64)

### ISSUE THREAD

**Issue by joseluismillan** [platformio/platformio-core#1192] opened 2017-11-18 13:40 UTC
when I try to open a new terminal, appear this issue... 
I try to reinstall atom
I try to reinstall the terminal
and nothing, I can't find the error code anywhere

**Comment by ivankravets** [comment] 2017-11-20 11:12
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/414

**Closed by ivankravets** 2017-11-20 11:12 UTC
