### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by die-tueftelei** [platformio/platformio-core#2992] opened 2019-09-12 16:13 UTC
'ascii' codec can't decode byte 0xcc in position 55: ordinal not in range(128)

Any Idea how to fix this ?

**Comment by ivankravets** [comment] 2019-09-13 15:16
Duplicate of https://github.com/platformio/platformio-core/issues/2796

See my comment in https://github.com/platformio/platformio-core/issues/2796#issuecomment-514324620

**Closed by ivankravets** 2019-09-13 15:16 UTC
