### ISSUE TITLE
Seeed Studio XIAO nRF52840 Sense

### ISSUE THREAD

**Issue by ericphilbaz** [platformio/platformio-core#4602] opened 2023-04-19 02:28 UTC
please  add the seeed board "Seeed Studio XIAO nRF52840 Sense", the board repo is : 
 https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json

**Comment by maxgerhardt** [comment] 2023-04-19 12:13
Duplicate of https://github.com/platformio/platform-nordicnrf52/issues/142 and will be fixed by https://github.com/platformio/platform-nordicnrf52/pull/151

**Closed** 2023-04-21 10:49 UTC
