### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by demsergey** [platformio/platformio-core#2332] opened 2019-04-17 15:16 UTC
PIO Core Call Error: "<Exception instance at 0x7f2a1bcfb680 with str error:\n Traceback (most recent call last):\n  File \"/home/usr/.platformio/packages/contrib-pysite/twisted/python/reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 58-66: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-04-17 17:18
Duplicate of https://github.com/platformio/platformio-core/issues/2078

**Closed by ivankravets** 2019-04-17 17:18 UTC
