### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by pricesc85** [platformio/platformio-core#1742] opened 2018-07-14 19:46 UTC
PIO Core Call Error: Library Storage: C:\Users\price\Documents\PlatformIO\Projects\180127-135652-esp32dev\.piolibdeps
Updating arduino-esp32                   @ abc6c29        [3a4ec66]
git version 2.14.1.windows.1

Fetching submodule libraries/BLE
fatal: refusing to merge unrelated histories
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment] 2018-07-15 17:41
Duplicate of https://github.com/platformio/platformio-core/issues/1223

**Closed by ivankravets** 2018-07-15 17:41 UTC
