### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by mado1362** [platformio/platformio-core#2301] opened 2019-04-09 11:17 UTC
PIO Core Call Error: "PlatformManager: Installing ST STM8\n\nError: Detected unknown package 'ST STM8'"

**Comment by ivankravets** [comment] 2019-04-17 18:08
Duplicate of https://github.com/platformio/platform-ststm8/issues/6

**Closed by ivankravets** 2019-04-17 18:08 UTC
