### ISSUE TITLE
Home: Could not uninstall platform

### ISSUE THREAD

**Issue by ollleg** [platformio/platformio-core#1402] opened 2018-02-26 22:05 UTC
PIO Core Call Error: Uninstalling espressif32 @ 0.12.0: 	[OK]
Uninstalling framework-arduinoespressif32 @ 1.4.0: 	[OK]
Uninstalling framework-espidf @ 2.211.0: 	[OK]
Uninstalling tool-espotapy @ 1.1.0: 	[OK]
Uninstalling tool-esptoolpy @ 1.20100.0: 	[OK]
Uninstalling toolchain-xtensa32 @ 2.50200.80: 	[OK]

Error: Detected unknown package '/.../.platformio/packages/toolchain-xtensa32@1.50200.2 @ 1.50200.2'

**Comment by ivankravets** [comment] 2018-03-06 10:10
Duplicate of https://github.com/platformio/platformio-core/issues/1282

**Closed by ivankravets** 2018-03-06 10:10 UTC
