### ISSUE TITLE
CurieBLE Library does not work

### ISSUE THREAD

**Issue by resonance20** [platformio/platformio-core#1007] opened 2017-08-03 19:30 UTC
I am using the PlatformIO extension with Visual Studio Code. While attempting to program a Genuino 101, the code stops executing at BLEPeripheral.begin(). This also stops all future code from executing. This code compiles and runs perfectly with the Arduino IDE.

**Comment by ivankravets** [comment] 2017-08-03 22:24
Duplicate of https://github.com/platformio/platform-intel_arc32/issues/2

**Closed by ivankravets** 2017-08-03 22:24 UTC
Labels: duplicate
