### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by zxf1025** [platformio/platformio-core#1544] opened 2018-03-30 18:04 UTC
PIO Core Call Error: The next files/directories have been created in C:\Users\z\Documents\PlatformIO\Projects\stm32f103 time
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Could not install 'toolchain-gccarmnoneeabi' with version requirements '>=1.60301.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment] 2018-04-04 17:08
Duplicate of https://github.com/platformio/platformio-core/issues/1530

**Closed by ivankravets** 2018-04-04 17:08 UTC
