### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by juergenschubert** [platformio/platformio-core#2768] opened 2019-07-09 16:06 UTC
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: '/Users/juergenschubert/Documents/ESP8266/PlatformIO/Projects/ESP32 CAM/CameraWebServer'","type":"OSError"}

**Comment by ivankravets** [comment] 2019-07-09 16:32
Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Closed by ivankravets** 2019-07-09 16:32 UTC
