### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by arferdz** [platformio/platformio-core#3238] opened 2019-11-04 08:11 UTC
PIO Core Call Error: "The current working directory C:\\Users\\ferdz\\Documents\\PlatformIO\\Projects\\191104-161056-esp-wrover-kit will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\ferdz\\Documents\\PlatformIO\\Projects\\191104-161056-esp-wrover-kit\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Detected unknown package 'tool-scons'"

**Comment by ivankravets** [comment] 2019-11-05 15:20
Duplicate of https://github.com/platformio/platformio-core/issues/3116

**Closed by ivankravets** 2019-11-05 15:20 UTC
