### ISSUE TITLE
Add Realtek RTL8720DN(BW16) chip

### ISSUE THREAD

**Issue by luxin88** [platformio/platformio-core#4080] opened 2021-10-12 09:57 UTC
Realtek RTL8720DN is a Wi-Fi and Bluetooth IC that supports 2.4GHz and 5GHz dual bands for Wi-Fi communication, and Bluetooth Low Energy (BLE) 5.0. BW16 is a module manufactured by B&T, this module is a highly integrated Wi-Fi and Bluetooth module with the RTL8720DN as the main SoC (System on Chip), it can be regarded as an SoC for the Wi-Fi and Bluetooth application with typical SBCs.

https://www.amebaiot.com/en/amebad-bw16-arduino-getting-started/ 
https://github.com/ambiot/ambd_arduino

**Comment by ivankravets** [comment] 2021-10-15 17:46
Duplicate of https://github.com/platformio/platformio-core/issues/769

**Closed as completed by ivankravets** 2021-10-15 17:46 UTC
