### ISSUE TITLE
Home: Error occurred while requesting content from http://dl.platformio.org/libraries/examples/37/3782/OLED_Bitmap_Inverse_Display.ino

### ISSUE THREAD

**Issue by watershade** [platformio/platformio-core#1681] opened 2018-06-14 06:01 UTC
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at c.crossDomainError (http://127.0.0.1:8010/d7e69906dadeacfea693.min.js:17:185763)
    at XMLHttpRequest.c._end.t.onreadystatechange (http://127.0.0.1:8010/d7e69906dadeacfea693.min.js:17:186970)

**Comment by ivankravets** [comment] 2018-06-15 13:51
Duplicate of https://github.com/platformio/platformio-core/issues/1426

**Closed by ivankravets** 2018-06-15 13:51 UTC
