### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by GerardoBueno** [platformio/platformio-core#3235] opened 2019-11-03 15:16 UTC
PIO Core Call Error: "The current working directory /Users/gebr/Documents/PlatformIO/Projects/191103-151520-nanoatmega328 will be used for the project.\n\nThe next files/directories have been created in /Users/gebr/Documents/PlatformIO/Projects/191103-151520-nanoatmega328\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing atmelavr\natmelavr @ 1.15.0 has been successfully installed!\nPackageManager: Installing toolchain-atmelavr @ ~1.50400.0\ntoolchain-atmelavr @ 1.50400.190710 has been successfully installed!\nThe platform 'atmelavr' has been successfully installed!\nThe rest of packages will be installed automatically depending on your build environment.\n\n\nError: Processing nanoatmega328 (platform: atmelavr; board: nanoatmega328; framework: arduino)\n--------------------------------------------------------------------------------\nPackageManager: Installing framework-arduinoavr @ ~4.1.1\nframework-arduinoavr @ 4.1.2 has been successfully installed!\nCorePackageManager: Installing tool-scons @ ~3.30101.0\ntool-scons @ 3.30101.0 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/nanoatmega328.html\nPLATFORM: Atmel AVR 1.15.0 > Arduino Nano ATmega328\nHARDWARE: ATMEGA328P 16MHz, 2KB RAM, 30KB Flash\nPACKAGES: toolchain-atmelavr 1.50400.190710 (5.4.0), framework-arduinoavr 4.1.2\nLDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf\nLDF Modes: Finder ~ chain, Compatibility ~ soft\nFound 5 compatible libraries\nScanning dependencies...\nNo dependencies\nCorePackageManager: Installing tool-unity @ ~1.20403.0\nInternetIsOffline: You are not connected to the Internet.\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains.:\n  File \"/Users/gebr/.platformio/penv/lib/python3.8/site-packages/platformio/builder/main.py\", line 165:\n    env.DumpIDEData(projenv)  # pylint: disable=undefined-variable\n  File \"/Users/gebr/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"/Users/gebr/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/pioide.py\", line 149:\n    _dump_includes(env, projenv),\n  File \"/Users/gebr/.platformio/penv/lib/python3.8/site-packages/platformio/builder/tools/pioide.py\", line 53:\n    unity_dir = get_core_package_dir(\"tool-unity\")\n  File \"/Users/gebr/.platformio/penv/lib/python3.8/site-packages/platformio/managers/core.py\", line 89:\n    return pm.install(name, requirements)\n  File \"/Users/gebr/.platformio/penv/lib/python3.8/site-packages/platformio/managers/core.py\", line 55:\n    PackageManager.install(self, name, requirements, *args, **kwargs)\n  File \"/Users/gebr/.platformio/penv/lib/python3.8/site-packages/platformio/managers/package.py\", line 703:\n    pkg_dir = self._install_from_piorepo(name, requirements)\n  File \"/Users/gebr/.platformio/penv/lib/python3.8/site-packages/platformio/managers/package.py\", line 455:\n    util.internet_on(raise_exception=True)\n  File \"/Users/gebr/.platformio/penv/lib/python3.8/site-packages/platformio/util.py\", line 409:\n    raise exception.InternetIsOffline()\n========================== [FAILED] Took 8.79 seconds =========================="

**Comment by ivankravets** [comment] 2019-11-05 15:25
Duplicate of https://github.com/platformio/platformio-core/issues/1348

**Closed by ivankravets** 2019-11-05 15:25 UTC
