### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by AsyaSyarif** [platformio/platformio-core#2095] opened 2019-02-03 07:21 UTC
PIO Core Call Error: "Platform C:\\Users\\asyar\\.platformio\\platforms\\espressif8266\r\n--------\r\nUpdating espressif8266                   @ 1.8.0          [Up-to-date]\r\nUpdating tool-mkspiffs                   @ 1.200.0        [Up-to-date]\r\nUpdating tool-esptool                    @ 1.413.0        [Up-to-date]\n\nError: Detected unknown package 'C:\\Users\\asyar\\.platformio\\packages\\tool-espotapy @ ~1.1.0'"

**Comment by ivankravets** [comment] 2019-02-23 16:12
Duplicate of https://github.com/platformio/platformio-core/issues/2072

**Closed by ivankravets** 2019-02-23 16:12 UTC
