### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by virtorgan** [platformio/platformio-core#2010] opened 2019-01-01 22:00 UTC
PIO Core Call Error: "<Exception instance at 0x4e72488 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\daniel\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe8' in position 949: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-01-09 14:57
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Closed by ivankravets** 2019-01-09 14:57 UTC
