### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Derak78** [platformio/platformio-core#2239] opened 2019-03-21 14:08 UTC
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: /home/derak/Documents/PlatformIO/Projects/myIMU/platformio.ini, line: 10\n'v\\n''","args":["File contains no section headers.\nfile: /home/derak/Documents/PlatformIO/Projects/myIMU/platformio.ini, line: 10\n'v\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment] 2019-03-21 22:01
Duplicate of https://github.com/platformio/platformio-core/issues/2198

**Closed by ivankravets** 2019-03-21 22:01 UTC
