### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by lanmushan** [platformio/platformio-core#1740] opened 2018-07-14 13:13 UTC
PIO Core Call Error: The next files/directories have been created in C:\Users\Administrator\Documents\PlatformIO\Projects\test
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: 
Processing genericSTM32F103ZE (platform: ststm32; board: genericSTM32F103ZE; framework: stm32cube)

Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'genericSTM32F103ZE'
 [ERROR] Took 0.94 seconds 

 [SUMMARY] 
Environment genericSTM32F103RC	[SKIP]
Environment genericSTM32F103ZC	[SKIP]
Environment microduino32_flash	[SKIP]
Environment genericSTM32F103ZE	[ERROR]
 [ERROR] Took 0.94 seconds

**Comment by ivankravets** [comment] 2018-07-14 13:46
Duplicate of https://github.com/platformio/platformio-core/issues/1738

**Closed by ivankravets** 2018-07-14 13:46 UTC
