### ISSUE TITLE
How to download packages manually?

### ISSUE THREAD

**Issue by Gianthard-cyh** [platformio/platformio-core#3835] opened 2021-02-06 06:53 UTC
I am a user from China and the speed of downloading packages is extremely low.
I've found the comment from @jiladahe1997 in #3425 :
>If it's slow with downloading platformio packages (like stm32HAL library, gcctools, which platformio will download automatically after you create a new project).
>you could download it manually here:http://dl.bintray.com/platformio/ . And then just copy them to .platformio\packages\ .

the speed of http://dl.bintray.com/platformio/ is high.
However, after I downloaded the tar.gz file and unzipped it, I started building and get this:
![image](https://user-images.githubusercontent.com/45843411/107111388-bb2d0f00-688a-11eb-99bc-52d37d3db882.png)
It seems that PIO didn't recognize the package and still tries to download it.
So how do I install the package manually from http://dl.bintray.com/platformio/?
![image](https://user-images.githubusercontent.com/45843411/107111439-224ac380-688b-11eb-85cf-c0f0e4fbc415.png)

**Comment by Gianthard-cyh** [comment] 2021-02-06 06:58
我是一个来自中国的用户。PIO自带的包管理器下载速度很慢。我在 #3425 中找到了 @jiladahe1997 的回复：
>If it's slow with downloading platformio packages (like stm32HAL library, gcctools, which platformio will download automatically after you create a new project).
you could download it manually here:http://dl.bintray.com/platformio/ . And then just copy them to .platformio\packages\

所以我从http://dl.bintray.com/platformio/ 下载了.tar.gz文件放在了.platformio\packages\目录下，但是我再次运行生成任务的时候，PIO的包管理器又开始下载我已经下好的包。
所以如何正确地手动安装PIO包？

**Comment by ivankravets** [comment] 2021-02-10 11:37
Could you try these links from our own CDNs?

- CDN1 => https://dl.registry.nm1.platformio.org/tools/c9/17/f2c97dab926bb74d65343a647d20b75450201aface6a1ab6071556a640a1/toolchain-xtensa-windows_amd64-2.100100.200706.tar.gz
- CDN2 => https://dl.registry.ns1.platformio.org/tools/c9/17/f2c97dab926bb74d65343a647d20b75450201aface6a1ab6071556a640a1/toolchain-xtensa-windows_amd64-2.100100.200706.tar.gz

So, where is a good speed?

**Comment by Gianthard-cyh** [comment] 2021-02-10 11:40
> Could you try these links from our own CDNs?
> 
> * CDN1 => https://dl.registry.nm1.platformio.org/tools/c9/17/f2c97dab926bb74d65343a647d20b75450201aface6a1ab6071556a640a1/toolchain-xtensa-windows_amd64-2.100100.200706.tar.gz
> * CDN2 => https://dl.registry.ns1.platformio.org/tools/c9/17/f2c97dab926bb74d65343a647d20b75450201aface6a1ab6071556a640a1/toolchain-xtensa-windows_amd64-2.100100.200706.tar.gz
> 
> So, where is a good speed?

the first one. How do I change the CDN to it?

**Comment by ivankravets** [comment] 2021-02-10 11:43
We changed the priority for China on our side. So, please run `pio system prune -f` and try building project.

Does it download fast automatically now?

**Comment by Gianthard-cyh** [comment] 2021-02-10 11:46
> We changed the priority for China on our side. So, please run `pio system prune -f` and try building project.
> 
> Does it download fast automatically now?

![image](https://user-images.githubusercontent.com/45843411/107506136-a200c700-6bd8-11eb-99fe-21275b1fc937.png)
It looks nice now. Thank you very much.

**Comment by Gianthard-cyh** [comment] 2021-02-10 11:47
> > We changed the priority for China on our side. So, please run `pio system prune -f` and try building project.
> > Does it download fast automatically now?
> 
> ![image](https://user-images.githubusercontent.com/45843411/107506136-a200c700-6bd8-11eb-99fe-21275b1fc937.png)
> It looks nice now. Thank you very much.

**Comment by ivankravets** [comment] 2021-02-10 11:47
Thanks for the report! Happy coding with PlatformIO!

**Comment by Gianthard-cyh** [comment] 2021-03-25 17:08
I'm sorry to say that, but the speed when I init a project for the first time is really low.
Have you changed the CDN when init a project for the first time to CDN 2?

**Comment by ivankravets** [comment] 2021-03-25 17:29
What is the speed for https://dl.registry.nm1.platformio.org/tools/c9/17/f2c97dab926bb74d65343a647d20b75450201aface6a1ab6071556a640a1/toolchain-xtensa-windows_amd64-2.100100.200706.tar.gz ?

**Comment by Gianthard-cyh** [comment] 2021-03-26 05:31
> What is the speed for https://dl.registry.nm1.platformio.org/tools/c9/17/f2c97dab926bb74d65343a647d20b75450201aface6a1ab6071556a640a1/toolchain-xtensa-windows_amd64-2.100100.200706.tar.gz ?

It's slow. About 30kB/s

**Comment by ivankravets** [comment] 2021-03-26 09:50
Do you have a Linux machine? Please provide an output of the next commands:
# 1
```
traceroute platformio.org
```

# 2

```
traceroute nm1.platformio.org
```

**Comment by Gianthard-cyh** [comment] 2021-03-26 11:10
> Do you have a Linux machine? Please provide an output of the next commands:
> 
> # 1
> ```
> traceroute platformio.org
> ```
> 
> # 2
> ```
> traceroute nm1.platformio.org
> ```

![image](https://user-images.githubusercontent.com/45843411/112623120-e7b2df80-8e66-11eb-9979-20a35e7a87ba.png)
![image](https://user-images.githubusercontent.com/45843411/112623141-ebdefd00-8e66-11eb-8bac-b415f76ae527.png)

**Comment by ivankravets** [comment] 2021-03-29 10:08
How about a speed for this package?
- https://dl.registry.platformio.org/libraries/03/df/56123fae2b834c2b805c4c1b5e6d3382e38849c8b5b44a03f9b71b2d7680/LovyanGFX-0.3.10.tar.gz

**Comment by Gianthard-cyh** [comment] 2021-04-03 02:38
> How about a speed for this package?
> 
> * https://dl.registry.platformio.org/libraries/03/df/56123fae2b834c2b805c4c1b5e6d3382e38849c8b5b44a03f9b71b2d7680/LovyanGFX-0.3.10.tar.gz

about 1MB/s.

**Comment by Gianthard-cyh** [comment] 2021-04-03 14:36
However , the speeds of all the CDNs are swinging. They are different between machines ,even from time to time,

**Comment by Gianthard-cyh** [comment] 2021-04-03 14:37
> However , the speeds of all the CDNs are swinging. They are different between machines ,even from time to time,

maybe a speed test of usable CDNs is needed before downloading.

**Comment by ivankravets** [comment] 2021-04-04 17:07
What is the right solution for this case? Is it possible to contact your government and ask them to unblock our servers? I don't see another option here. We tried 3 different data centers and all are blocked and speed is limited.

**Comment by ivankravets** [comment] 2021-04-04 17:07
I also know that China government blocked https://pypi.org/. I don't have any words on how to explain this reason.

**Comment by Gianthard-cyh** [comment] 2021-04-05 02:31
> What is the right solution for this case? Is it possible to contact your government and ask them to unblock our servers? I don't see another option here. We tried 3 different data centers and all are blocked and speed is limited.

Thank you very much for your reply.
I'm so sorry that China government has blocked your servers. I do not have the right to ask the government to unblock it . Although the speeds are swinging, some of them have acceptable speed at a certain time. Set up a mirror server in China may be a long time goal. So Focus on the present, just choose the CDN with better speed automatically before every download. It will increase user experience.
Thank you for making PIO better!

**Comment by ivankravets** [comment] 2021-04-05 10:01
Could you advise us of a few VPS providers in China that work with non-Chinese customers?

**Comment by Gianthard-cyh** [comment] 2021-04-05 11:33
> Could you advise us of a few VPS providers in China that work with non-Chinese customers?

https://www.alibabacloud.com/
https://intl.cloud.tencent.com/

Thank you very much for your reply.
According to the law, websites in China must be registered, including VPS and CDN, and must use Chinese ID card, so you should find a person in charge in China to apply for the record. Otherwise, ports 80 and 443 will be blocked when resolving the domain name, and testpage184 will be displayed. So if you want to use a domain name and want to use port 80, the only solution is to choose a person in charge in China. If not, you can use another port. If you just want to build an image for storing files in China, a more affordable way is to use OSS (object storage service). It will provide a storage space, as well as a default domain name, so that you can access the above files. However, if you want to use other domain names, you still need to apply for the record. Also, servers in China Hongkong is an option, and they don't need record.

I'm still asking my friends for the providers they advise.

**Comment by ivankravets** [comment] 2021-04-05 11:58
Sounds crazy strange. Can't imagine how to resolve this issue in the 21st century.

**Comment by ivankravets** [comment] 2021-04-05 12:13
Sounds crazy strange. Can't imagine how to resolve this issue in the 21st century.

P.S: I tried to register at Tencent and their service works "well". See a picture below. It seems they block people outside China as well.

![Screen Shot 2021-04-05 at 14 51 54](https://user-images.githubusercontent.com/1760209/113572689-62c38500-9621-11eb-9e78-2a14bceeb3d9.png)

**Comment by Gianthard-cyh** [comment] 2021-04-09 14:17
> Sounds crazy strange. Can't imagine how to resolve this issue in the 21st century.
> 
> P.S: I tried to register at Tencent and their service works "well". See a picture below. It seems they block people outside China as well.
> 
> ![Screen Shot 2021-04-05 at 14 51 54](https://user-images.githubusercontent.com/1760209/113572689-62c38500-9621-11eb-9e78-2a14bceeb3d9.png)

nodecache.com
This may be a good choice, which doesn't need record in China.

**Comment by ivankravets** [comment] 2021-04-09 14:18
@Gianthard-cyh do you mean if use direct IP on a non HTTP port your government will not block us?

**Comment by Gianthard-cyh** [comment] 2021-04-09 14:21
> @Gianthard-cyh do you mean if use direct IP on a non HTTP port your government will not block us?

yes, and some providers like https://www.nodecache.com/Pricing doesn't need record, which means you can use your domain and HTTP port when using their CDN product

**Comment by Gianthard-cyh** [comment] 2021-04-09 14:29
> @Gianthard-cyh do you mean if use direct IP on a non HTTP port your government will not block us?

Just for servers in China. This can avoid record. But for your servers outside China, They block IPs, which means that there is no way except setting up a server in China.

**Comment by ivankravets** [comment] 2021-04-09 14:31
Could you email me directly via me@ikravets.com? I'll provide some internal links based on different IPs and ports. We would be thankful if you test them. Thanks!

**Comment by Gianthard-cyh** [comment] 2021-04-09 14:32
> Could you email me directly via [me@ikravets.com](mailto:me@ikravets.com)? I'll provide some internal links based on different IPs and ports. We would be thankful if you test them. Thanks!

OK. Thank you!

**Comment by ivankravets** [comment] 2021-04-19 20:12
Should be fixed on our side. Please try to install any package. Does it work fast now?

**Closed by ivankravets** 2021-04-19 20:12 UTC
Labels: registry

**Comment by dkwiqmd** [comment] 2022-09-05 15:26
so vpn

**Comment by ivankravets** [comment] 2022-09-27 15:29
@dkwiqmd , do experience ay problems with downloading packages?

**Comment by developer-ken** [comment] 2022-10-07 10:46
Is it possible to configure which mirror should pio use, just like `source.list` for apt? 
It would be great that we can mirror pio packages in our school lab and make it easier for students to learn and use pio. 

I now providing them with a compressed file of my `~/.platformio` folder, but when any package got an update, pio will download them again, at a very slow speed. Actually we can have a whole afternoon doing no work just downloading packages. It will be great if we can just have a local mirror, then we only need to download it once and fast distribute them to local computers.

**Comment by radonyl** [comment] 2022-11-05 18:02
According to https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html#local-folder
Since version 6.0, `pio pkg install` can install packages manually from directories, archive files or custom links.

@Gianthard-cyh 
a package will only be recongized when there is a `.piopm` file in its directory which is generate locally, so directly copy and paste downloaded packagse will not work. Use the `pio pkg install file://path_to_directory` instead.

**Comment by developer-ken** [comment] 2023-01-22 14:20
> Is it possible to configure which mirror should pio use, just like `source.list` for apt? It would be great that we can mirror pio packages in our school lab and make it easier for students to learn and use pio.
> 
> I now providing them with a compressed file of my `~/.platformio` folder, but when any package got an update, pio will download them again, at a very slow speed. Actually we can have a whole afternoon doing no work just downloading packages. It will be great if we can just have a local mirror, then we only need to download it once and fast distribute them to local computers.
> 
> I am in China, 'Inter'net is not quite international here and developers have to eventually figure out a way to got a proxy. We can hardly view github without a proxy. There is actually someone selling pio packages here because they are not so easy to get by official mirror. Tha's awful.

I am now running a reverse proxy in China with my registered domain, which works well for me and most students in the lab. Also I noticed the official server got a huge download speed increase now, installing packages is possible even without special tricks. I guess the problem is solved somehow.  
Can't understand why our gov block those download servers which contains absolutely legal contents.

**Comment by nikito7** [comment] 2023-10-01 11:55
Slow again. Europe

**Comment by ivankravets** [comment] 2023-10-02 07:42
@nikito7 , what is your country? What is your download speed for https://dl.registry.platformio.org/download/espressif/tool/toolchain-xtensa-esp32/12.2.0+20230208/toolchain-xtensa-esp32-darwin_arm64-12.2.0+20230208.tar.gz ?

**Comment by nikito7** [comment] 2023-10-02 08:23
> @nikito7 , what is your country? What is your download speed for https://dl.registry.platformio.org/download/espressif/tool/toolchain-xtensa-esp32/12.2.0+20230208/toolchain-xtensa-esp32-darwin_arm64-12.2.0+20230208.tar.gz ?

It's ok now. But it happen sometimes.

![Screenshot_20231002_092055](https://github.com/platformio/platformio-core/assets/45373783/5459d75e-dd7a-4273-ae5b-c3a5fecff9dd)

**Comment by dizjis** [comment] 2024-05-17 09:11
So slow, very slow. Russia
![image](https://github.com/platformio/platformio-core/assets/37826964/aa0c014b-6583-48ba-99c5-104ad1d322fc)
> https://dl.registry.platformio.org/download/espressif/tool/toolchain-xtensa-esp32/12.2.0+20230208/toolchain-xtensa-esp32-darwin_arm64-12.2.0+20230208.tar.gz ?

on this link the speed is 15kb/s 
![image](https://github.com/platformio/platformio-core/assets/37826964/6d239e89-e1b9-4eee-a5f6-e9bae43f817e)

>tracert platformio.org

![image](https://github.com/platformio/platformio-core/assets/37826964/502f6679-0401-45c7-b365-8e212d59c360)

**Comment by ivankravets** [comment] 2024-05-17 09:24
Could you try again?

**Comment by dizjis** [comment] 2024-05-17 09:26
> Could you try again?

its ok.Thank you very much
