### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by scottdarch** [platformio/platformio-core#1069] opened 2017-09-13 04:45 UTC
PIO Core Call Error: got stderr: "sh: gitsubmodule_recursive: line 1: syntax error: unexpected end of file\nsh: error importing function definition for `gitsubmodule_recursive'\nsh: showpr: line 1: syntax error: unexpected end of file\nsh: error importing function definition for `showpr'\n"

**Comment by ivankravets** [comment] 2017-09-13 11:15
Duplicate of https://github.com/platformio/platformio-core/issues/1054

**Closed by ivankravets** 2017-09-13 11:15 UTC
