### ISSUE TITLE
Feature Request: Locally installed libraries not in `lib_deps` be removed

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-core#3376] opened 2020-02-13 05:37 UTC
- [x] **Feature Request**

Firstly, apologies if this was asked and closed in another issue... I had a quick look but couldn't see anything. 

Current behaviour of PlatformIO is to install missing libraries per the `platformio.ini lib_deps` parameter. However, in the reverse, it does not remove locally installed libraries no longer listed in `lib_deps`, which can result in compilation errors if a library is no longer used in a project, but still present in the `.pio/libdeps/env-name`. 

Is this a deliberate design choice to prevent other issues, or could it be made so that the library management routine does this sort of cleanup also?

**Comment by ivankravets** [comment] 2020-02-13 12:43
Duplicate of https://github.com/platformio/platformio-core/issues/3076

Yes, we know about this issue and will fix it when a new registry will be released. We want to refactor the package manager in PIO core.

**Closed by ivankravets** 2020-02-13 12:43 UTC
