### ISSUE TITLE
Home: Could not list directoryC:\Users\giuse\SendTo

### ISSUE THREAD

**Issue by Lettly** [platformio/platformio-core#1106] opened 2017-10-05 14:18 UTC
Could not list directory by `C:\Users\giuse\SendTo`

**Comment by ivankravets** [comment] 2017-10-17 23:15
Please open PlatformIO IDE Terminal and type
```
pio home
```

Now, it should be opened in your browser. Do you see any errors in a console?

**Comment by ivankravets** [comment] 2017-10-19 12:27
Duplicate of https://github.com/platformio/platformio-core/issues/1105

**Closed by ivankravets** 2017-10-19 12:27 UTC
Labels: help wanted, home
