### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by TrDA-hab** [platformio/platformio-core#3125] opened 2019-10-15 13:39 UTC
PIO Core Call Error: "Platform C:\\Users\\Admin\\.platformio\\platforms\\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf\n--------\nUpdating espressif8266                   @ 4db7ada        [Up-to-date]\nUpdating tool-esptoolpy                  @ 1.20600.0      [Up-to-date]\nUpdating tool-mkspiffs                   @ 1.200.0        [Up-to-date]\nUpdating tool-esptool                    @ 1.413.0        [Up-to-date]\nUpdating framework-arduinoespressif8266  @ 7ee793e        [11c3757]\r\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment] 2019-10-17 18:49
Duplicate of https://github.com/platformio/platformio-core/issues/3033

Did you modify files in `C:\Users\Admin\.platformio\platforms\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf`?

**Closed by ivankravets** 2019-10-17 18:49 UTC
