### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by gakarl** [platformio/platformio-core#1357] opened 2018-02-12 21:03 UTC
PIO Core Call Error: Platform /Users/gkarl/.platformio/platforms/nordicnrf51
--------

Error: Unknown development platform '/Users/gkarl/.platformio/platforms/nordicnrf51'

**Comment by ivankravets** [comment] 2018-02-14 11:55
Duplicate of https://github.com/platformio/platformio-core/issues/1350

**Closed by ivankravets** 2018-02-14 11:55 UTC
