### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Abdullah-ece** [platformio/platformio-core#2868] opened 2019-08-05 09:45 UTC
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\Abdullah Al-lababidy\\\\Documents\\\\PlatformIO\\\\Projects\\\\test'","type":"WindowsError"}

**Comment by ivankravets** [comment] 2019-08-17 19:49
Do have antivirus tools in a system? They block PlatformIO.

Duplicate of #2321

**Closed by ivankravets** 2019-08-17 19:49 UTC
