### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by dehein** [platformio/platformio-core#1253] opened 2017-12-20 16:06 UTC
As far as i could tell, the thing, which was not available in python 3 was Scons. But it seems the latest release supports python 3.5+.

Is it possible now to change to normal Python?

**Comment by ivankravets** [comment] 2017-12-22 09:45
Duplicate of https://github.com/platformio/platformio-core/issues/895

**Closed by ivankravets** 2017-12-22 09:45 UTC
