### ISSUE TITLE
platformio init --ide clion --board uno - fail

### ISSUE THREAD

**Issue by igronin** [platformio/platformio-core#1097] opened 2017-09-30 20:27 UTC
### Configuration

**Operating system**:

**PlatformIO Version** (`platformio --version`):

### Description of problem

d:\Program\igor\arduino\platformioTest6>platformio init --ide clion --board uno
****************************************************************************************************************************************
Obsolete PIO Core v3.4.1 is used (previous was 3.5.0a16)
Please remove multiple PIO Cores from a system:
http://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system
****************************************************************************************************************************************

The current working directory d:\Program\igor\arduino\platformioTest6 will be used for project.
You can specify another project directory via
`platformio init -d %PATH_TO_THE_PROJECT_DIR%` command.

The next files/directories have been created in d:\Program\igor\arduino\platformioTest6
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
Error: Traceback (most recent call last):
  File "d:\install\programming\python\python2.7\lib\site-packages\platformio\__main__.py", line 104, in main
    cli(None, None, None)
  File "d:\install\programming\python\python2.7\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "d:\install\programming\python\python2.7\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "d:\install\programming\python\python2.7\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\install\programming\python\python2.7\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\install\programming\python\python2.7\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "d:\install\programming\python\python2.7\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\install\programming\python\python2.7\lib\site-packages\platformio\commands\init.py", line 103, in cli
    pg.generate()
  File "d:\install\programming\python\python2.7\lib\site-packages\platformio\ide\projectgenerator.py", line 121, in generate
    self._render_tpl(tpl_path).encode("utf8"))
  File "d:\install\programming\python\python2.7\lib\site-packages\platformio\ide\projectgenerator.py", line 127, in _render_tpl
    return bottle.template(content, **self._tplvars)
  File "d:\install\programming\python\python2.7\lib\site-packages\bottle.py", line 3619, in template
    return TEMPLATES[tplid].render(kwargs)
  File "d:\install\programming\python\python2.7\lib\site-packages\bottle.py", line 3409, in render
    self.execute(stdout, env)
  File "d:\install\programming\python\python2.7\lib\site-packages\bottle.py", line 3396, in execute
    eval(self.co, env)
  File "<string>", line 15, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 9: ordinal not in range(128)

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

#### Steps to Reproduce

1. http://docs.platformio.org/en/latest/installation.html
2. http://docs.platformio.org/en/latest/ide/clion.html

### Additional info
1.-------------------------------------------------------------------------------------------------
d:\Program\igor\arduino\platformioTest6>pio home
Usage: pio [OPTIONS] COMMAND [ARGS]...

Error: No such command "home"

d:\Program\igor\arduino\platformioTest6>platformio platforms list
*******************************************************************************************************************************************************************************************************
Obsolete PIO Core v3.4.1 is used (previous was 3.5.0a16)
Please remove multiple PIO Cores from a system:
http://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system
*******************************************************************************************************************************************************************************************************
atmelavr ~ Atmel AVR
====================
Atmel AVR 8- and 32-bit MCUs deliver a unique combination of performance, power efficiency and design flexibility. Optimized to speed time to market-and easily adapt to new ones-they are based on the
industrys most code-efficient architecture for C and assembly programming.

Home: http://platformio.org/platforms/atmelavr
Frameworks: arduino, simba
Packages: toolchain-atmelavr, framework-arduinoavr, framework-simba, tool-avrdude, tool-micronucleus
Version: 1.7.1

2.-------------------------------------------------------------------------------------------------
d:\Program\igor\arduino\platformioTest6>platformio run -t idedata
*******************************************************************************************************************************************************************************************************
Obsolete PIO Core v3.4.1 is used (previous was 3.5.0a16)
Please remove multiple PIO Cores from a system:
http://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system
*******************************************************************************************************************************************************************************************************
[09/30/17 23:19:13] Processing uno (platform: atmelavr; board: uno; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Collected 24 compatible libraries
Looking for dependencies...
Project does not have dependencies

{"cxx_path": "C:\\.platformio\\packages\\toolchain-atmelavr\\bin\\avr-g++.exe", "cc_flags": "-std=gnu11 -fno-fat-lto-objects -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DF
_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619", "prog_path": "d:\\Program\\igor\\arduino\\platformioTest6\\.pioenvs\\uno\\firmware.elf", "gdb_path": "C:\\.plat
formio\\packages\\toolchain-atmelavr\\bin\\avr-gdb.exe", "cxx_flags": "-fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -g -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=at
mega328p -DF_CPU=16000000L -DPLATFORMIO=30401 -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -DARDUINO=10619", "includes": ["C:\\.platformio\\packages\\framework-arduinoavr\\cores\\arduino", "C:\\.platformio\\p
ackages\\framework-arduinoavr\\variants\\standard", "d:\\Program\\igor\\arduino\\platformioTest6\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\__cores__\\arduino\\EEPROM\\src", "
C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\__cores__\\arduino\\HID\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\__cores__\\arduino\\SPI\\src", "C:\\.platformio\
\packages\\framework-arduinoavr\\libraries\\__cores__\\arduino\\SoftwareSerial\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\__cores__\\arduino\\Wire\\src", "C:\\.platformio\\pac
kages\\framework-arduinoavr\\libraries\\Adafruit_CircuitPlayground", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\Adafruit_CircuitPlayground\\utility", "C:\\.platformio\\packages\\fram
ework-arduinoavr\\libraries\\Bridge\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\Esplora\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\Ethernet\\src", "C:\
\.platformio\\packages\\framework-arduinoavr\\libraries\\Firmata", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\Firmata\\utility", "C:\\.platformio\\packages\\framework-arduinoavr\\lib
raries\\GSM\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\Keyboard\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\LiquidCrystal\\src", "C:\\.platformio\\pack
ages\\framework-arduinoavr\\libraries\\Mouse\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\RobotIRremote\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\Robot
_Control\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\Robot_Motor\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\SD\\src", "C:\\.platformio\\packages\\frame
work-arduinoavr\\libraries\\Servo\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\SpacebrewYun\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\Stepper\\src", "C
:\\.platformio\\packages\\framework-arduinoavr\\libraries\\TFT\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\Temboo\\src", "C:\\.platformio\\packages\\framework-arduinoavr\\libra
ries\\WiFi\\src", "C:\\.platformio\\packages\\toolchain-atmelavr\\avr\\include", "C:\\.platformio\\packages\\toolchain-atmelavr\\lib\\gcc\\avr\\4.9.2\\include", "C:\\.platformio\\packages\\toolchain-a
tmelavr\\lib\\gcc\\avr\\4.9.2\\include-fixed", "C:\\.platformio\\packages\\tool-unity"], "libsource_dirs": ["d:\\Program\\igor\\arduino\\platformioTest6\\lib", "d:\\Program\\igor\\arduino\\platformioT
est6\\.piolibdeps", "C:\\.platformio\\lib", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries\\__cores__\\arduino", "C:\\.platformio\\packages\\framework-arduinoavr\\libraries"], "cc_path":
"C:\\.platformio\\packages\\toolchain-atmelavr\\bin\\avr-gcc.exe", "defines": ["F_CPU=16000000L", "PLATFORMIO=30401", "ARDUINO_ARCH_AVR", "ARDUINO_AVR_UNO", "ARDUINO=10619", "__AVR_ATmega328P__"]}

===================================================================================== [SUCCESS] Took 0.76 seconds =====================================================================================

3.-------------------------------------------------------------------------------------------------
d:\Program\igor\arduino\platformioTest6>python --version
Python 2.7.14
4.-------------------------------------------------------------------------------------------------
d:\Program\igor\arduino\platformioTest6>pio --version
PlatformIO, version 3.4.1

**Comment by ivankravets** [comment] 2017-10-02 09:25
Duplicate of https://github.com/platformio/platformio-core/issues/952

**Closed by ivankravets** 2017-10-02 09:25 UTC
