### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by PCM1945** [platformio/platformio-core#1647] opened 2018-05-31 21:56 UTC
PIO Core Call Error: Platform /home/pedro/.platformio/platforms/ststm32@src-15e0e87f41a00aa2f9602f71367ac29c
--------
Updating ststm32                         @ 57bd156        [be162a1]
git version 2.7.4

fatal: Not a git repository: /home/pedro/.platformio/platforms/_tmp_installing-fj4Uqb-package/.git/modules/builder/frameworks/libopencm3
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment] 2018-06-01 15:09
Duplicate of https://github.com/platformio/platformio-core/issues/1223

**Closed by ivankravets** 2018-06-01 15:09 UTC
Labels: duplicate
