### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by greg-wood** [platformio/platformio-core#2827] opened 2019-07-24 05:55 UTC
PIO Core Call Error: "The current working directory /Users/greg/Documents/PlatformIO/Projects/Keyboard2 will be used for the project.\n\nThe next files/directories have been created in /Users/greg/Documents/PlatformIO/Projects/Keyboard2\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Could not install 'framework-esp8266-rtos-sdk' with version requirements '>=1.5.0-beta' for your system 'darwin_x86_64'.\n\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment] 2019-07-27 08:37
Duplicate of https://github.com/platformio/platformio-core/issues/2826

**Closed by ivankravets** 2019-07-27 08:37 UTC
