### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by pavellzubkov** [platformio/platformio-core#1956] opened 2018-12-05 07:15 UTC
PIO Core Call Error: "<Exception instance at 0x7359ec8 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 57-61: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2018-12-12 13:56
Duplicate of https://github.com/platformio/platformio-core/issues/1955

**Closed by ivankravets** 2018-12-12 13:56 UTC
