### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by OmarAlkassab** [platformio/platformio-core#2343] opened 2019-04-19 11:45 UTC
When I search for a library it shows thise error message:

Server error: {"message":"No module named _dumbwin32proc","args":["No module named _dumbwin32proc"],"type":"ImportError"}

**Comment by ivankravets** [comment] 2019-04-19 12:42
Duplicate of https://github.com/platformio/platformio-core/issues/1997#issuecomment-452685135

**Closed by ivankravets** 2019-04-19 12:42 UTC
