### ISSUE TITLE
Download speeds suck in China. Here are some solutions.

### ISSUE THREAD

**Issue by CyberFoxHax** [platformio/platformio-core#4656] opened 2023-06-11 04:59 UTC
https://community.platformio.org/t/platformio-packages-download-slowly/26490

issue https://github.com/platformio/platformio-core/issues/3835

reading these threads left me slightly miffed providing no solutions other than "got a new a new shiny mirror" (that's dead)

some brief information, I'm on Windows 10. I just downloaded the latest VSCode (1.79.0) and PlatformIO (6.1.7) and doing a fresh installation 8 hours in, there have been a lot of muttering and swearing.

It IS possible to install packages manually using `pio pkg -t [path to tar.gz]` the only problem is getting said package. there are no download urls to be found anywhere. I had to dig into the source code to discover the `registry.platformio.org/api/v3/*` endpoints. I that's my url! Now download with my browser at 10mb/s. 3 hours is now 30 seconds!
I'm not going into the details of how i pieced together the url, because i have a much easier way.

Find your package on registry.platformio.org, open the web inspector, navigate to the network tab and find the xhr request with the package name. Within this payload lies the url for all versions

Of course all this was all useless, because platformio insisted downloading the packages again (some of them, not all, but we're still talking ~3 hours)

Now i'm back to investigating proxies.

Normally in China we do not rely solely on fast mirrors, they exist, but are somewhat... temporary.

some people have Virtual Network Interface VPN's that is "ExpressVPN" (which i don't use, cause it sucks), the fastest "VPN" i have seen is Shadowsocks/V2Ray or Clash, these are called "web proxies" that run on localhost, not a full blown Virtual Adapter.
It's "common" knowledge for Chinese Python devs that you need to set HTTP_PROXY and HTTPS_PROXY to get any kind of work done.

So i followed the guide https://docs.platformio.org/en/latest/core/installation/proxy-configuration.html but unfortunately it didn't work. (the variable syntax is also wrong but i digress) PIO still wont use the proxy, yes i'm sure, cause i killed my proxy, and it continued on at 10kb/s as if nothing happened. I tried system variables, i tried `set` and `setx`, nothing worked. At last. I tried everything again, but in cmd.exe. That worked!
So VSCode is using Powershell as the default shell. Why is Env variables doesn't work? I don't know.

All of this is of course just for PlatformIO CLI. The GUI, i can't figure out how to get that to use the proxy

A few tiny things that could make this much less infuriating.
1. Provide a "verbose" mode for "pio pkg" that actually prints out the full address of the files being downloaded. 
2. Put actual download links on registry.platformio.org instead of the "please use the platformio tools, it's a much better experience"
3. Since Powershell is the default shell in vscode. Figure out why Pio pkg can't read the environment variables. Or print a warning.

EDIT:
setting proxy for VSCode seems to fix the GUI part
https://docs.mend.io/en-US/bundle/wsk/page/how_to_set_up_proxy_settings_for_advise_for_visual_studio_code.html

**Comment by ivankravets** [comment] 2023-06-11 09:52
> I tried system variables, i tried set and setx, nothing worked. 

Why should it work? You set environment variable in your temporary terminal session. The VSCode works from the separated isolated process. You need to set the environment variables to global scope https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html

> "got a new a new shiny mirror" (that's dead)

Duplicate of https://github.com/platformio/platformio-core/issues/4345 . Let's move to that issue.

**Closed by ivankravets** 2023-06-11 09:52 UTC

**Comment by acmcee** [comment] 2023-08-27 05:47
thanks，i can download platformio package successfully!

**Comment by dennisdebel** [comment] 2025-11-02 09:34
Having daily issues with platformio...it works for 10 hours and then you are stuck for two days....no matter proxy settings etc. As OP said, there is no feedback anywhere, not even in the inspector. What to do :(

**Comment by dennisdebel** [comment] 2025-12-25 09:42
Still having the same issue...how to change the sources???? Platformio ignores VPN conf...

**Comment by dennisdebel** [comment] 2026-01-02 12:30
Still...every week or so it just takes +12 hours to simply dl espressif framework losing days of work in a month...how are people in China getting anything done?

**Comment by ivankravets** [comment] 2026-01-02 14:35
Using a VPN while you are in mainland China does not make sense in this case. The PlatformIO's CDN includes nodes that are directly connected to the China Telecom CN2 high-speed network. We serve dozens of terabytes of traffic per day, and there have been no incidents reported from mainland China.

Could you please try downloading the package without using a VPN?

**Comment by CyberFoxHax** [comment] 2026-01-30 03:57
@dennisdebel I'm still using PlatformIO to this day and I have a workaround that should at least get you going a little.

1. Open the PlatformIO tab in VSCode and find the "PlatformIO Core CLI"
2. input "cmd" (to get out of powershell)
3. input "set HTTPS_PROXY=http://127.0.0.1:1234" (remember to change to the correct port number)
4. input "pio pkg install"

this should install all dependencies through your proxy. 

(This is the solution i always use for Python, and PlatformIO is coincidentally, written in Python)

Note, you may be able to set the variable in Powershell though the syntax is different and harder to remember. `$env:HTTPS_PROXY="http://127.0.0.1"1234"`

If the built-in gui can't even update the `platformio.ini` you can opt to add the package manually to the .ini, or in the `pio pkg install` command. (assuming you can figure what the package identifier is...)
