### ISSUE TITLE
Output from custom target *very* slow to appear in the terminal

### ISSUE THREAD

**Issue by adbancroft** [platformio/platformio-core#3965] opened 2021-06-06 11:50 UTC
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Goal 
Add a custom target that launches a simulator: simavr in my case.

### Configuration

**Operating system**: Window 10 64 bit Version 1909

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 5.2.0a6

### Description of problem

Simulator output is incredibly slow to echo in the terminal: up to the point it looks like nothing is happening. If I wait long enough (minutes) it eventually appears. 

Running simavr on it's own produces output line by line.

#### Steps to Reproduce

1. Setup a project using the ini, cpp & python script below.
2. Build
3. Launch the 'Simulate' custom target. E.g. `pio run -t Simulate`

### Actual Results

Simulator output doesn't appear in the terminal

### Expected Results

Simulator output (to stdout & stderr) is echoed in the terminal as soon as the child simavr process prints to stdout/stderr.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
extra_scripts = simavr_env.py
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>

int counter = 0;

void setup() {
  Serial.begin(9600);
  Serial.println("TESTING");
}

void loop() {
  if (counter % 10 == 0) {
    Serial.println(counter); 
  } else {
    Serial.print(counter); Serial.print("-");
  }
  counter++;
  delay(100);
}
```

### Additional info

* [Custom python script](https://github.com/ridiculousfish/libdivide/blob/master/test/avr/simavr_env.py)
* [slow-output-from-custom-target.zip](https://github.com/platformio/platformio-core/files/7406185/slow-output-from-custom-target.zip)

**Comment by valeros** [comment] 2021-09-24 14:40
Hi @adbancroft ! It seems your extra script is no longer available. Could you please upload it somewhere so I can reproduce the issue?

**Comment by adbancroft** [comment] 2021-09-24 23:28
@valeros Original link updated.

Also here: https://github.com/ridiculousfish/libdivide/blob/master/test/avr/simavr_env.py

**Comment by ivankravets** [comment] 2022-05-04 19:11
Duplicate of https://github.com/buserror/simavr/issues/489

**Closed by ivankravets** 2022-05-04 19:11 UTC
Labels: help wanted, debugging
