### ISSUE TITLE
Home: Could not uninstall platform

### ISSUE THREAD

**Issue by cloeffler** [platformio/platformio-core#1708] opened 2018-06-26 16:35 UTC
PIO Core Call Error: Error: Unknown development platform 'C:\Users\cloeffler\.platformio\platforms\espressif8266@1.6.0'

**Comment by ivankravets** [comment] 2018-07-03 12:01
Duplicate of https://github.com/platformio/platformio-core/issues/1346

**Closed by ivankravets** 2018-07-03 12:01 UTC
