### ISSUE TITLE
Feature Request: Support RealTek Ameba AMB82-Mini board (RTL8735BDM)

### ISSUE THREAD

**Issue by Kela910512** [platformio/platformio-core#4855] opened 2024-02-05 15:57 UTC
PlatformIO Version: PlatformIO Core, version 6.1.13

### Description of problem

Please support RealTek Ameba AMB82-Mini board (RTL8735BDM) in Platformio boards.

- MCU: ARMv8M up to 500MHz
- Chip: RTL8735BDM

Product: [Realtek AMB82-Mini](https://www.seeedstudio.com/AMB82-MINI-RTL8735B-IoT-AI-Camera-Dev-Board-p-5584.html)

### Note
All such requests are directed to [#769](https://github.com/platformio/platformio-core/issues/769) and are marked as duplicates, but this is incorrect.
In request [#769](https://github.com/platformio/platformio-core/issues/769), RTL8720 / RTL8710 / RTL8711 / RTL8195 are listed.
The AMB82 MINI is RTL8735BDM.

**Comment by ivankravets** [comment] 2024-02-07 11:39
Duplicate of https://github.com/platformio/platformio-core/issues/769


It covers all MCUs.

**Closed by ivankravets** 2024-02-07 11:39 UTC
