### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by DJManas** [platformio/platformio-core#2760] opened 2019-07-07 17:56 UTC
PIO Core Call Error: "No JSON object could be decoded“

Tried to login to my account.

VSCode 1.36.0 (1.36.0)
PIO: PlatformIO 4.0.0rc4 is currently the newest version available.

**Comment by ivankravets** [comment] 2019-07-09 21:21
Duplicate of https://github.com/platformio/platformio-core/issues/2748

**Closed by ivankravets** 2019-07-09 21:21 UTC
