### ISSUE TITLE
Home: Internal Store Exception

### ISSUE THREAD

**Issue by EAmgarten** [platformio/platformio-core#1136] opened 2017-10-23 10:53 UTC
TypeError: Cannot read property 'filter' of null
    at t.value (http://127.0.0.1:8010/8a915bf8c2b0eb535301.min.js:25:87698)
    at http://127.0.0.1:8010/8a915bf8c2b0eb535301.min.js:25:87384
    at Array.map (native)
    at t.value (http://127.0.0.1:8010/8a915bf8c2b0eb535301.min.js:25:87239)
    at t.value (http://127.0.0.1:8010/8a915bf8c2b0eb535301.min.js:25:85311)
    at d._renderValidatedComponentWithoutOwnerOrContext (http://127.0.0.1:8010/8a915bf8c2b0eb535301.min.js:25:479053)
    at d._renderValidatedComponent (http://127.0.0.1:8010/8a915bf8c2b0eb535301.min.js:25:479180)
    at d._updateRenderedComponent (http://127.0.0.1:8010/8a915bf8c2b0eb535301.min.js:25:478484)
    at d._performComponentUpdate (http://127.0.0.1:8010/8a915bf8c2b0eb535301.min.js:25:478285)
    at d.updateComponent (http://127.0.0.1:8010/8a915bf8c2b0eb535301.min.js:25:477563)

**Comment by ivankravets** [comment] 2017-11-02 18:56
Duplicate of https://github.com/platformio/platformio-core/issues/1062

**Closed by ivankravets** 2017-11-02 18:56 UTC
