### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by SkuterGaming** [platformio/platformio-core#2486] opened 2019-05-12 13:46 UTC
PIO Core Call Error: "<Exception instance at 0x5af9708 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u0142' in position 31: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-05-23 18:33
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Closed by ivankravets** 2019-05-23 18:33 UTC
