### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by sanketbphc89** [platformio/platformio-core#1662] opened 2018-06-06 06:48 UTC
PIO Core Call Error: The next files/directories have been created in /home/iotsys1/Documents/PlatformIO/Projects/raspbeB
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
PlatformManager: Installing linux_arm
Downloading
Downloading
Unpacking
Unpacking
linux_arm @ 1.4.6 has been successfully installed!
PackageManager: Installing toolchain-gccarmlinuxgnueabi @ ~1.40802.0

Error: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'linux_x86_64'

**Comment by ivankravets** [comment] 2018-06-07 22:09
Duplicate of https://github.com/platformio/platform-linux_arm/issues/2

**Closed by ivankravets** 2018-06-07 22:09 UTC
