### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by MickyPf** [platformio/platformio-core#2771] opened 2019-07-09 20:53 UTC
PIO Core Call Error: "CorePackageManager: Installing tool-pioplus @ ^2.5.2\ntool-pioplus @ 2.5.2 has been successfully installed!"

**Comment by ivankravets** [comment] 2019-07-09 21:21
Duplicate of https://github.com/platformio/platformio-core/issues/2748

**Closed by ivankravets** 2019-07-09 21:21 UTC
