### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by Pictout** [platformio/platformio-core#2451] opened 2019-05-04 19:43 UTC
PIO Core Call Error: "Library Storage: /home/francis/.platformio/lib\nUpdating ESPManager                      @ 2.0.3          [2.0.4]\nUninstalling ESPManager @ 2.0.3: \t[OK]\nLooking for ESPManager library in registry\nESPManager\n==========\n#ID: 1480\nWiFi and OTA manager for ESP8266\n\nKeywords: uncategorized\nCompatible frameworks: Arduino\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, Intel ARC32, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, Teensy, TI MSP430\nAuthors: Andrew Melvin\n\nESPManager\n==========\n#ID: 5958\nESP manager\n\nKeywords: device, control\nCompatible frameworks: Arduino\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, Intel ARC32, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, ST STM8, Teensy, TI MSP430\nAuthors: Sergiu Toporjinschi\n\nFound: https://platformio.org/lib/show/1480/ESPManager\nLibraryManager: Installing id=1480 @ 2.0.4\n\nConflict: More than one library has been found by request {\"requirements\": \"2.0.4\", \"name\": \"ESPManager\"}:\nAutomatically chose the first available library (use `--interactive` option to make a choice)\nError: Could not find a version that satisfies the requirement '2.0.4' for your system 'linux_x86_64'"

**Comment by ivankravets** [comment] 2019-05-06 15:37
Duplicate of https://github.com/platformio/platformio-core/issues/2065

Try to uninstall ESPManager and install it again.

**Closed by ivankravets** 2019-05-06 15:37 UTC
