### ISSUE TITLE
IndustrialShields Boards with PlatformIO

### ISSUE THREAD

**Issue by Ottega** [platformio/platformio-core#4404] opened 2022-08-30 12:15 UTC
What kind of issue is this?
- [x] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.
------------------------------------------------------------------

### Configuration

**Operating system**:
Fedora 36
**PlatformIO Version** (`platformio --version`):
PlatformIO Core, version 6.1.4
### Description of problem

I'd like to use IndustrialShields Boards with PlatformIO, but they are not supported yet.

#### Steps to Reproduce

1. Try to install the board: industrialshields
2.  Try to install the board: industrialshields-esp32
3. Try to install the board: industrialshields-megaavr

#### Additional Information

The board information can be found [here](http://apps.industrialshields.com/main/arduino/boards/package_industrialshields_index.json).

**Comment by ivankravets** [comment] 2022-09-03 09:15
Duplicate of https://github.com/platformio/platformio-core/issues/3935

**Closed by ivankravets** 2022-09-03 09:15 UTC
