### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by ejronin** [platformio/platformio-core#2974] opened 2019-09-03 19:18 UTC
PIO Core Call Error: "Library Storage: C:\\Users\\shawn\\.platformio\\lib\r\nLooking for Ds1307 library in registry\r\nDS1307\r\n======\r\n#ID: 145\r\nDS1307 RTC (Real-Time-Clock)\r\n\r\nKeywords: i2c, rtc, time, clock\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR\r\nAuthors: Watterott electronic\r\n\r\nDs1307\r\n======\r\n#ID: 1926\r\nA C/C++ library to use DS1307 RTC chip.\r\n\r\nKeywords: library, c, c++, rtc, ds1307, clock, date, time, datetime\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR, Espressif 32, Espressif 8266\r\nAuthors: Rafa Couto\r\n\r\nDS1307\r\n======\r\n#ID: 2270\r\nThis is a class for using the DS1307 Real Time Clock chip from Dallas Semiconductor. This class uses mbeds i2c class to talk to the chip. I have tested this ...\r\n\r\nKeywords: clock, ds1307, i2c, rtc\r\nCompatible frameworks: mbed\r\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\r\nAuthors: Philip Smith\r\n\r\nDS1307\r\n======\r\n#ID: 2269\r\nDallas DS1307 real-time clock minimalistic driver\r\n\r\nKeywords: clock, ds1307, rtc\r\nCompatible frameworks: mbed\r\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\r\nAuthors: Ales Povalac\r\n\r\nDS1307\r\n======\r\n#ID: 3467\r\nDS1307\r\n\r\nKeywords: ds1307\r\nCompatible frameworks: mbed\r\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\r\nAuthors: Chindanai Mala-eiam\r\n\r\nDS1307\r\n======\r\n#ID: 3469\r\nLibreria para trabajar con DS1307 y usar su memoria\r\n\r\nKeywords: ds1307\r\nCompatible frameworks: mbed\r\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\r\nAuthors: Angel David Yaguana Hernandez\r\n\r\nFound: https://platformio.org/lib/show/145/DS1307\r\nLibraryManager: Installing id=145 @ ^1.0.2\r\n\n\nConflict: More than one library has been found by request {\"name\": \"Ds1307\", \"requirements\": \"^1.0.2\"}:\r\nAutomatically chose the first available library (use `--interactive` option to make a choice)\r\nError: Could not find a version that satisfies the requirement '^1.0.2' for your system 'windows_amd64'"

**Comment by ivankravets** [comment] 2019-09-04 12:47
Duplicate of https://github.com/platformio/platformio-core/issues/2954

**Closed by ivankravets** 2019-09-04 12:47 UTC
