### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by xixxi** [platformio/platformio-core#2127] opened 2019-02-12 21:22 UTC
PIO Core Call Error: "Library Storage: C:\\Users\\denisov\\.platformio\\lib\r\nUpdating GUIslice                        @ 0c4e3a3        [6a4e2f3]\r\ngit version 2.20.1.windows.1\nUpdating 0c4e3a3..6a4e2f3\n\nFrom https://github.com/ImpulseAdventure/GUIslice\n   0c4e3a3..6a4e2f3  master     -> origin/master\nerror: Your local changes to the following files would be overwritten by merge:\n\tconfigs/ard-adagfx-st7735-notouch.h\n\tsrc/GUIslice_config.h\nPlease commit your changes or stash them before you merge.\nAborting\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment] 2019-02-23 16:30
Duplicate of https://github.com/platformio/platformio-core/issues/2138

**Closed by ivankravets** 2019-02-23 16:30 UTC
