### ISSUE TITLE
Unit tests results not showing

### ISSUE THREAD

**Issue by cccadel** [platformio/platformio-core#3886] opened 2021-03-17 13:38 UTC
Due to this line the results of my Unit Tests aren't showing using the `pio test` command. After running this command, the result is stuck on `If you don't see any output for the first 10 secs, please reset board (press reset button)`. I'm using the Arduino MKR GSM 1400 and the solution for now is to manually open a serial monitor after running `pio test` and see the results of the Unit Tests there.
 
https://github.com/platformio/platformio-core/blob/61db0f1d6a89a621281b12e1a913635905d0e035/platformio/commands/test/embedded.py#L67

**Comment by ivankravets** [comment] 2021-03-17 15:05
Could it be linked with https://github.com/platformio/platformio-core/issues/3742?

**Comment by ivankravets** [comment] 2021-03-24 11:06
Duplicate of https://github.com/platformio/platformio-core/issues/3742

**Closed by ivankravets** 2021-03-24 11:06 UTC
Labels: help wanted, unit testing
