### ISSUE TITLE
Support Arduino Micro Debugging

### ISSUE THREAD

**Issue by pepsipu** [platformio/platformio-core#3023] opened 2019-09-16 00:36 UTC
Hi! I'd suggest adding support for the debugging of Arduino Micro. It's microprocessor is the ATmega32U4, which I'd assume you guys have added support for. It shouldn't be too hard to implement. Thanks!

**Comment by ivankravets** [comment] 2019-10-02 09:04
Duplicate of https://github.com/platformio/platform-atmelavr/issues/95

**Closed by ivankravets** 2019-10-02 09:04 UTC
