### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by BXODA** [platformio/platformio-core#2537] opened 2019-05-22 23:14 UTC
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\56808\\Documents\\PlatformIO\\Projects\\190522-220758-stm32cube-hal-blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: You are not connected to the Internet.\r\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains."

**Comment by ivankravets** [comment] 2019-05-23 21:20
Duplicate of https://github.com/platformio/platformio-core/issues/2088

**Closed by ivankravets** 2019-05-23 21:20 UTC
