### ISSUE TITLE
Installing Artik platform on Mac os fails in VSCode IDE

### ISSUE THREAD

**Issue by ratmandu** [platformio/platformio-core#1614] opened 2018-05-08 18:45 UTC
Setting up a project for the Artik 710 on MacOS 10.12.6 fails with the following

PIO Core Call Error: The next files/directories have been created in /Users/ratmandu/Documents/PlatformIO/Projects/Artik7Test
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
PlatformManager: Installing linux_arm
Downloading
Downloading
Unpacking
Unpacking
linux_arm @ 1.4.6 has been successfully installed!
PackageManager: Installing toolchain-gccarmlinuxgnueabi @ ~1.40802.0
Downloading
Downloading
Unpacking
Unpacking
toolchain-gccarmlinuxgnueabi @ 1.40802.0 has been successfully installed!
The platform 'linux_arm' has been successfully installed!
The rest of packages will be installed automatically depending on your build environment.

Error: Could not find a version that satisfies the requirement '*' for your system 'darwin_x86_64'

**Comment by ivankravets** [comment] 2018-05-08 22:12
Duplicate of https://github.com/platformio/platform-linux_arm/issues/2

**Closed by ivankravets** 2018-05-08 22:12 UTC
