### ISSUE TITLE
Include manually installed projects in /lib folder when discovering library dependencies

### ISSUE THREAD

**Issue by Bascy** [platformio/platformio-core#3871] opened 2021-03-04 21:25 UTC
**Feature request**
I want to use my own private libraries as git submodules in a platformio project.
I clone the submodules in the /lib folder so they are automatically accessible from my project source files. That works great.

The problem is that my private libraries have dependencies specified in a library.json file that are now not automatically installed if not already present.

It would be perfect if the library dependency finder process would include the /lib folder in its search for `library.json` files specifying dependencies and also when determining if a needed  library is already present.

Alternatively a special subfolder (i.e. `submodules`) could be created and via a setting in platformio indicated as being a folder with git repo libraries

**Comment by ivankravets** [comment] 2021-03-05 17:52
Thanks for the FR! 

Duplicate of https://github.com/platformio/platformio-core/issues/2573

**Closed by ivankravets** 2021-03-05 17:52 UTC
