### ISSUE TITLE
Home: Could not uninstall platform

### ISSUE THREAD

**Issue by ladidadida** [platformio/platformio-core#1405] opened 2018-02-27 19:10 UTC
PIO Core Call Error: Error: Unknown development platform '/home/stefan/.platformio/platforms/linux_arm@src-70ce52bd401973cf992ddca908e821b6'

**Comment by ivankravets** [comment] 2018-03-06 10:10
Duplicate of https://github.com/platformio/platformio-core/issues/1282

**Closed by ivankravets** 2018-03-06 10:10 UTC
