### ISSUE TITLE
Support of mbed framework to STM32F103RE

### ISSUE THREAD

**Issue by harimambura** [platformio/platformio-core#1948] opened 2018-11-29 22:25 UTC
The STM32F103RE is the 512K flash version of the STM32F103C8 chip. So if the board genericSTM32F103C8 supports mbed, the RE version with just the bigger flash should be supported too, i think. here the additional description of this board https://stm32-base.org/boards/STM32F103RET6-Generic-Board

**Comment by ivankravets** [comment] 2018-11-29 23:37
Duplicate of https://github.com/platformio/platform-ststm32/issues/98

**Closed by ivankravets** 2018-11-29 23:37 UTC
