### ISSUE TITLE
Home: Could not list directory/private/var/folders/cm/87164lm91_517vp5t0w6lvn00000gn/T/AppTranslocation/DBFAE66A-2C46-40A2-A2ED-4EADB6131CCA

### ISSUE THREAD

**Issue by aramperez** [platformio/platformio-core#2344] opened 2019-04-19 14:32 UTC
Server error: {"message":"[Errno 34] Result too large: '/private/var/folders/cm/87164lm91_517vp5t0w6lvn00000gn/T/AppTranslocation/DBFAE66A-2C46-40A2-A2ED-4EADB6131CCA'","args":[34,"Result too large"],"type":"OSError"}

**Comment by ivankravets** [comment] 2019-04-20 08:43
Duplicate of https://github.com/platformio/platformio-core/issues/2085

**Closed by ivankravets** 2019-04-20 08:43 UTC
