### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by yjyFlashing** [platformio/platformio-core#2111] opened 2019-02-09 15:12 UTC
PIO Core Call Error: "<Exception instance at 0x627a448 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 56-58: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-02-23 15:01
Duplicate of https://github.com/platformio/platformio-core/issues/2078

**Closed by ivankravets** 2019-02-23 15:01 UTC
