### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by nkimlevn** [platformio/platformio-core#2266] opened 2019-03-30 04:48 UTC
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\nkiml\\Documents\\PlatformIO\\Projects\\Stm8S\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing stm8sdisco (platform: ststm8; board: stm8sdisco; framework: spl)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm8/stm8sdisco.html\r\nPLATFORM: ST STM8 > ST STM8S-DISCOVERY\r\nHARDWARE: STM8S105C6T6 16MHz 2KB RAM (32KB Flash)\r\nDEBUG: CURRENT(stlink) ON-BOARD(stlink)\r\nError: Could not parse library files for the target.\r\nstm8s.h:2723:25: fatal error: stm8s_conf.h: No such file or directory\r\n\r\n********************************************************************\r\n* Looking for stm8s_conf.h dependency? Check our library registry!\r\n*\r\n* CLI  > platformio lib search \"header:stm8s_conf.h\"\r\n* Web  > https://platformio.org/lib/search?query=header:stm8s_conf.h\r\n*\r\n********************************************************************\r\n\r\ncompilation terminated.\r\n [ERROR] Took 0.91 seconds"

**Comment by ivankravets** [comment] 2019-03-30 16:58
Duplicate of https://github.com/platformio/platform-ststm8/issues/6

**Closed by ivankravets** 2019-03-30 16:58 UTC
