### ISSUE TITLE
bl618 bl616 arduino

### ISSUE THREAD

**Issue by longgeligelong** [platformio/platformio-core#4936] opened 2024-06-14 04:45 UTC
Need to add bl616 and bl618 development board support
This existing Arduino framework is as follows
https://github.com/strongwong/arduino-bl618

**Comment by ivankravets** [comment] 2024-07-06 17:10
Duplicate of https://github.com/platformio/platformio-core/issues/4046 

Please vote (👍 ) for that issue.

**Closed by ivankravets** 2024-07-06 17:10 UTC
