### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by sushantdasputepatil** [platformio/platformio-core#3252] opened 2019-11-06 07:27 UTC
PIO Core Call Error: "Library Storage: /home/sushantdasputepatil/.platformio/lib\nUpdating SD                              @ 1.2.3          [1.2.4]\nUninstalling SD @ 1.2.3: \t[OK]\nLooking for SD library in registry\nSD\n==\n#ID: 161\nThis library aims to expose a subset of SD card functionality in the form of a higher level 'wrapper' object\n\nKeywords: sd, card, file, system\nCompatible frameworks: Arduino\nCompatible platforms: Atmel AVR\nAuthors: Adafruit Industries\n\nSD\n==\n#ID: 868\nEnables reading and writing on SD cards.\n\nKeywords: storage, data\nCompatible frameworks: Arduino\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, GigaDevice GD32V, Infineon XMC, Intel ARC32, Kendryte K210, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, ST STM8, Teensy, TI MSP430\nAuthors: Arduino, SparkFun\n\nSD\n==\n#ID: 79\nThis library aims to expose a subset of SD card functionality in the form of a higher level 'wrapper' object (adaptation for LaunchPad LM4F120 / TM4C123)\n\nKeywords: sd, card, file, system\nCompatible frameworks: Energia\nCompatible platforms: TI MSP430, TI TIVA\nAuthors: Rei Vilo, William Greiman, SparkFun Electronics\n\nSD\n==\n#ID: 5210\nSD\n\nKeywords: sd\nCompatible frameworks: mbed\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\nAuthors: Jackson Lv\n\nFound: https://platformio.org/lib/show/161/SD\nLibraryManager: Installing id=161 @ 1.2.4\n\n\nConflict: More than one library has been found by request {\"name\": \"SD\", \"requirements\": \"1.2.4\"}:\nAutomatically chose the first available library (use `--interactive` option to make a choice)\nError: Could not find a version that satisfies the requirement '1.2.4' for your system 'linux_x86_64'"

**Comment by ivankravets** [comment] 2019-11-06 11:01
Duplicate of https://github.com/platformio/platformio-core/issues/3149

**Closed by ivankravets** 2019-11-06 11:01 UTC
