### ISSUE TITLE
Home: Platforms: Registry

### ISSUE THREAD

**Issue by Aspro1982** [platformio/platformio-core#1608] opened 2018-05-04 13:08 UTC
PIO Core Call Error: Error: You are not connected to the Internet.
If you build a project first time, we need Internet connection to install all dependencies and toolchain.

**Comment by ivankravets** [comment] 2018-05-08 22:17
Duplicate of https://github.com/platformio/platformio-core/issues/1408

**Closed by ivankravets** 2018-05-08 22:17 UTC
