### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by ThoreSiercks** [platformio/platformio-core#2529] opened 2019-05-21 09:32 UTC
PIO Core Call Error: "CorePackageManager: Installing tool-pioplus @ ^2.1.4\r\nWarning! Package Mirror: Got an unrecognized status code '502' when downloaded https://dl.bintray.com/platformio/dl-packages/tool-pioplus-windows_amd64-2.2.1.tar.gz\r\nLooking for another mirror...\r\nDownloading...\r\nUnpacking\r\nUnpacking\n\n[Error 5] Zugriff verweigert: 'C:\\\\Users\\\\thore\\\\.platformio\\\\packages\\\\tool-pioplus\\\\pioplus.exe' \r\nPlease manually remove the file `C:\\Users\\thore\\.platformio\\packages\\tool-pioplus\\pioplus.exe`\r\n[Error 5] Zugriff verweigert: 'C:\\\\Users\\\\thore\\\\.platformio\\\\packages\\\\tool-pioplus' \r\nPlease manually remove the file `C:\\Users\\thore\\.platformio\\packages\\tool-pioplus`\r\nError: Could not install 'tool-pioplus' with version requirements '^2.1.4' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment] 2019-05-23 16:46
Duplicate of #2473

**Closed by ivankravets** 2019-05-23 16:46 UTC
