### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by 4HomeProject** [platformio/platformio-core#2428] opened 2019-04-28 07:19 UTC
PIO Core Call Error: "Library Storage: /home/mariusz/.platformio/lib\nUpdating AESLib                          @ 1.0.4          [1.0.5]\nUninstalling AESLib @ 1.0.4: \t[OK]\nLooking for AESLib library in registry\nAESLib\n======\n#ID: 276\nSmall AES implementation in ASM\n\nKeywords: cryptography, aes\nCompatible frameworks: Arduino\nCompatible platforms: Atmel AVR\nAuthors: Davy Landman\n\nAESLib\n======\n#ID: 5533\nArduino/ESP8266 wrapper for AES library with 128-bit CBC encryption\n\nKeywords: data, processing\nCompatible frameworks: Arduino\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, Intel ARC32, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, ST STM8, Teensy, TI MSP430\nAuthors: Matej Sychra\n\nFound: https://platformio.org/lib/show/276/AESLib\nLibraryManager: Installing id=276 @ 1.0.5\n\nConflict: More than one library has been found by request {\"requirements\": \"1.0.5\", \"name\": \"AESLib\"}:\nAutomatically chose the first available library (use `--interactive` option to make a choice)\nError: Could not find a version that satisfies the requirement '1.0.5' for your system 'linux_x86_64'"

**Comment by ivankravets** [comment] 2019-05-03 10:28
Duplicate of https://github.com/platformio/platformio-core/issues/2065

**Closed by ivankravets** 2019-05-03 10:28 UTC
