### ISSUE TITLE
DOIT ESP32 Devkit V1 upload timeout in less than 1 second!

### ISSUE THREAD

**Issue by ERROPiX** [platformio/platformio-core#1880] opened 2018-10-16 21:24 UTC
Hi,

I am trying to use PlatformIO IDE in VS Code, I have already checked for updates for boards and platforms etc. all is up to date!

Uploading code to Arduino UNO works fine, but DOIT esp32 devkit doesn't work.
I was using this board in both Arduino IDE or with VS Code Arduino extension without problems.
I also tried uploading to it via the included esptool.py directly and it worked.

## PlatformIO.ini (default with no changes)
```
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
```
## Upload Task Output
```
> Executing task in folder ESP32_Blink: C:\Users\*****\.platformio\penv\Scripts\platformio.exe run --target upload <

Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Espressif 32 > DOIT ESP32 DEVKIT V1
SYSTEM: ESP32 240MHz 320KB RAM (4MB Flash)
DEBUG: CURRENT(esp-prog) EXTERNAL(esp-prog, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 24 compatible libraries
Scanning dependencies...
No dependencies
Retrieving maximum program size .pioenvs\esp32doit-devkit-v1\firmware.elf
Checking size .pioenvs\esp32doit-devkit-v1\firmware.elf
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [          ]   4.2% (used 13884 bytes from 327680 bytes)
PROGRAM: [=         ]  13.6% (used 178020 bytes from 1310720 bytes)
Configuring upload protocol...
AVAILABLE: esp-prog, esptool, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: COM5
Uploading .pioenvs\esp32doit-devkit-v1\firmware.bin
Serial port COM5
Connecting...
Traceback (most recent call last):
File "C:\Users\*****\.platformio\packages\tool-esptoolpy\esptool.py", line 2849, in <module>
_main()
File "C:\Users\*****\.platformio\packages\tool-esptoolpy\esptool.py", line 2842, in _main
main()
File "C:\Users\*****\.platformio\packages\tool-esptoolpy\esptool.py", line 2550, in main
esp.connect(args.before)
File "C:\Users\*****\.platformio\packages\tool-esptoolpy\esptool.py", line 444, in connect
last_error = self._connect_attempt(mode=mode, esp32r0_delay=False)
File "C:\Users\*****\.platformio\packages\tool-esptoolpy\esptool.py", line 424, in _connect_attempt
self.sync()
File "C:\Users\*****\.platformio\packages\tool-esptoolpy\esptool.py", line 363, in sync
timeout=SYNC_TIMEOUT)
File "C:\Users\*****\.platformio\packages\tool-esptoolpy\esptool.py", line 306, in command
self.write(pkt)
File "C:\Users\*****\.platformio\packages\tool-esptoolpy\esptool.py", line 269, in write
self._port.write(buf)
File "c:\users\*****\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 323, in write
raise writeTimeoutError
serial.serialutil.SerialTimeoutException: Write timeout
*** [upload] Error 1
====================================================== [ERROR] Took 6.53 seconds ======================================================
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

**Comment by ivankravets** [comment] 2018-10-16 21:41
Duplicate of https://github.com/platformio/platform-espressif32/issues/131

**Closed by ivankravets** 2018-10-16 21:41 UTC

**Comment by ERROPiX** [comment] 2018-10-16 21:58
@ivankravets I don't know where is the appropriate repository for it, so I post it twice
