### ISSUE TITLE
Making an environment extend itself causes `pio` to hang

### ISSUE THREAD

**Issue by oatberry** [platformio/platformio-core#4021] opened 2021-08-04 17:10 UTC
What kind of issue is this?
### Configuration

**Operating system**: Windows 10

**PlatformIO Version** : 5.1.1

### Description of problem
I accidentally made a build environment in my `platformio.ini` extend itself. This was a typo, but it caused commands like `pio run --list-targets` to silently hang until terminated by the user. 

#### Steps to Reproduce

1. Create an environment definition in `platformio.ini` that extends itself
2. Attempt any `pio` command that requires parsing environments

### Actual Results
`pio` does nothing and hangs

### Expected Results
Perhaps there could be some kind of cycle detection to help users like myself catch typos in their configs.

**Comment by ivankravets** [comment] 2021-09-13 09:48
Duplicate of https://github.com/platformio/platformio-core/issues/3883

**Closed by ivankravets** 2021-09-13 09:48 UTC
Labels: bug, duplicate, known issue, config
