### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by exothink** [platformio/platformio-core#2930] opened 2019-08-19 16:49 UTC
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"c:\\users\\jhe\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 88, in main\n    cli(None, None, None)\n  File \"c:\\users\\jhe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\jhe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\jhe\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\jhe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\jhe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\jhe\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\jhe\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py\", line 30, in cli\n    return _print_boards_json(query, installed)\n  File \"c:\\users\\j

**Comment by ivankravets** [comment] 2019-08-19 20:34
Duplicate of https://github.com/platformio/platformio-core/issues/2929

**Closed by ivankravets** 2019-08-19 20:34 UTC
