### ISSUE TITLE
Home: Libraries: Search, cannot search for libraries

### ISSUE THREAD

**Issue by Mimile-Ali** [platformio/platformio-core#3244] opened 2019-11-04 16:45 UTC
PIO Core Call Error: "Error: You are not connected to the Internet.\r\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains."

Using PlatformIO on VS and I cannot search for any libraries.

**Comment by Mimile-Ali** [comment] 2019-11-04 16:49
Also, I am connected...

**Comment by ivankravets** [comment] 2019-11-05 15:24
Duplicate of https://github.com/platformio/platformio-core/issues/1348

**Closed by ivankravets** 2019-11-05 15:24 UTC
