### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by ballinor** [platformio/platformio-core#3044] opened 2019-09-23 22:35 UTC
Server error: {"args":["ascii","File contains parsing errors: C:\\Users\\Дмитрий MSI\\Documents\\PlatformIO\\Projects\\svet\\platformio.ini\n\t[line 17]: 'DHT sensor library\\n'\n\t[line 18]: 'Adafruit Unified sensor'",39,46,"ordinal not in range(128)"],"message":"'ascii' codec can't encode characters in position 39-45: ordinal not in range(128)","type":"UnicodeEncodeError"}

**Comment by ivankravets** [comment] 2019-10-02 08:22
Duplicate of https://github.com/platformio/platformio-core/issues/2796

**Closed by ivankravets** 2019-10-02 08:22 UTC
