### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by kemaldede** [platformio/platformio-core#1409] opened 2018-02-28 16:57 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 36 column 115 (char 4 - 2335)
The library and boards menu never comes and I can't login my account

**Comment by ivankravets** [comment] 2018-03-06 10:28
Duplicate of https://github.com/platformio/platformio-core/issues/1311

**Closed by ivankravets** 2018-03-06 10:28 UTC
