### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by danibaal98** [platformio/platformio-core#2263] opened 2019-03-28 10:44 UTC
PIO Core Call Error: "<Exception instance at 0x5900848 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\Daniel\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xba' in position 64: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-03-29 18:22
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Closed by ivankravets** 2019-03-29 18:22 UTC
