### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by mogplus8** [platformio/platformio-core#1350] opened 2018-02-10 05:14 UTC
PIO Core Call Error: Error: Unknown development platform 'teensy@2.9.1'
Occurred when trying to update to teenxy 3.0.1

**Comment by ivankravets** [comment] 2018-02-14 11:51
Duplicate of https://github.com/platformio/platformio-core/issues/1346

**Closed by ivankravets** 2018-02-14 11:51 UTC
