### ISSUE TITLE
Home: Internal Store Exception on PlatformIO(Atom)

### ISSUE THREAD

**Issue by adeltc** [platformio/platformio-core#1243] opened 2017-12-16 19:22 UTC
I can't create a new arduino project. When I click on New project, the Board section is stuck searching with no results and the Framework section is emptly.

I'm using Atom on windows 10 64bit

I keep getting those errors :

TypeError: Cannot read property 'length' of null
    at _ (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:11:33158)
    at http://127.0.0.1:8010/f00d19876293fb32c015.min.js:11:33885
    at Array.map (native)
    at y (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:11:33779)
    at Function.a [as mapToProps] (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:25:403989)
    at r (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:6:10578)
    at l (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:6:11948)
    at c (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:6:12066)
    at http://127.0.0.1:8010/f00d19876293fb32c015.min.js:6:12219
    at Object.run (http://127.0.0.1:8010/f00d19876293fb32c015.min.js:6:6152)

**Comment by ivankravets** [comment] 2017-12-16 19:30
Duplicate of https://github.com/platformio/platformio-core/issues/1236

Please open PIO IDE Terminal and type `pio update`. Restart IDE.

**Closed by ivankravets** 2017-12-16 19:30 UTC

**Comment by adeltc** [comment] 2017-12-16 19:34
I just did open PIO IDE Terminal and type pio update. Restart IDE and still not working for me

**Comment by adeltc** [comment] 2017-12-16 19:36
Oups, sorry, I did not wait enouph time :) I seems to work now. Thanks!!!!

**Comment by ivankravets** [comment] 2017-12-16 19:37
Sorry for the issue, we fixed it quickly.
