### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by swapnildavangave** [platformio/platformio-core#1627] opened 2018-05-15 13:24 UTC
PIO Core Call Error: Platform /home/swapnil.davangave/.platformio/platforms/ststm32@src-15e0e87f41a00aa2f9602f71367ac29c
--------
Updating ststm32                         @ d8003b0        [57bd156]
git version 2.7.4

From https://github.com/platformio/platform-ststm32
   d8003b0..57bd156  develop    -> origin/develop
fatal: Not a git repository: /home/swapnil.davangave/.platformio/platforms/_tmp_installing-gTRUOm-package/.git/modules/builder/frameworks/libopencm3
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment] 2018-05-22 19:53
Duplicate of https://github.com/platformio/platformio-core/issues/1223

**Closed by ivankravets** 2018-05-22 19:53 UTC
