### ISSUE TITLE
Endless loop / Memory leak in cppcheck in a project that uses ArduinoJson

### ISSUE THREAD

**Issue by arduhe** [platformio/platformio-core#3578] opened 2020-07-04 18:29 UTC
- [x ] **PlatformIO Core**.

### Configuration

**Operating system**:
OpenSuse Leap 15.1

**PlatformIO Version** (`platformio --version`):
PlatformIO, version 4.3.4

### Description of problem

I've started _pio check_ from clion - a few seconds later my computer was frozen and I had to switch the power off to restart it.
Further investigations showed me that the problem is located in _pio check_ regardless how you start it. 
I've created a small project to reproduce the problem. You find it at https://github.com/arduhe/cppcheck_fault.git

#### Steps to Reproduce

1.  check out the example project
2. call _pio check_ 

### Actual Results
One core (running cppcheck) shows permanently 100% load and the process cppcheck increases memory usage until the complete available RAM and swap-space are used, unless you kill the process. Otherwise the computer freezes and it's time for a forced reboot 😉

### Expected Results
cppcheck should show the results of its checks and not freeze my PC by swallowing the whole memory

**Comment by valeros** [comment] 2020-08-25 21:41
Hi @arduhe ! We've updated the Cppcheck package to v2.1 and I'm not able to reproduce the problem, it would be great if you could retest your project with PlatformIO Core from the dev branch. Just run `pio upgrade --dev` in the terminal and you ready to go.

**Comment by arduhe** [comment] 2020-08-26 08:50
After upgrade to latest dev 
`pio --version
PlatformIO, version 5.0.0b2`

pio check terminates properly :-)

Is there a stable version containing this fix? To be honest - I am not a friend of dev versions  - aka beta - no matter from which program ;-).

**Comment by valeros** [comment] 2020-08-26 08:58
Closing as resolved. At the moment there is no stable version with this fix. I think it's safe to use the current beta since it will be released as stable v5.0 very soon.

**Closed by valeros** 2020-08-26 08:58 UTC
Labels: help wanted, static analysis

**Comment by arduhe** [comment] 2020-08-26 12:07
> I think it's safe to use the current beta

That's the same I always say about my software ;-)
