### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by talkingbeast** [platformio/platformio-core#1294] opened 2018-01-15 12:44 UTC
PIO Core Call Error: Platform /home/talkingbeast/.platformio/platforms/espressif8266@src-d2f6a4ecb96f34425e5e701de09dc0a9
--------
Updating espressif8266                   @ 3352890        [Up-to-date]
Updating tool-mkspiffs                   @ 1.200.0        [Up-to-date]
Updating tool-esptool                    @ 1.409.0        [Up-to-date]
Updating tool-espotapy                   @ 1.1.0          [Up-to-date]
Updating framework-arduinoespressif8266  @ 2c8b2b9        [12f336f]
git version 2.7.4

From https://github.com/esp8266/Arduino
   2c8b2b9..12f336f  master     -> origin/master
fatal: Not a git repository: /home/talkingbeast/.platformio/packages/_tmp_installing-ErRlE2-package/.git/modules/lwip2
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment] 2018-01-15 22:18
Duplicate of https://github.com/platformio/platformio-core/issues/1223

**Closed by ivankravets** 2018-01-15 22:18 UTC
