### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by NRJ-Javor** [platformio/platformio-core#1396] opened 2018-02-26 06:56 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 36 column 119 (char 4 - 2409)

**Comment by ivankravets** [comment] 2018-03-06 10:28
Duplicate of https://github.com/platformio/platformio-core/issues/1311

**Closed by ivankravets** 2018-03-06 10:28 UTC
