### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by MurzzZ** [platformio/platformio-core#1455] opened 2018-03-16 14:36 UTC
PIO Core Call Error: PlatformManager: Installing linux_arm
Downloading...
Unpacking...
linux_arm @ 1.4.6 has been successfully installed!
PackageManager: Installing toolchain-gccarmlinuxgnueabi @ ~1.40802.0

Error: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'windows_x86'

**Comment by ivankravets** [comment] 2018-03-16 15:43
Duplicate of https://github.com/platformio/platformio-core/issues/1452

**Closed by ivankravets** 2018-03-16 15:43 UTC
