### ISSUE TITLE
Home: Could not initialize project- server error

### ISSUE THREAD

**Issue by greg1714** [platformio/platformio-core#1729] opened 2018-07-10 11:43 UTC
hi
8-th generation I-7 - 8550U powered Acer  5 laptop running Win 10 (updated).  I installed Atom, Platform IO and Clung. Appears to be running fine but when trying to start new project, I get message "Could not initialize project - server error". 
I have good internet access and attempts to uninstall ATOM have been "never ending" - unsuccessful.
 Located in:    This PC > Acer (C) >Users > Greg >.atom.          Win 10 firewall does not have any entry regarding ATOM.
Similar installation on I-7 powered Win 7 older laptop installation and Arduino files editing works great. 
Any help would be appreciated.
                                                        Greg

**Comment by ivankravets** [comment] 2018-07-11 12:59
Duplicate of https://github.com/platformio/platformio-core/issues/1616

**Closed by ivankravets** 2018-07-11 12:59 UTC
