### ISSUE TITLE
Debugging support for "SparkFun Pro Micro 5V/16MHz"

### ISSUE THREAD

**Issue by CiriousJoker** [platformio/platformio-core#3334] opened 2020-01-08 18:26 UTC
### Configuration

**Operating system**:

**PlatformIO Version** (`platformio --version`): 4.1.0

### Description of problem
Title says it all. I can't debug code on my "SparkFun Pro Micro 5V/16MHz" and the error message told me to create an issue in this repository.

I'm kind of confused by this big issue template, so I deleted most of it. I hope that's ok for you.

**Comment by maxgerhardt** [comment] 2020-01-09 22:26
AVR Debugger support is difficult for a number of reasons pointed on in the existing issue https://github.com/platformio/platform-atmelavr/issues/95 and e.g. https://community.platformio.org/t/debugger-for-arduino-uno-mega-and-esp8266/5307/8 and https://community.platformio.org/t/atmel-ice-debugger/4396/4.

**Comment by ivankravets** [comment] 2020-01-22 19:24
Duplicate of https://github.com/platformio/platform-atmelavr/issues/95

**Closed by ivankravets** 2020-01-22 19:24 UTC
