### ISSUE TITLE
Add Raspberry Pi Pico support

### ISSUE THREAD

**Issue by Can-too** [platformio/platformio-core#3937] opened 2021-04-24 00:58 UTC
-  **Feature Request**.
      I would like  to use PlatformIO with my Raspberry PI PICO to code in MicroPython

------------------------------------------------------------------

### Additional info
Raspberry Pi Pico powered by RP2040 dual-core Cortex-M0+ microcontroller designed in-house by the Raspberry Pi Foundation

**Comment by ivankravets** [comment] 2021-04-24 14:27
Duplicate of https://github.com/platformio/platformio-core/issues/728

**Closed by ivankravets** 2021-04-24 14:27 UTC
