### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by RamilRamizugly** [platformio/platformio-core#2091] opened 2019-01-31 19:02 UTC
PIO Core Call Error: "The next files/directories have been created in /home/rut/Documents/PlatformIO/Projects/Blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'linux_aarch64'"

**Comment by ivankravets** [comment] 2019-02-02 16:39
Duplicate of https://github.com/platformio/platformio-core/issues/2090

**Closed by ivankravets** 2019-02-02 16:39 UTC
