### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by saleh-mehdikhani** [platformio/platformio-core#2098] opened 2019-02-05 11:02 UTC
PIO Core Call Error: "The next files/directories have been created in E:\\SalehProjects\\ClockifyGadget\\testBearSSL\\testBearSSL\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing nodemcuv2overclock (platform: espressif8266; board: nodemcuv2overclock; framework: arduino)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'nodemcuv2overclock'\r\n [ERROR] Took 0.63 seconds"

**Comment by ivankravets** [comment] 2019-02-23 16:19
Duplicate of https://github.com/platformio/platformio-core/issues/2096

**Closed by ivankravets** 2019-02-23 16:19 UTC
