### ISSUE TITLE
Arduino Mega 2560 Debug Support

### ISSUE THREAD

**Issue by ApacheHelicopter** [platformio/platformio-core#3323] opened 2019-12-30 04:53 UTC
Hello, I would like to start off by saying that I absolutely love this editor! It is very easy to use compared to the regular Arduino IDE.

I plugged in my board, and tried to open the debug window, but it said it is not currently supported. Will debug support for the Mega 2560 be coming soon?

**Comment by ivankravets** [comment] 2020-01-03 19:59
Duplicate of https://github.com/platformio/platform-atmelavr/issues/95

**Closed by ivankravets** 2020-01-03 19:59 UTC
