### ISSUE TITLE
Home: Libraries: Could not uninstall library

### ISSUE THREAD

**Issue by twobaker** [platformio/platformio-core#1700] opened 2018-06-21 21:25 UTC
PIO Core Call Error: Library Storage: C:\xyz\Documents\PlatformIO\Projects\ESP32 OTA\.piolibdeps

Error: Detected unknown package 'C:\xyz\Documents\PlatformIO\Projects\ESP32 OTA\.piolibdeps\EasyOTA_ID1975 @ *'

**Comment by ivankravets** [comment] 2018-06-25 20:22
Duplicate of https://github.com/platformio/platformio-core/issues/1700

**Closed by ivankravets** 2018-06-25 20:22 UTC
