### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by ChuckVanzant** [platformio/platformio-core#1917] opened 2018-11-09 16:43 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 4 column 69 (char 1635 - 1800)

**Comment by ivankravets** [comment] 2018-11-19 17:21
Duplicate of https://github.com/platformio/platformio-core/issues/1311

**Closed by ivankravets** 2018-11-19 17:21 UTC
