### ISSUE TITLE
Support for Arduino Uno WiFi Rev2

### ISSUE THREAD

**Issue by mrarmyant** [platformio/platformio-core#2092] opened 2019-02-01 16:30 UTC
There is only the default uno.  It throws all sorts of errors using the wifinina package.

`Processing uno (platform: atmelavr; board: uno; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/uno.html
PLATFORM: Atmel AVR > Arduino Uno
HARDWARE: ATMEGA328P 16MHz 2KB RAM (31.50KB Flash)
Converting main.ino
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 6 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <SPI> 1.0
|-- <WiFiNINA> 1.3.0
|   |-- <SPI> 1.0
Compiling .pioenvs/uno/src/main.ino.cpp.o
Compiling .pioenvs/uno/lib731/WiFiNINA_ID5538/utility/spi_drv.cpp.o
Compiling .pioenvs/uno/FrameworkArduino/HardwareSerial.cpp.o
/.platformio/lib/WiFiNINA_ID5538/src/utility/spi_drv.cpp: In static member function 'static void SpiDrv::begin()':
/.platformio/lib/WiFiNINA_ID5538/src/utility/spi_drv.cpp:87:24: error: 'PINS_COUNT' was not declared in this scope
if (SLAVERESET > PINS_COUNT) {
^
/.platformio/lib/WiFiNINA_ID5538/src/utility/spi_drv.cpp:97:15: error: 'NINA_GPIO0' was not declared in this scope
pinMode(NINA_GPIO0, OUTPUT);
^
/.platformio/lib/WiFiNINA_ID5538/src/utility/spi_drv.cpp: In static member function 'static int SpiDrv::available()':
/.platformio/lib/WiFiNINA_ID5538/src/utility/spi_drv.cpp:565:25: error: 'NINA_GPIO0' was not declared in this scope
return (digitalRead(NINA_GPIO0) != LOW);
^
Compiling .pioenvs/uno/FrameworkArduino/HardwareSerial0.cpp.o
*** [.pioenvs/uno/lib731/WiFiNINA_ID5538/utility/spi_drv.cpp.o] Error 1`

**Comment by ivankravets** [comment] 2019-02-02 16:53
Duplicate of https://github.com/platformio/platform-atmelavr/issues/112

**Closed by ivankravets** 2019-02-02 16:53 UTC
