### ISSUE TITLE
Home: Platforms: Frameworks

### ISSUE THREAD

**Issue by roboter** [platformio/platformio-core#2093] opened 2019-02-01 16:39 UTC
PIO Core Call Error: "Error: You are not connected to the Internet.
If you build a project first time, we need Internet connection to install all dependencies and toolchains."
Linux Ubuntu  x86_64

**Comment by ivankravets** [comment] 2019-02-02 16:54
Duplicate of https://github.com/platformio/platformio-core/issues/2088

**Closed by ivankravets** 2019-02-02 16:54 UTC
