### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by sinafarhadiee** [platformio/platformio-core#2189] opened 2019-03-05 15:27 UTC
Server error: {"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\sa\\\\Documents\\\\PlatformIO'","args":[2,"The system cannot find the file specified"],"type":"WindowsError"}

**Comment by ivankravets** [comment] 2019-03-07 10:58
Duplicate of https://github.com/platformio/platformio-core/issues/2067

**Closed by ivankravets** 2019-03-07 10:58 UTC
