### ISSUE TITLE
Remote Serial Connection

### ISSUE THREAD

**Issue by phhoef** [platformio/platformio-core#1101] opened 2017-10-02 14:52 UTC
It would be nice to have a remote serial connection to send some serial commands to the remote device.
So, I do not want to flash the firmware, but send some serial commands to a remote device.
I am using a small Python script using pySerial to configure the device. It would be great if I could run such scripts from remote.

**Comment by phhoef** [comment] 2018-05-27 10:35
Any news on that :-)?

**Comment by ivankravets** [comment] 2019-05-23 18:20
Duplicate of https://github.com/platformio/platformio-core/issues/2228

**Closed by ivankravets** 2019-05-23 18:20 UTC
Labels: PIO Plus, feature
