### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by czecht** [platformio/platformio-core#2322] opened 2019-04-16 01:29 UTC
PIO Core Call Error: "PlatformManager: Installing AdvancedPlatformInstallation-4-15-2019-first-project\n\nError: Detected unknown package 'AdvancedPlatformInstallation-4-15-2019-first-project'"

When I closed the error I was asked to install Advanced platform installation.
I do not know how this works, but it isn't going as the video that I'm following on the youtube: 

https://www.youtube.com/watch?v=0poh_2rBq7E

**Comment by ivankravets** [comment] 2019-04-17 17:16
Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Closed by ivankravets** 2019-04-17 17:16 UTC
