### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by saouinet** [platformio/platformio-core#1895] opened 2018-10-26 11:25 UTC
PIO Core Call Error: Error: You are not connected to the Internet.
If you build a project first time, we need Internet connection to install all dependencies and toolchains.

Using a  proxy on windows 10

**Comment by ivankravets** [comment] 2018-10-27 17:09
Duplicate of https://github.com/platformio/platformio-core/issues/1861

**Closed by ivankravets** 2018-10-27 17:09 UTC
