### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by nowaylv** [platformio/platformio-core#2938] opened 2019-08-23 03:16 UTC
PIO Core Call Error: "The current working directory C:\\Users\\18459\\Documents\\PlatformIO\\Projects\\point array will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\18459\\Documents\\PlatformIO\\Projects\\point array\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing ststm8\nDownloading\nDownloading\nUnpacking\nUnpacking\nststm8 @ 1.0.1 has been successfully installed!\nPackageManager: Installing tool-stm8binutils @ 0.230.0\r\nDownloading\nDownloading\nUnpacking\nUnpacking\ntool-stm8binutils @ 0.230.0 has been successfully installed!\nPackageManager: Installing toolchain-sdcc @ ~1.30804.10766\r\nDownloading\nDownloading\nUnpacking\nUnpacking\ntoolchain-sdcc @ 1.30804.10766 has been successfully installed!\nThe platform 'ststm8' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment.\r\n\n\nError: Processing stm8sblue (platform: ststm8; board: stm8sblue; framework: spl)\n\nPackageManager: Installing framework-ststm8spl @ 0.20301.181217\nDownloading\nDownloading\nUnpacking\nUnpacking\nframework-ststm8spl @ 0.20301.181217 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm8/stm8sblue.html\nPLATFORM: ST STM8 1.0.1 > ST STM8S103F3 Breakout Board\nHARDWARE: STM8S103F3P6 16MHz, 1KB RAM, 8KB Flash\nPACKAGES: framework-ststm8spl 0.20301.181217 (2.3.1), tool-stm8binutils 0.230.0 (2.30), toolchain-sdcc 1.30804.10766 (3.8.4)\nError: Could not parse library files for the target.\nstm8s.h:2723:25: fatal error: stm8s_conf.h: No such file or directory\r\n\n********************************************************************\n* Looking for stm8s_conf.h dependency? Check our library registry!\n*\n* CLI  > platformio lib search \"header:stm8s_conf.h\"\n* Web  > https://platformio.org/lib/search?query=header:stm8s_conf.h\n*\n********************************************************************\n\n [ERROR] Took 15.92 seconds"

**Comment by ivankravets** [comment] 2019-08-23 12:58
Duplicate of https://github.com/platformio/platform-ststm8/issues/6

**Closed by ivankravets** 2019-08-23 12:58 UTC
