### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by testerxxx** [platformio/platformio-core#2452] opened 2019-05-04 20:24 UTC
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\Viper\\Documents\\PlatformIO\\Projects\\190503-144210-arduino-blink\\platformio.ini, line: 1\n'com; PlatformIO Project Configuration File\\n''","args":["File contains no section headers.\nfile: C:\\Users\\Viper\\Documents\\PlatformIO\\Projects\\190503-144210-arduino-blink\\platformio.ini, line: 1\n'com; PlatformIO Project Configuration File\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment] 2019-05-06 15:34
Duplicate of https://github.com/platformio/platformio-core/issues/2260

**Closed by ivankravets** 2019-05-06 15:34 UTC
