### ISSUE TITLE
Home: Could not list directoryC:\\Documents and Settings

### ISSUE THREAD

**Issue by timurufa86** [platformio/platformio-core#1116] opened 2017-10-11 05:54 UTC
Could not list directory by `C:\\Documents and Settings`

**Comment by ivankravets** [comment] 2017-10-17 23:10
Do you have files with non-ascii chars in this directory? What is your locale?

**Comment by ivankravets** [comment] 2017-10-19 12:27
Duplicate of https://github.com/platformio/platformio-core/issues/1105

**Closed by ivankravets** 2017-10-19 12:27 UTC
Labels: help wanted, home
