### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by bigyen** [platformio/platformio-core#2513] opened 2019-05-18 16:08 UTC
PIO Core Call Error: "<Exception instance at 0x757f108 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\ian\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 204-208: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-05-23 18:33
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Closed by ivankravets** 2019-05-23 18:33 UTC
