### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by xuongrau** [platformio/platformio-core#2082] opened 2019-01-30 12:07 UTC
PIO Core Call Error: "<Exception instance at 0x53e9cc8 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\KCOM\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xf5' in position 29: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-02-23 15:00
Duplicate of https://github.com/platformio/platformio-core/issues/2078

**Closed by ivankravets** 2019-02-23 15:00 UTC
