### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by fahrulputra40** [platformio/platformio-core#2298] opened 2019-04-07 15:22 UTC
PIO Core Call Error: "The next files/directories have been created in E:\\teensy\\stm32\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing black_f407vg (platform: ststm32; board: black_f407vg; framework: stm32cube)\r\n\r\nPackageManager: Installing toolchain-gccarmnoneeabi @ >=1.40803.0,<1.40805.0\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\nPackageManager: Installing framework-stm32cube @ ~1.0.0\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'black_f407vg'\r\n [ERROR] Took 201.41 seconds"

**Comment by ivankravets** [comment] 2019-04-17 20:02
Duplicate of https://github.com/platformio/platformio-core/issues/2299

**Closed by ivankravets** 2019-04-17 20:02 UTC

**Comment by ukey-ltd** [comment] 2021-09-01 03:31
Hi Fahrulputra40, 

I sent you a message on Fiverr.

Please check it.

Regards
