### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by lanmushan** [platformio/platformio-core#1739] opened 2018-07-14 11:56 UTC
PIO Core Call Error: The next files/directories have been created in G:\test\led
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Processing genericSTM32F103ZE (platform: ststm32; board: genericSTM32F103ZE; framework: stm32cube)

Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'genericSTM32F103ZE'
 [ERROR] Took 0.83 seconds

**Comment by ivankravets** [comment] 2018-07-14 12:14
Duplicate of https://github.com/platformio/platformio-core/issues/1738

**Closed by ivankravets** 2018-07-14 12:14 UTC
