### ISSUE TITLE
Home: The system cannot find the file specified

### ISSUE THREAD

**Issue by herry93** [platformio/platformio-core#2718] opened 2019-06-28 07:48 UTC
Server error: {"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\rnd01\\\\Documents\\\\PlatformIO'","args":[2,"The system cannot find the file specified"],"type":"WindowsError"}

**Comment by ivankravets** [comment] 2019-06-28 10:57
It seems that your antivirus tools remove files which PlatformIO Core create.

**Comment by ivankravets** [comment] 2019-07-04 16:39
Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Comment by ivankravets** [comment] 2019-07-04 16:39
Do you have an antivirus tool in a system?

**Closed by ivankravets** 2019-07-04 16:39 UTC
Labels: known issue
