### ISSUE TITLE
compile_commands.json include toolchain headers by default

### ISSUE THREAD

**Issue by gagara** [platformio/platformio-core#4130] opened 2021-12-04 18:07 UTC
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

**Operating system**:

GNU/Linux

**PlatformIO Version** (`platformio --version`):

PlatformIO Core, version 5.2.3

### Description of problem
`compile_commands.json` does not include path to toolchain headers, thus clangd unable to resolve some toolchain headers

#### Steps to Reproduce

1. Setup sample project
2. Generate `compile_commands.json`
```
$ pio run -t compiledb
```
3. Import project to clangd enabled IDE/editor (I use vim)

### Actual Results
Navigate to `Arduino.h` -- works fine.
All includes in `Arduino.h` are wrongly resolved. Some of them (e.g. `math.h`) resolved to host headers at `/usr`, others, avr specific (e.g. `avr/io.h`) failed to resolve.

### Expected Results
All headers/sources should be resolved correctly

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>
void setup() {
}
void loop() {
}
```

### Additional info
Possible workaround: Add missing include in project config:
```ini
[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags =
	-I${platformio.packages_dir}/toolchain-atmelavr/avr/include
```
In this case all sources resolved correctly.
I think this path should be included by default.

**Comment by ivankravets** [comment] 2022-04-08 14:08
Duplicate of https://github.com/platformio/platformio-core/issues/3735

**Closed by ivankravets** 2022-04-08 14:08 UTC
Labels: enhancement, integration
