### ISSUE TITLE
Home: Could not load mDNS services

### ISSUE THREAD

**Issue by Cra5h0verride** [platformio/platformio-core#1807] opened 2018-08-24 22:26 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 3 column 124 (char 476 - 599)

**Comment by ivankravets** [comment] 2018-08-27 17:50
Duplicate of https://github.com/platformio/platformio-core/issues/1582

**Closed by ivankravets** 2018-08-27 17:50 UTC
