### ISSUE TITLE
STM32 Bluepill mbed-os support

### ISSUE THREAD

**Issue by Split7fire** [platformio/platformio-core#847] opened 2016-12-06 05:11 UTC
While platformio already has mbed (classic?) support of Bluepill (stm32f103). It currently don't support USBSERIAL (USBENDPOINTS missing). Also I noticed strange lug in Blink example.

So, mbed-os repo does include STM32F103 bluepill target and claims support of this boards.
Could it be possible to add this support to PlatformIO?

**Comment by Split7fire** [comment] 2016-12-06 05:20
Sorry for the noise. I figured out that this situation already discussed https://github.com/platformio/platformio-core/issues/835
https://github.com/platformio/platformio-core/issues/819

**Comment by ivankravets** [comment] 2016-12-06 11:30
Duplicate of https://github.com/platformio/platformio-core/issues/835

**Closed by ivankravets** 2016-12-06 11:30 UTC
Labels: duplicate
