### ISSUE TITLE
The presentation tabs (while downloading toolchains) switches too fast !

### ISSUE THREAD

**Issue by Navis-Raven** [platformio/platformio-core#1827] opened 2018-09-01 03:34 UTC
- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 7, VSCode

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.6.1a1

### Description of problem
When choosing a new board, and downloading the libraries and toolchains, the tabs of the presentation displayed moves too rapidly, so we can't read them

![image](https://user-images.githubusercontent.com/15887222/44941977-15ffd980-ada8-11e8-84b6-bff6207377d5.png)

#### Steps to Reproduce

1. Click on New Project and type a project name, select a board and a framework then click finish
2. A Window displays a presentation with four tabs while downloading the toolchains, framework etc...

### Actual Results
The tabs switch from one to the other automatically too fast, so we can't finish the reading of what's inside

### Expected Results
Please slow down this switch, let at least 15 s for each tab.

**Comment by ivankravets** [comment] 2018-09-05 23:34
Duplicate of https://github.com/platformio/platformio-core/issues/1442

P.S: Just move the mouse over slides and it will stop.

**Closed by ivankravets** 2018-09-05 23:34 UTC

**Comment by Navis-Raven** [comment] 2018-09-06 07:43
@ivankravets 
additionnal info: even if you click on the previous tab to return back it doesn't stay enough time and go further to the next tab.
