### ISSUE TITLE
Kindly Add VEGA ARIES Boards to the PlatformIO Extension

### ISSUE THREAD

**Issue by ashrafulkhn** [platformio/platformio-core#4815] opened 2023-12-24 08:23 UTC
What kind of issue is this?

- [ ] **Feature Request**.

Hi, <br>
<p>I love using PlatformIO Extension for my projects and would like to have a new board to be part of the extension.
Kindly add the VEGA ARIES Boards which use RISC-V architecture. I think these boards are going to have a big impact on the development board market soon. </p>
<br>
<p>Here is the link to the board file JSON. <br>
<a href="https://gitlab.com/riscv-vega/vega-arduino/-/raw/main/package_vega_index.json">Board RAW JSON</a> </p>

<br>
<p>For reference, you may look for details of the board from the link below: <br>
<a href="https://vegaprocessors.in/devboards">VEGA ARIES Boards</a>
</p>

Thank you in advance.

**Comment by ivankravets** [comment] 2023-12-30 16:00
Duplicate of https://github.com/platformio/platformio-core/issues/4792

**Closed by ivankravets** 2023-12-30 16:00 UTC
