### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by Pawel-Was** [platformio/platformio-core#2219] opened 2019-03-14 14:42 UTC
PIO Core Call Error: "<Exception instance at 0x4fd6e08 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u0142' in position 30: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-03-14 17:39
Duplicate of https://github.com/platformio/platformio-core/issues/2078

**Closed by ivankravets** 2019-03-14 17:39 UTC
