### ISSUE TITLE
Home: Platforms: Frameworks

### ISSUE THREAD

**Issue by cyclemat** [platformio/platformio-core#1868] opened 2018-10-01 23:49 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 3 column 66 (char 7514 - 7579)

**Comment by ivankravets** [comment] 2018-10-03 21:59
Duplicate of https://github.com/platformio/platformio-core/issues/1311

**Closed by ivankravets** 2018-10-03 21:59 UTC
