### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by aldibagas** [platformio/platformio-core#2909] opened 2019-08-16 10:32 UTC
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\PC\\\\Documents\\\\PlatformIO\\\\Projects\\\\190816-173230-arduino-blink'","type":"WindowsError"}

**Comment by ivankravets** [comment] 2019-08-17 19:47
Do have antivirus tools in a system? They block PlatformIO. 

Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Closed by ivankravets** 2019-08-17 19:47 UTC

**Comment by ivankravets** [comment] 2019-08-17 20:01
Do have antivirus tools in a system? They block PlatformIO.

Duplicate of #2321
