### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 179: character maps to <undefined>

### ISSUE THREAD

**Issue by pawcio0928** [platformio/platformio-core#3493] opened 2020-05-06 09:02 UTC
Hi I have similar issue to [https://github.com/platformio/platformio-core/issues/3481](url)
`Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\pawel\.platformio\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\pawel\.platformio\python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pawel\.platformio\penv\lib\site-packages\platformio\proc.py", line 46, in run
    self.do_reading()
  File "C:\Users\pawel\.platformio\penv\lib\site-packages\platformio\proc.py", line 69, in do_reading
    for byte in iter(lambda: self._pipe_reader.read(1), ""):
  File "C:\Users\pawel\.platformio\penv\lib\site-packages\platformio\proc.py", line 69, in <lambda>
    for byte in iter(lambda: self._pipe_reader.read(1), ""):
  File "C:\Users\pawel\.platformio\python37\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 179: character maps to <undefined>`
I am using PlatformIO 4.3.4a1 on Windows 10. This error shows when I try to build and upload Marlin FW.

Please help resolve that issue.

**Comment by ivankravets** [comment] 2020-05-08 21:02
Duplicate of https://github.com/platformio/platformio-core/issues/3481

**Closed by ivankravets** 2020-05-08 21:02 UTC
