### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by holowa** [platformio/platformio-core#3156] opened 2019-10-19 01:32 UTC
PIO Core Call Error: "The current working directory /Users/wqearth/Documents/PlatformIO/Projects/stm8 will be used for the project.\n\nThe next files/directories have been created in /Users/wqearth/Documents/PlatformIO/Projects/stm8\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing stm8sblack (platform: ststm8; board: stm8sblack; framework: spl)\n--------------------------------------------------------------------------------\nPackageManager: Installing framework-ststm8spl @ 0.20301.181217\nframework-ststm8spl @ 0.20301.181217 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm8/stm8sblack.html\nPLATFORM: ST STM8 1.0.1 > ST STM8S105K4T6 Breakout Board\nHARDWARE: STM8S105K4T6 16MHz, 2KB RAM, 16KB Flash\nPACKAGES: toolchain-sdcc 1.30804.10766 (3.8.4), framework-ststm8spl 0.20301.181217 (2.3.1), tool-stm8binutils 0.230.0 (2.30)\nError: Could not parse library files for the target.\nstm8s.h:2723:25: fatal error: stm8s_conf.h: No such file or directory\n\n********************************************************************\n* Looking for stm8s_conf.h dependency? Check our library registry!\n*\n* CLI  > platformio lib search \"header:stm8s_conf.h\"\n* Web  > https://platformio.org/lib/search?query=header:stm8s_conf.h\n*\n********************************************************************\n\ncompilation terminated.\n========================== [FAILED] Took 7.99 seconds =========================="

**Comment by ivankravets** [comment] 2019-10-20 12:17
Duplicate of platformio/platform-ststm8#6

**Closed by ivankravets** 2019-10-20 12:17 UTC
