### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by texjoachim** [platformio/platformio-core#1071] opened 2017-09-15 08:09 UTC
PIO Core Call Error: got stderr: 'Von https://github.com/platformio/platform-atmelavr\n   30472b2..e2d0381  develop    -> origin/develop\n'

**Comment by ivankravets** [comment] 2017-09-15 11:07
Duplicate of https://github.com/platformio/platformio-core/issues/1038

**Comment by ivankravets** [comment] 2017-09-15 11:07
Thanks! Will be resolved soon!

**Closed by ivankravets** 2017-09-15 11:07 UTC
