### ISSUE TITLE
Home: Could not list directory/Users/ali/Documents/PlatformIO/Projects

### ISSUE THREAD

**Issue by engali94** [platformio/platformio-core#2327] opened 2019-04-17 12:30 UTC
Invalid params: {"type":"TypeError","args":["'cmp' is an invalid keyword argument for this function"],"message":"'cmp' is an invalid keyword argument for this function"}

**Comment by ivankravets** [comment] 2019-04-17 17:23
Duplicate of https://github.com/platformio/platformio-core/issues/2319

**Comment by ivankravets** [comment] 2019-04-17 17:26
Duplicate of https://github.com/platformio/platformio-core/issues/2169

**Closed by ivankravets** 2019-04-17 17:26 UTC
