### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by igor-markevich** [platformio/platformio-core#2099] opened 2019-02-05 15:04 UTC
Server error: {"message":"[Error 2] : u'C:\\\\Users\\\\i.markevich\\\\Documents\\\\PlatformIO'","args":[2,""],"type":"WindowsError"}

**Comment by ivankravets** [comment] 2019-02-23 16:24
Duplicate of https://github.com/platformio/platformio-core/issues/2067

**Closed by ivankravets** 2019-02-23 16:24 UTC
