### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by pratikguru** [platformio/platformio-core#1100] opened 2017-10-02 11:39 UTC
I get this long error when I want to start a new project, the trace back is quite a long one, with PIO Call error.. I tried re installing Platform IO but didn't help much.

**Comment by ivankravets** [comment] 2017-10-03 11:28
Duplicate of https://github.com/platformio/platformio-core/issues/1099

**Closed by ivankravets** 2017-10-03 11:28 UTC
