### ISSUE TITLE
Debugger Support for MSP432P401R and MSP432P4111

### ISSUE THREAD

**Issue by CraftBreadth** [platformio/platformio-core#4503] opened 2022-12-31 04:00 UTC
Hello Platformio team!

It would be greatly appreciated to add debugger support for the MSP432 line of boards. These boards are already compatible with the TI MSP Debugger (XDS110 USB Debug Probe) which appears to already be implemented in platformio. I should note that although the MSP432P4111 is not officially supported if you change the msp.h to a msp432P411 header file it works fine.

P.S Thank I love the platformio extension as it allows me to avoid using code composer studio, a classically bad eclipse based IDE.

**Comment by ivankravets** [comment] 2023-01-03 21:12
Duplicate of https://github.com/platformio/platformio-core/issues/147

**Closed by ivankravets** 2023-01-03 21:12 UTC
