### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by gecrby** [platformio/platformio-core#2736] opened 2019-07-03 08:02 UTC
Server error: {"message":"[Error 2] : u'C:\\\\Users\\\\user\\\\Documents\\\\PlatformIO'","args":[2,""],"type":"WindowsError"}

**Comment by ivankravets** [comment] 2019-07-03 10:50
Duplicate of https://github.com/platformio/platformio-core/issues/2718

**Closed by ivankravets** 2019-07-03 10:50 UTC
