### ISSUE TITLE
Cannot influence include flags via library's extra script

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platformio-core#2431] opened 2019-04-28 19:51 UTC
- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.
------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10 x64

**PlatformIO Version** (`platformio --version`): `PlatformIO, version 4.0.0a8`

### Description of problem

Due to certain circumstances in ESP-IDF and ESP-ADF I have first remove a  `-I` flag and then inject a `-I` flag into the build-process of the framework when a certain library is included. For this purpose, my `library.json` looks like this

```json
{
  "name": "esp_http_client",
  "keywords": "audio, esp-adf",
  "description": "The esp_http_client component of ESP-ADF",
  "repository": {
    "type": "git",
    "url": "https://github.com/maxgerhardt/tobefilled.git"
  },
  "version": "1.0",
  "authors": {
    "name": "ESPRESSIF SYSTEMS (SHANGHAI) PTE LTD",
    "url": "https://github.com/espressif/esp-adf"
  },
  "licence": "MIT",
  "frameworks": "espidf",
  "platforms": "espressif32",
  "build" : {
    "flags": [
      "-I include",
      "-I lib/include"
    ],
    "extraScript": "fix_compilation.py"
  }
}
```` 

(in the `platformio.ini` has `build_unflags = -I"C:/Users/Maxi/.platformio/packages/framework-espidf/components/esp_http_client/include"`)

And `fix_compilation.py`:

```py
Import("env")
import os

print("=========== FIX_COMPILATION CALLED =========")
# directory in which this script is located
script_dir = os.path.dirname(os.path.realpath('__file__'))

global_env = DefaultEnvironment()

global_env.Append(CPPPATH=[
    os.path.join(script_dir, "include"),
    os.path.join(script_dir, "lib", "include")
])

env.Append(CPPPATH=[
    os.path.join(script_dir, "include"),
    os.path.join(script_dir, "lib", "include")
])

print global_env.Dump()
```

In the resulting dump I can see that the folders were successfully added to the `CPPPATH`

```
[...]
'C:\\Users\\Maxi\\Desktop\\pio-esp-adf-example\\lib\\esp_http_client\\include',
'C:\\Users\\Maxi\\Desktop\\pio-esp-adf-example\\lib\\esp_http_client\\lib\\include'],
```

However, when compiling the ESP-IDF framework, the the compiler doesn't care about the include paths I added and will throw an error 

```
C:/Users/Maxi/.platformio/packages/framework-espidf/components/esp_https_ota/include/esp_https_ota.h:17:29: fatal error: esp_http_client.h: No such file or directory
```

(This file is in the `include` folder I attempted to add above)

With the build command being 

```
xtensa-esp32-elf-gcc -o .pioenvs\esp32dev\esp_http_client\esp_http_client.o -c -Wno-old-style-declaration -std=gnu99 -Werror=all -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-error=unused-function -mfix-esp32-psram-cache-issue -Os -Wall -nostdlib -Wpointer-arith -Wno-error=unused-but-set-variable -Wno-error=unused-variable -mlongcalls -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -DWITH_POSIX -DIDF_VER=\"3.30200.190418\" -DPLATFORMIO=40000 -DARDUINO_ESP32_DEV -DCONFIG_ESP_LYRATD_MSC_V2_2_BOARD -DCONFIG_SPIRAM_CACHE_WORKAROUND -DCONFIG_SPIRAM_SUPPORT=1 -DCONFIG_SPIRAM_BOOT_INIT -DCONFIG_SPIRAM_TYPE_AUTO=1 -DCONFIG_SPIRAM_SIZE=-1 -DCONFIG_SPIRAM_SPEED_40M -DCONFIG_SPIRAM_MEMTEST=1 -DCONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768 -DCONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384 -DCONFIG_SPIRAM_USE_MALLOC=1 -DCONFIG_SUPPORT_STATIC_ALLOCATION=1 -DCONFIG_PICO_PSRAM_CS_IO=10 -DCONFIG_SPIRAM_OCCUPY_VSPI_HOST -DESP32 -DESP_PLATFORM -DF_CPU=240000000L -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DGCC_NOT_5_2_0=0 @"C:\Users\Maxi\Desktop\pio-esp-adf-example\.pioenvs\esp32dev\longcmd-38b92633808e77fc2639c6be40524896" C:\Users\Maxi\.platformio\packages\framework-espidf\components\esp_http_client\esp_http_client.c
```

And the longcmd being [here](https://pastebin.com/pgQeyw8L). 

I simpy can't get it to put a `-I ..` flag in the global build process. I have also tried with `CCFLAGS` without success. 

How can I force the injection of a `-I` flag through the extra script of a library? It seems to be ignored completely. This seems very much as a bug because I'm adding this to the build environment but it doesn't use it properly.

**Comment by ivankravets** [comment] 2019-05-03 10:42
Duplicate of https://github.com/platformio/platformio-core/issues/1941

Could you try https://community.platformio.org/t/library-json-global-build-flag/3814/3?u=ivankravets ? ` global_env = DefaultEnvironment()`.

**Closed by ivankravets** 2019-05-03 10:42 UTC
Labels: lib
