### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by sve95** [platformio/platformio-core#1714] opened 2018-07-01 06:39 UTC
PIO Core Call Error: Library Storage: D:\user\work\platformio\ttgo\.piolibdeps

Error: Detected unknown package 'D:\user\work\platformio\ttgo\.piolibdeps\Adafruit ST7735 Library_ID12 @ *'

**Comment by ivankravets** [comment] 2018-07-03 12:01
Duplicate of https://github.com/platformio/platformio-core/issues/1346

**Closed by ivankravets** 2018-07-03 12:01 UTC
