### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by dunk8888** [platformio/platformio-core#1195] opened 2017-11-21 15:31 UTC
PIO Core Call Error: Error: Could not load broken JSON: C:\Users\Dunk\.platformio\lib\I2C_Sensor\library.json

**Comment by dunk8888** [comment] 2017-11-21 15:32
same with arduino debug.exe

**Comment by ivankravets** [comment] 2017-11-21 15:36
Duplicate of https://github.com/platformio/platformio-core/issues/1194

**Closed by ivankravets** 2017-11-21 15:36 UTC
