### ISSUE TITLE
Add CH58x board 

### ISSUE THREAD

**Issue by opilat** [platformio/platformio-core#4731] opened 2023-08-31 14:01 UTC
Hi can, you please add support for the CH58x board? There is already some Arduino IDE support https://github.com/ElectronicCats/arduino-wch58x. Unfortunately, It cannot be directly used with PlatformIO.

**Comment by ivankravets** [comment] 2023-08-31 19:10
Duplicate of https://github.com/platformio/platformio-core/issues/3802

**Closed by ivankravets** 2023-08-31 19:10 UTC
