### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by free1980** [platformio/platformio-core#2123] opened 2019-02-12 10:03 UTC
Server error: {"message":"[API] Could not connect to PlatformIO API Service. Please try later.","args":["Could not connect to PlatformIO API Service. Please try later."],"type":"APIRequestError"}

**Comment by ivankravets** [comment] 2019-02-23 16:56
Duplicate of https://github.com/platformio/platformio-core/issues/2117

**Closed by ivankravets** 2019-02-23 16:56 UTC
