### ISSUE TITLE
Add "SparkFun ReadBoard Turbo"

### ISSUE THREAD

**Issue by mrtheski** [platformio/platformio-core#3262] opened 2019-11-10 15:18 UTC
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ X] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
Mac OS 10.14.6, iMac Pro computer
**PlatformIO Version** (`platformio --version`):
Home: 3.0.0 Core: 4.1.0
### Description of problem

Please Add "Sparkfun RedBoard Turbo" to Platformio IDE

#### Steps to Reproduce
N/A

### Actual Results
N/A

### Expected Results

Hope that I do not have to wait to long for the board to be added.

### If problems with PlatformIO Build System:
none
**The content of `platformio.ini`:**
N/A
Insert here...
N/A
**Source file to reproduce issue:**
N/A
Insert here...
N/A

**Comment by ivankravets** [comment] 2019-11-11 21:28
Duplicate of https://github.com/platformio/platform-atmelsam/issues/85

**Closed by ivankravets** 2019-11-11 21:28 UTC
