### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by jeremybuisson** [platformio/platformio-core#1063] opened 2017-09-12 11:51 UTC
Server error

Same as in issue #1062, but leave "Use default location" ticked. Click finish. and... tada!
No other information appears in Code's window.

**Comment by ivankravets** [comment] 2017-09-21 19:07
Could you open PIO IDE Terminal and type
```
pio upgrade
pio update
```
Restart IDE.

Does it work now?

**Comment by candidoneto89** [comment] 2017-09-22 19:02
Having the same issue. I have folders with non-ascii characters too. Tried what was suggested and still facing this problem.

**Comment by ivankravets** [comment] 2017-10-19 12:25
Duplicate of https://github.com/platformio/platformio-core/issues/1062

**Closed by ivankravets** 2017-10-19 12:25 UTC
Labels: help wanted, home
