### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by devxetechs** [platformio/platformio-core#2514] opened 2019-05-19 01:54 UTC
PIO Core Call Error: "The next files/directories have been created in /home/bashman/1/melo\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing ststm32\nDownloading\nDownloading\nUnpacking\nUnpacking\nststm32 @ 5.4.0 has been successfully installed!\nPackageManager: Installing toolchain-gccarmnoneeabi @ >=1.60301.0,<1.80000.0\nDownloading\nDownloading\nUnpacking\nUnpacking\ntoolchain-gccarmnoneeabi @ 1.70201.0 has been successfully installed!\nThe platform 'ststm32' has been successfully installed!\nThe rest of packages will be installed automatically depending on your build environment.\n\nError: Processing genericSTM32F103C8 (platform: ststm32; board: genericSTM32F103C8; framework: libopencm3)\n--------------------------------------------------------------------------------------------------------------------------------\nPackageManager: Installing framework-libopencm3 @ ~1.1.0\nDownloading\nDownloading\nUnpacking\nUnpacking\nCorePackageManager: Installing tool-scons @ ~2.20501.7\nDownloading\nDownloading\nUnpacking\nUnpacking\ntool-scons @ 2.20501.7 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103C8.html\nPLATFORM: ST STM32 > STM32F103C8 (20k RAM. 64k Flash)\nHARDWARE: STM32F103C8T6 72MHz 20KB RAM (64KB Flash)\nDEBUG: CURRENT(blackmagic) EXTERNAL(blackmagic, jlink, stlink)\nIOError: [Errno 2] No such file or directory: '/home/bashman/.platformio/packages/framework-libopencm3/lib/Makefile':\nFile \"/home/bashman/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/main.py\", line 169:\nenv.SConscript(\"$BUILD_SCRIPT\")\nFile \"/home/bashman/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\nreturn _SConscript(self.fs, *files, **subst_kw)\nFile \"/home/bashman/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\nexec _file_ in call_stack[-1].globals\nFile \"/home/bashman/.platformio/platforms/ststm32/builder/main.py\", line 90:\ntarget_elf = env.BuildProgram()\nFile \"/home/bashman/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\nreturn self.method(*nargs, **kwargs)\nFile \"/home/bashman/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/platformio.py\", line 107:\nenv.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\nFile \"/home/bashman/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\nreturn self.method(*nargs, **kwargs)\nFile \"/home/bashman/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/platformio.py\", line 319:\nSConscript(env.GetFrameworkScript(f), exports=\"env\")\nFile \"/home/bashman/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 604:\nreturn method(*args, **kw)\nFile \"/home/bashman/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\nreturn _SConscript(self.fs, *files, **subst_kw)\nFile \"/home/bashman/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\nexec _file_ in call_stack[-1].globals\nFile \"/home/bashman/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 181:\nget_source_files(root_dir)\nFile \"/home/bashman/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 100:\nmkdata = parse_makefile_data(join(src_dir, \"Makefile\"))\nFile \"/home/bashman/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 77:\nwith open(makefile) as f:\n================================================== [ERROR] Took 7.89 seconds =================================================="

**Comment by ivankravets** [comment] 2019-05-23 18:28
Duplicate of https://github.com/platformio/platform-ststm32/issues/232

**Closed by ivankravets** 2019-05-23 18:28 UTC
