### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by rodinholland** [platformio/platformio-core#1588] opened 2018-04-23 19:07 UTC
PIO Core Call Error: PlatformManager: Installing linux_arm
linux_arm @ 1.4.6 is already installed
PackageManager: Installing toolchain-gccarmlinuxgnueabi @ ~1.40802.0

Error: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'linux_x86_64'

Not 100% sure this is an error... would appreciate a hint, though!

**Comment by ivankravets** [comment] 2018-04-25 13:38
Duplicate of https://github.com/platformio/platform-linux_arm/issues/2

**Closed by ivankravets** 2018-04-25 13:38 UTC
