### ISSUE TITLE
Debugging  for Arduino UNO / AVR

### ISSUE THREAD

**Issue by Stimmenhotel** [platformio/platformio-core#2896] opened 2019-08-13 09:24 UTC
- [x] **Development Platform or Board**.
- [x] **Feature Request**.
------------------------------------------------------------------
### Configuration
**Operating system**: Windows 10
**PlatformIO Version** (`platformio --version`):  Home - 2.2.0 and Core - 4.0.0

### Description of problem
Trying to run the debugging with a adruino uno board, the CLI tells me to write here and ask for support.

`Error: Currently, PlatformIO does not support debugging for `Arduino Uno`.
Please request support at https://github.com/platformio/platformio-core/issues 
or visit -> https://docs.platformio.org/page/plus/debugging.html`

**The content of `platformio.ini`:**
[env:uno]
platform = atmelavr
board = uno
framework = arduino

**Comment by ivankravets** [comment] 2019-08-17 20:38
Duplicate of https://github.com/platformio/platform-atmelavr/issues/95

**Closed by ivankravets** 2019-08-17 20:38 UTC
