### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by big-data-elg** [platformio/platformio-core#2418] opened 2019-04-25 23:08 UTC
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\ejuneun\\Documents\\PlatformIO\\Projects\\esp32-cam-test\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing esp32cam (platform: espressif32; board: esp32cam; framework: arduino)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'esp32cam'\r\n [ERROR] Took 3.14 seconds"

**Comment by ivankravets** [comment] 2019-05-03 10:47
Duplicate of https://github.com/platformio/platformio-core/issues/2438

**Closed by ivankravets** 2019-05-03 10:47 UTC
