### ISSUE TITLE
platformio for code-server 

### ISSUE THREAD

**Issue by yhur** [platformio/platformio-core#4431] opened 2022-10-03 08:15 UTC
I'm evaluating the code-server as the alternative environment and installed platformio manually with vsix on top of the code-server .

It seems working fine up to the point it pulls the required board support packages (ex, esp8266 arduino), compiles, uploads, and that binary works fine. So I think I can work with this combination.

The problem I would like to get resolved, is I can't access the PIO Home through code-server. 

I dug a little and found the vscode is spawning the pio http server for each connection with the session-id, but it seems the browser is not getting the proper session-id, hence not connecting. So if this gets resolved, I think code-server/pio should work fine.

I may be wrong, but this is what I found out so far. Could the team have a look at this and help?

Regards,
Yoonseok

**Comment by ivankravets** [comment] 2022-10-03 11:05
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/2665

**Closed by ivankravets** 2022-10-03 11:05 UTC
