### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by manzamb** [platformio/platformio-core#1589] opened 2018-04-24 01:05 UTC
PIO Core Call Error: The next files/directories have been created in C:\Users\manza\Documents\PlatformIO\Projects\Raspberry PI
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
PlatformManager: Installing linux_arm
Downloading
Downloading
Unpacking
Unpacking
linux_arm @ 1.4.6 has been successfully installed!
PackageManager: Installing toolchain-gccarmlinuxgnueabi @ ~1.40802.0

Error: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'windows_amd64'

**Comment by ivankravets** [comment] 2018-04-25 13:37
Duplicate of https://github.com/platformio/platform-linux_arm/issues/2

**Closed by ivankravets** 2018-04-25 13:37 UTC
