### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by dr-apple** [platformio/platformio-core#2786] opened 2019-07-13 11:04 UTC
PIO Core Call Error: "Platform /Users/drapple/.platformio/platforms/espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf\n--------\nUpdating espressif8266                   @ 02e2007        [4db7ada]\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment] 2019-07-13 16:20
Duplicate of https://github.com/platformio/platformio-core/issues/2787

**Closed by ivankravets** 2019-07-13 16:20 UTC
