### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by kolergy** [platformio/platformio-core#1920] opened 2018-11-10 21:54 UTC
PIO Core Call Error: Upon execvpe /home/jmi/.platformio/penv/bin/platformio ['/home/jmi/.platformio/penv/bin/platformio', 'lib', 'stats', '--json-output'] in environment id 139948322520432
:Traceback (most recent call last):
  File "/home/jmi/.platformio/packages/contrib-pysite/twisted/internet/process.py", line 445, in _fork
    environment)
  File "/home/jmi/.platformio/packages/contrib-pysite/twisted/internet/process.py", line 523, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 370, in _execvpe
    func(file, *argrest)
OSError: [Errno 2] No such file or directory

**Comment by ivankravets** [comment] 2018-11-19 15:49
Duplicate of https://github.com/platformio/platformio-core/issues/1919

**Closed by ivankravets** 2018-11-19 15:49 UTC
