### ISSUE TITLE
Does Platform IO have plans for multilingual adaptation?

### ISSUE THREAD

**Issue by gxdung** [platformio/platformio-core#4640] opened 2023-05-25 21:27 UTC
Platform IO IDE is not very friendly to non-English speakers. Is there any official plan to adapt to multiple languages? If so, can developers join the program to help with translations?

**Comment by ivankravets** [comment] 2023-05-26 11:36
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/452 

Please vote (👍 ) for this request https://github.com/platformio/platformio-vscode-ide/issues/452

**Closed by ivankravets** 2023-05-26 11:36 UTC
