### ISSUE TITLE
T89C51CC01

### ISSUE THREAD

**Issue by heikohettler** [platformio/platformio-core#1250] opened 2017-12-19 09:15 UTC
Subj

**Comment by heikohettler** [comment] 2017-12-19 09:19
I need this board to start to program

**Comment by ivankravets** [comment] 2017-12-19 10:52
Duplicate of https://github.com/platformio/platformio-core/issues/907

**Closed by ivankravets** 2017-12-19 10:52 UTC

**Comment by chrizbee** [comment] 2022-05-13 12:29
> Duplicate of #907

This is marked as `done` here https://registry.platformio.org/platforms/platformio/intel_mcs51 but I can't seem to find the Atmel T89C51CC01 MCU there...

**Comment by ivankravets** [comment] 2022-05-13 12:35
Please file a feature request at https://github.com/platformio/platform-intel_mcs51/issues
