### ISSUE TITLE
Home: Could not load mDNS services

### ISSUE THREAD

**Issue by denise-amiga** [platformio/platformio-core#1736] opened 2018-07-13 18:43 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 3 column 121 (char 2623 - 2743)

**Comment by ivankravets** [comment] 2018-07-14 18:16
Duplicate of https://github.com/platformio/platformio-core/issues/1311

**Closed by ivankravets** 2018-07-14 18:16 UTC
