### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by Ivanhooo** [platformio/platformio-core#3085] opened 2019-10-06 19:50 UTC
PIO Core Call Error: "Library Storage: C:\\ESPScale-master\\.pio\\libdeps\\esp12e\nUpdating ESP Async WebServer             @ 2f37037        [75acf88]\r\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment] 2019-10-17 18:49
Duplicate of https://github.com/platformio/platformio-core/issues/3033

Did you modify files in `C:\ESPScale-master\.pio\libdeps\esp12e\nUpdating ESP Async WebServer @ 2f37037`?

**Closed by ivankravets** 2019-10-17 18:49 UTC
