### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by aschoelzhorn** [platformio/platformio-core#2035] opened 2019-01-13 09:50 UTC
PIO Core Call Error: "Error: Could not load broken JSON: C:\\Users\\alexa\\.platformio\\platforms\\atmelavr\\boards\\attiny24.json"

**Comment by ivankravets** [comment] 2019-01-15 20:16
Duplicate of https://github.com/platformio/platformio-core/issues/2034

**Closed by ivankravets** 2019-01-15 20:16 UTC
