### ISSUE TITLE
Home: Error occurred while requesting content from http://dl.platformio.org/libraries/examples/0/37/CompButton.ino

### ISSUE THREAD

**Issue by ronyef** [platformio/platformio-core#1448] opened 2018-03-14 01:43 UTC
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at c.crossDomainError (http://127.0.0.1:8010/0fce13c15ea1c9f96851.min.js:17:188970)
    at XMLHttpRequest.t.onreadystatechange (http://127.0.0.1:8010/0fce13c15ea1c9f96851.min.js:17:190177)

**Comment by ivankravets** [comment] 2018-03-14 11:07
Duplicate of https://github.com/platformio/platformio-core/issues/1426

**Closed by ivankravets** 2018-03-14 11:07 UTC
