### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by joscha** [platformio/platformio-core#1072] opened 2017-09-16 05:33 UTC
PIO Core Call Error: got stderr: 'From https://github.com/platformio/platform-atmelsam\n   45bf7ce..06c3d9e  develop    -> origin/develop\n'

**Comment by ivankravets** [comment] 2017-09-16 12:13
Duplicate of https://github.com/platformio/platformio-core/issues/1038

**Closed by ivankravets** 2017-09-16 12:13 UTC
