### ISSUE TITLE
Platformio ignores monitor_speed in platformio.io settings when used from monitor or monitor and upload

### ISSUE THREAD

**Issue by arcticlinux** [platformio/platformio-core#4323] opened 2022-06-14 18:38 UTC
What kind of issue is this?

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

**PlatformIO Version** (`platformio --version`): 6.0.2, 6.0.3a3

### Description of problem
When running `monitor` or `monitor and upload` from a project, the monitor_speed setting in `platformio.ini` is ignored.

In `platformio\device\monitor\command.py` it does not apply the `monitor_speed` setting from `platformio.ini` because `initial_options['baud']` already has a default value of `9600` which is set in `platformio\project\options.py`

It does work if you run it manually from a shell `pio device monitor`.

platformio/device/monitor/command.py
```
def apply_project_monitor_options(initial_options, project_options):
    for k in ("port", "speed", "rts", "dtr"):
        k2 = "monitor_%s" % k
        if k == "speed":
            k = "baud"
        if initial_options[k] is None and k2 in project_options:
            initial_options[k] = project_options[k2]
            if k != "port":
                initial_options[k] = int(initial_options[k])
    return initial_options
```

platformio/project/options.py
```
            ConfigEnvOption(
                group="monitor",
                name="monitor_speed",
                description="A monitor speed (baud rate)",
                type=click.INT,
                oldnames=["monitor_baud"],
                default=9600,
            ),
```

I added some print statements to show the value of initial_options and project_options when I run the monitor.
```
initial_options  {'port': None, 'baud': 9600, 'parity': 'N', 'rtscts': False, 'xonxoff': False, 'rts': None, 'dtr': None, 'echo': False, 'encoding': 'UTF-8', 'filters': (), 'eol': 'CRLF', 'raw': False, 'exit_char': 3, 'menu_char': 20, 'quiet': False, 'no_reconnect': False, 'project_dir': 'C:\\Users\\Michael\\Documents\\PlatformIO\\Projects\\MyProject', 'environment': None}
```

```
project options: {'board': 'esp32', 'monitor_speed': 115200, 'framework': ['arduino']}
```

platformio.ini
```
[env:esp32]
board = esp32doit-devkit-v1
monitor_speed = 14400
framework = arduino
```

### Actual Results
> Executing task in folder MyProject: C:\Users\Michael\.platformio\penv\Scripts\platformio.exe device monitor <

{'port': 'COM3', 'baud': 9600, 'parity': 'N', 'rtscts': False, 'xonxoff': False, 'rts': 0, 'dtr': 0, 'echo': False, 'encoding': 'UTF-8', 'filters': (), 'eol': 'CRLF', 'raw': False, 'exit_char': 3, 'menu_char': 20, 'quiet': False, 'no_reconnect': False, 'project_dir': 'C:\\Users\\Michael\\Documents\\PlatformIO\\Projects\\MyProject', 'environment': None}
--- forcing DTR inactive
--- forcing RTS inactive
--- Terminal on COM3 | 9600 8-N-1

### Expected Results
> Executing task in folder MyProject: C:\Users\Michael\.platformio\penv\Scripts\platformio.exe device monitor <

{'port': 'COM3', 'baud': 115200, 'parity': 'N', 'rtscts': False, 'xonxoff': False, 'rts': 0, 'dtr': 0, 'echo': False, 'encoding': 'UTF-8', 'filters': (), 'eol': 'CRLF', 'raw': False, 'exit_char': 3, 'menu_char': 20, 'quiet': False, 'no_reconnect': False, 'project_dir': 'C:\\Users\\Michael\\Documents\\PlatformIO\\Projects\\MyProject', 'environment': None}
--- forcing DTR inactive
--- forcing RTS inactive
--- Terminal on COM3 | 115200 8-N-1

It would work as expected if it didn't check for the default value, I'm not sure why it's written that way, I couldn't find other examples in the codebase.
```
diff --git a/platformio/device/monitor/command.py b/platformio/device/monitor/command.py
index ac74b336..461045e1 100644
--- a/platformio/device/monitor/command.py
+++ b/platformio/device/monitor/command.py
@@ -144,7 +144,7 @@ def apply_project_monitor_options(initial_options, project_options):
         k2 = "monitor_%s" % k
         if k == "speed":
             k = "baud"
-        if initial_options[k] is None and k2 in project_options:
+        if k2 in project_options:
             initial_options[k] = project_options[k2]
             if k != "port":
                 initial_options[k] = int(initial_options[k])
```

**Comment by arcticlinux** [comment] 2022-06-14 18:54
This is the same issue mentioned in #4319

**Comment by ivankravets** [comment] 2022-06-14 18:54
Duplicate of https://github.com/platformio/platformio-core/issues/4319

Please re-test with `pio upgrade --dev`.

**Closed by ivankravets** 2022-06-14 18:54 UTC

**Comment by arcticlinux** [comment] 2022-06-14 19:01
Not sure why this was closed, I looked at the code from the develop branch directly to confirm the problem still exists.  It *cannot* function as written.

**Comment by ivankravets** [comment] 2022-06-14 19:02
I don't see the problem in the code. Could you re-test with `pio upgrade --dev`?

**Comment by arcticlinux** [comment] 2022-06-14 19:05
I tried it in both 6.0.2 and 6.0.3a as I indicated in the description.

**Comment by ivankravets** [comment] 2022-06-14 19:16
There is no bug in 6.0.2. I can't reproduce it. How to reproduce it? Could you reproduce it with 6.0.2?

Please note that 6.0.3a have had this bug and we fixed it a few hours ago. The version has not been changed, still 6.0.3a. However, if you re-run `pio upgrade --dev`, it will pull the latest changes from the repository.

**Comment by arcticlinux** [comment] 2022-06-14 20:20
Thanks for your work!

I couldn't seem to get it to upgrade using --dev, so I reinstalled from scratch and things are working in 6.0.2 and in 6.0.3 afterwards I reinstalled.

**Comment by chesteryu** [comment] 2022-06-15 03:49
@ivankravets 
Not sure if it is appropriate to report this in this thread, related but not exactly the same.
After running `pio upgrade --dev` right now, monitor_speed option is working but monitor_filters is still ignored.

**Comment by ivankravets** [comment] 2022-06-15 12:39
@chesteryu, thanks for the report. That was a bug. Could you re-test the latest development branch? 

```
pio upgrade --dev
```

Does it work now?

**Comment by chesteryu** [comment] 2022-06-16 02:35
@ivankravets 
After upgrading I got this error whenever trying to use serial monitor.


```
Error: Traceback (most recent call last):
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/platformio/__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/platformio/cli.py", line 71, in invoke
    return super().invoke(ctx)
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/platformio/device/monitor/command.py", line 125, in device_monitor_cmd
    options["port"] = find_serial_port(
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/platformio/device/finder.py", line 57, in find_serial_port
    if board_config and board_config.get("build.hwids"):
  File "/Users/username/.platformio/penv/lib/python3.9/site-packages/platformio/platform/board.py", line 47, in get
    raise KeyError("Invalid board option '%s'" % path)
KeyError: "Invalid board option 'build.hwids'"
```

**Comment by ivankravets** [comment] 2022-06-16 06:46
@chesteryu, sorry, it was a typo. Please re-run `pio upgrade --dev`. Should work now.

P.S: What is your board that does not have declared HWIDs?

**Comment by chesteryu** [comment] 2022-06-16 07:05
@ivankravets Thanks, everything is working now.
I am using ESP32-DevKitC.

**Comment by ivankravets** [comment] 2022-06-16 07:07
Could you provide an output from `pio device list`?

**Comment by chesteryu** [comment] 2022-06-16 07:12
This is the output I got
```
/dev/cu.usbserial-14420
-----------------------
Hardware ID: USB VID:PID=10C4:EA60 SER=34f8380da31aec11b433aaab5139011f LOCATION=20-4.2
Description: CP2102N USB to UART Bridge Controller
```

**Comment by ivankravets** [comment] 2022-06-16 08:40
Is this an official board or a Chinese clone? I don't see this HWID in https://github.com/espressif/arduino-esp32/blob/master/boards.txt

**Comment by chesteryu** [comment] 2022-06-16 11:10
I think it's an official one but I have no proof as I am not the person making purchase.
In boards.txt, the official ESP32 dev module doesn't have a tid/pid value, unlike ESP32S2/ESP32S3/ESP32C3 dev module.
Is that the cause?

**Comment by ivankravets** [comment] 2022-06-16 13:26
What is your “board” ID in the configuration file?

**Comment by chesteryu** [comment] 2022-06-17 02:28
It's `esp32dev`.
