### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by demsergey** [platformio/platformio-core#2333] opened 2019-04-17 15:40 UTC
PIO Core Call Error: "The next files/directories have been created in /home/usr/Documents/PlatformIO/Projects/testble\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Processing nrf52_dk (platform: nordicnrf52; board: nrf52_dk; framework: mbed)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/nordicnrf52/nrf52_dk.html\nPLATFORM: Nordic nRF52 > Nordic nRF52-DK\nHARDWARE: NRF52832 64MHz 64KB RAM (512KB Flash)\nDEBUG: CURRENT(cmsis-dap) ON-BOARD(cmsis-dap, jlink) EXTERNAL(blackmagic, stlink)\nImportError: No module named lib2to3.pgen2.parse:\nFile \"/home/usr/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py\", line 169:\nenv.SConscript(\"$BUILD_SCRIPT\")\nFile \"/home/usr/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\nreturn _SConscript(self.fs, *files, **subst_kw)\nFile \"/home/usr/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\nexec _file_ in call_stack[-1].globals\nFile \"/home/usr/.platformio/platforms/nordicnrf52/builder/main.py\", line 154:\ntarget_elf = env.BuildProgram()\nFile \"/home/usr/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\nreturn self.method(*nargs, **kwargs)\nFile \"/home/usr/.platformio/penv/lib/python2.7/site-packages/platformio/builder/tools/platformio.py\", line 107:\nenv.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\nFile \"/home/usr/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\nreturn self.method(*nargs, **kwargs)\nFile \"/home/usr/.platformio/penv/lib/python2.7/site-packages/platformio/builder/tools/platformio.py\", line 319:\nSConscript(env.GetFrameworkScript(f), exports=\"env\")\nFile \"/home/usr/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 604:\nreturn method(*args, **kw)\nFile \"/home/usr/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\nreturn _SConscript(self.fs, *files, **subst_kw)\nFile \"/home/usr/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\nexec _file_ in call_stack[-1].globals\nFile \"/home/usr/.platformio/platforms/nordicnrf52/builder/frameworks/mbed.py\", line 37:\n\"platformio-build.py\"))\nFile \"/home/usr/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 604:\nreturn method(*args, **kw)\nFile \"/home/usr/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\nreturn _SConscript(self.fs, *files, **subst_kw)\nFile \"/home/usr/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\nexec _file_ in call_stack[-1].globals\nFile \"/home/usr/.platformio/packages/framework-mbed/platformio/platformio-build.py\", line 40:\nfrom pio_mbed_adapter import PlatformioMbedAdapter\nFile \"/home/usr/.platformio/packages/framework-mbed/platformio/pio_mbed_adapter.py\", line 23:\nfrom tools.build_api import (prepare_toolchain, merge_region_list,\nFile \"/home/usr/.platformio/packages/framework-mbed/tools/build_api.py\", line 48:\nfrom .toolchains import TOOLCHAIN_CLASSES\nFile \"/home/usr/.platformio/packages/framework-mbed/tools/toolchains/__init__.py\", line 40:\nfrom ..notifier.term import TerminalNotifier\nFile \"/home/usr/.platformio/packages/framework-mbed/tools/notifier/term.py\", line 17:\nfrom past.builtins import basestring\nFile \"/home/usr/.platformio/packages/framework-mbed/platformio/package_deps/py2/past/__init__.py\", line 88:\nfrom past.translation import install_hooks as autotranslate\nFile \"/home/usr/.platformio/packages/framework-mbed/platformio/package_deps/py2/past/translation/__init__.py\", line 41:\nfrom lib2to3.pgen2.parse import ParseError\n========================== [ERROR] Took 0.65 seconds =========================="

**Comment by ivankravets** [comment] 2019-04-17 17:17
Duplicate of https://github.com/platformio/platformio-core/issues/2332

**Closed by ivankravets** 2019-04-17 17:17 UTC
