### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by fokin91** [platformio/platformio-core#2086] opened 2019-01-30 17:38 UTC
проблема при создании проекта

PIO Core Call Error: "<Exception instance at 0x4d90300 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 57-63: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-01-30 22:47
What is your Windows version and locale? What is your user name?

**Comment by ivankravets** [comment] 2019-02-23 15:00
Duplicate of https://github.com/platformio/platformio-core/issues/2078

**Closed by ivankravets** 2019-02-23 15:00 UTC
Labels: help wanted
