### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by flyucc** [platformio/platformio-core#3043] opened 2019-09-22 07:42 UTC
PIO Core Call Error: "The current working directory /Users/flyu/Documents/PlatformIO/Projects/190922-154051-eval-blink will be used for the project.\n\nThe next files/directories have been created in /Users/flyu/Documents/PlatformIO/Projects/190922-154051-eval-blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

**Comment by ivankravets** [comment] 2019-09-23 14:16
Duplicate of https://github.com/sipeed/platform-gd32v/issues/6

**Closed by ivankravets** 2019-09-23 14:16 UTC
