### ISSUE TITLE
Dependency searching in the "lib" folder no longer works.

### ISSUE THREAD

**Issue by fenixphp** [platformio/platformio-core#2812] opened 2019-07-20 13:10 UTC
### Configuration

**Operating system**: Windows 10
**PlatformIO Version**: 4.0.1b3

#### Steps to Reproduce

```
│   platformio.ini
├───lib
│   └───FairyESP
│       │   library.json
│       │   library.properties
│       └───src
│           │   FairyESP.cpp
│           │   FairyESP.h
├───src
│       main.cpp
```

**The content of `library.json`:**
```json
{
  "name": "FairyESP",
  "version": "1.0.0",
  "frameworks": "arduino",
  "platforms": "espressif8266",
  "dependencies": {
    "ArduinoJson": "5.13.4",
    "AsyncMqttClient": "0.8.2",
    "ESP Async WebServer": "1.2.0",
    "TaskScheduler": "3.0.2"
  },
  "license": "MIT"
}
```

**The content of `platformio.ini`:**
```ini
[env:4m3m]
framework = arduino
platform = espressif8266
board = d1_mini
build_flags = -Wl,-Teagle.flash.4m3m.ld
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200
lib_deps=
    FairyESP@1.0.0
```

### Actual Results
After one of the latest updates, dependency search has stopped working.

### Expected Results
Earlier (20 days ago) everything worked. All libraries from "library.json" were loaded automatically.

**Comment by ivankravets** [comment] 2019-07-23 16:18
Duplicate of https://github.com/platformio/platformio-core/issues/2573

**Closed by ivankravets** 2019-07-23 16:18 UTC
