### ISSUE TITLE
Home: Platforms: Frameworks

### ISSUE THREAD

**Issue by aschoelzhorn** [platformio/platformio-core#1435] opened 2018-03-11 09:53 UTC
PIO Core Call Error: Extra data: line 3 column 1 - line 3 column 67 (char 6834 - 6900)

**Comment by ivankravets** [comment] 2018-03-12 17:03
Duplicate of https://github.com/platformio/platformio-core/issues/1311

**Closed by ivankravets** 2018-03-12 17:03 UTC
