### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by ihavenonick** [platformio/platformio-core#2106] opened 2019-02-07 18:59 UTC
PIO Core Call Error: "Platform C:\\Users\\Jan\\.platformio\\platforms\\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf\r\n--------\r\nUpdating espressif8266                   @ 8680436        [Up-to-date]\r\nUpdating tool-mkspiffs                   @ 1.200.0        [Up-to-date]\r\nUpdating tool-esptool                    @ 1.413.0        [Up-to-date]\r\nUpdating tool-espotapy                   @ 1.1.3          [Up-to-date]\r\nUpdating framework-arduinoespressif8266  @ 414fb07        [11c7981]\r\ngit version 2.20.1.windows.1\n\nFetching submodule libraries/SoftwareSerial\nFetching submodule tools/sdk/lwip2/builder\nFetching submodule tools/sdk/lwip2/builder/lwip2-src\nFetching submodule tools/sdk/ssl/bearssl\nfatal: refusing to merge unrelated histories\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment] 2019-02-23 16:30
Duplicate of https://github.com/platformio/platformio-core/issues/2138

**Closed by ivankravets** 2019-02-23 16:30 UTC
