### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by gagame** [platformio/platformio-core#2028] opened 2019-01-11 14:59 UTC
Server error: {"message":"No module named _dumbwin32proc","args":["No module named _dumbwin32proc"],"type":"ImportError"}

**Comment by ivankravets** [comment] 2019-01-23 16:54
Duplicate of https://github.com/platformio/platformio-core/issues/1993

**Closed by ivankravets** 2019-01-23 16:54 UTC
