### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by tweakoz** [platformio/platformio-core#2651] opened 2019-06-08 22:05 UTC
OS:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

Atom:
1.37.0 x64

Error:
PIO Core Call Error: "The next files/directories have been created in <redacted>/PlatformIO/Projects/stm32iotest2\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Processing genericSTM32F103ZE (platform: ststm32; board: genericSTM32F103ZE; framework: libopencm3)\n--------------------------------------------------------------------------------\nPackageManager: Installing framework-libopencm3 @ ~1.1.0\nDownloading...\nUnpacking...\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103ZE.html\nPLATFORM: ST STM32 > STM32F103ZE (64k RAM. 512k Flash)\nHARDWARE: STM32F103ZET6 72MHz 64KB RAM (512KB Flash)\nDEBUG: CURRENT(blackmagic) EXTERNAL(blackmagic, jlink, stlink)\nIOError: [Errno 2] No such file or directory: '<redacted>/.platformio/packages/framework-libopencm3/lib/Makefile':\nFile \"<redacted>/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/main.py\", line 169:\nenv.SConscript(\"$BUILD_SCRIPT\")\nFile \"<redacted>/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\nreturn _SConscript(self.fs, *files, **subst_kw)\nFile \"<redacted>/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\nexec _file_ in call_stack[-1].globals\nFile \"<redacted>/.platformio/platforms/ststm32/builder/main.py\", line 90:\ntarget_elf = env.BuildProgram()\nFile \"<redacted>/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\nreturn self.method(*nargs, **kwargs)\nFile \"<redacted>/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/platformio.py\", line 107:\nenv.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\nFile \"<redacted>/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\nreturn self.method(*nargs, **kwargs)\nFile \"<redacted>/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/platformio.py\", line 319:\nSConscript(env.GetFrameworkScript(f), exports=\"env\")\nFile \"<redacted>/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 604:\nreturn method(*args, **kw)\nFile \"<redacted>/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\nreturn _SConscript(self.fs, *files, **subst_kw)\nFile \"<redacted>/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\nexec _file_ in call_stack[-1].globals\nFile \"<redacted>/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 181:\nget_source_files(root_dir)\nFile \"<redacted>/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 100:\nmkdata = parse_makefile_data(join(src_dir, \"Makefile\"))\nFile \"<redacted>/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 77:\nwith open(makefile) as f:\n========================== [ERROR] Took 1.42 seconds =========================="

**Comment by ivankravets** [comment] 2019-06-10 12:01
Duplicate of https://github.com/platformio/platform-ststm32/issues/232

**Closed by ivankravets** 2019-06-10 12:01 UTC
