### ISSUE TITLE
TI MSPM0L1306

### ISSUE THREAD

**Issue by Srdpersonal** [platformio/platformio-core#4691] opened 2023-07-16 09:36 UTC
We wanna use Arduino to control this cortexM0 Devices, the old Msp432p401r is good to use at here, I believe you guys can make this in a very amazing way!

**Comment by ivankravets** [comment] 2024-03-11 10:45
duplicate of https://github.com/platformio/platformio-core/issues/3732

**Closed by ivankravets** 2024-03-11 10:45 UTC
Labels: board, platform, feature
