### ISSUE TITLE
Request for adding new Board "TI LAUNCHXL-F28379D"

### ISSUE THREAD

**Issue by LTech77** [platformio/platformio-core#4928] opened 2024-06-05 17:01 UTC
What kind of issue is this?

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`): 3.3.3 VSCode extension.

### Feature Request

Adding the TI Launchpads Boards / Chips .
To be more specific, it would be nice if Support for the "LAUNCHXL-F28379D" would be implemented.
 I personally hate working with Code Composer Studio.

**Comment by ivankravets** [comment] 2024-07-06 17:28
Duplicate of https://github.com/platformio/platformio-core/issues/3732

**Closed by ivankravets** 2024-07-06 17:28 UTC
