### ISSUE TITLE
Home: Could not load installed platforms

### ISSUE THREAD

**Issue by sergeant82d** [platformio/platformio-core#1518] opened 2018-03-24 01:07 UTC
Server error - cannot load any plugins. I mainly do embedded/IOT programming; ARM32, Arduino, ESP32/8266, etc.

lubuntu 17.10.1, old acer pc, AMD 6400 dual core, 4 GB RAM, 2 TB HDD
Fresh linux and VS Code and Platformio installs, as I initially screwed up and downloaded and tried to install the 64-bit version. I have been locking up with graphic conflicts/screen turns to a diagonal hash that appears to be continually repeating an error phrase (or something).

**Comment by ivankravets** [comment] 2018-03-24 10:48
Duplicate of https://github.com/platformio/platformio-core/issues/1482#issuecomment-375574185

Did it help you?

**Closed by ivankravets** 2018-03-24 10:48 UTC
