### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by czecht** [platformio/platformio-core#2324] opened 2019-04-16 01:49 UTC
Server error: {"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\ARDUINO\\\\Documents\\\\PlatformIO'","args":[2,"The system cannot find the file specified"],"type":"WindowsError"}

This is frustrating!
I made its own directory and named the new project and I'm getting this error. I have no clue why!
Sorry for my frustration, but this should not keep bombing every time I try to make a new project.

**Comment by ivankravets** [comment] 2019-04-17 17:17
Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Closed by ivankravets** 2019-04-17 17:17 UTC
