### ISSUE TITLE
Allow GDB for native environment tests

### ISSUE THREAD

**Issue by twhiston** [platformio/platformio-core#1262] opened 2017-12-28 21:51 UTC
It would be extremely useful if gdb could be run on native TEST targets so we could more effectively debug during the testing cycle, it seems like most generic code would benefit from this as it would allow you to do a lot of work before even getting near a microprocessor.

**Comment by ivankravets** [comment] 2017-12-28 21:58
Do you mean this https://github.com/platformio/platformio-core/issues/980 ?

**Comment by twhiston** [comment] 2017-12-28 22:24
yeah that is part of it, but i would like to specifically target the unit tests, and not the main(or setup/loop).

**Comment by ivankravets** [comment] 2017-12-29 00:31
You can do that with `native` dev/platform. See example https://github.com/platformio/platformio-examples/tree/develop/unit-testing/calculator

**Comment by twhiston** [comment] 2017-12-29 01:04
I had actually seen that example and tried something similar but could not get any breakpoints to halt execution.

**Comment by ivankravets** [comment] 2017-12-29 12:12
This feature request consists of

* https://github.com/platformio/platformio-core/issues/948
* https://github.com/platformio/platformio-core/issues/980

Am I right? If yes, please close it and subscribe to issues mentioned above.

**Comment by ivankravets** [comment] 2018-02-08 13:53
Duplicate of https://github.com/platformio/platformio-core/issues/948
Duplicate of https://github.com/platformio/platformio-core/issues/980

**Closed by ivankravets** 2018-02-08 13:53 UTC
Labels: core+, help wanted
