### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by cubieb** [platformio/platformio-core#3242] opened 2019-11-04 11:01 UTC
PIO Core Call Error: "The current working directory D:\\doc\\PlatformIO\\Projects\\cdt8266_adc_pwm_wifista will be used for the project.\r\n\r\nThe next files/directories have been created in D:\\doc\\PlatformIO\\Projects\\cdt8266_adc_pwm_wifista\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing espressif8266\r\nespressif8266 @ 2.2.3 has been successfully installed!\r\nPackageManager: Installing toolchain-xtensa @ <3\r\ntoolchain-xtensa @ 2.40802.190218 has been successfully installed!\r\nPackageManager: Installing tool-esptool @ <2\r\ntool-esptool @ 1.413.0 has been successfully installed!\r\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\r\ntool-esptoolpy @ 1.20600.0 has been successfully installed!\r\nThe platform 'espressif8266' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment.\r\n\n\nError: Detected unknown package 'framework-esp8266-rtos-sdk'"

**Comment by ivankravets** [comment] 2019-11-05 15:20
Duplicate of https://github.com/platformio/platformio-core/issues/3116

**Closed by ivankravets** 2019-11-05 15:20 UTC
