### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by orcim** [platformio/platformio-core#2285] opened 2019-04-04 08:16 UTC
PIO Core Call Error: "Platform /home/orcim/.platformio/platforms/ststm32\n--------\nUpdating ststm32                         @ e765934        [8e5232d]\ngit version 2.7.4\n\nfatal: Not a git repository: /home/orcim/.platformio/platforms/_tmp_installing-md1Duk-package/.git/modules/builder/frameworks/libopencm3\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment] 2019-04-04 09:59
Duplicate of https://github.com/platformio/platformio-core/issues/2284

**Closed by ivankravets** 2019-04-04 09:59 UTC
