### ISSUE TITLE
On multi environment project all libraries are included/Compiled

### ISSUE THREAD

**Issue by Pedroalbuquerque** [platformio/platformio-core#1158] opened 2017-11-01 22:23 UTC
What kind of issue is this?

- [ ] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: MACOS 10.12.6

**PlatformIO Version** (`platformio --version`):PlatformIO, version 3.5.0a17

### Description of problem

When defining multiple environments on a project as [env:nodemcuv2] and [env:esp32]

I need to include different libraries for each of the environment, so I use lib_deps var to define for each environment the needed libraries.

The problem I face is that if I compile a single environment using default_env var, there is not problem, the includes work fine for each one of the environment,

If I do not specify de env to use, both are built and I need to explicitly exclude some library on ESP8266 env that are included in esp32.

What I believe is happening is that the library dependency folder is common for both environements so ALL included libraries for both environment are copied to that .piolibdeps folder so I need in each environment exclude the libs included in the other environment that do not apply.

Some libraries are not compatible with both environments raising error during compilation, even if they are no #include in the code.

Hope I could be clear on what I am reporting,

#### Steps to Reproduce

1. define several environment that include different libraries. at least one of the libraries used in one environment is not compatible with the other environment.
2. compile each of the environment one at a time using var default_env, making sure each environment compiles without error
3. remove the var default_env, and compile again
4. only solution I could find is to exclude the library from the other environment

### Actual Results
error show due to incompatible library being included in wrong environment. 

### Expected Results
each environment should include its own libraries (defined with lib_deps var)

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[platformio]
env_default=nodemcuv2
src_dir=./

[common]
build_flags = -g -DDEBUG_PORT=Serial
lib_deps = ../../libraries/ESPBASE


[env:nodemcuv2]
platform=espressif8266
board=nodemcuv2
framework=arduino
;lib_ignore = ESP32WebServer
lib_deps = ${common.lib_deps}

[env:esp32]
platform=espressif32
board=esp32dev
framework=arduino
lib_deps = ${common.lib_deps}
  Preferences
  FS
  https://github.com/Pedroalbuquerque/ESP32PWM
  https://github.com/Pedroalbuquerque/ESP32WebServer
  https://github.com/Pedroalbuquerque/Ticker-ESP32
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>

#include <ESPBASE.h>


WiFiServer TelnetServer(23);  // Optional in case you want to use telnet as Monitor
WiFiClient Telnet;            // Optional in case you want to use telnet as Monitor


ESPBASE Esp;


void setup() {
  Serial.begin(115200);
   Esp.initialize();

   // put your setup code here, to run once:


   TelnetServer.begin();            // Optional in case you want to use telnet as Monitor
   TelnetServer.setNoDelay(true);   // Optional in case you want to use telnet as Monitor

}

void loop() {
  // put your main code here, to run repeatedly:

  //Serial.println(millis());
  // OTA request handling
  ArduinoOTA.handle();

  //  WebServer requests handling
  server.handleClient();

   //  feed de DOG :)
  customWatchdog = millis();

 // activate telnet service to act as output console

  if (TelnetServer.hasClient()){            // Optional in case you want to use telnet as Monitor
    if (!Telnet || !Telnet.connected()){
      if(Telnet) Telnet.stop();
      Telnet = TelnetServer.available();
    } else {
      TelnetServer.available().stop();
    }
  }


    //**** Normal Skecth code here ...


}



```

### Additional info

What I find to be happening is that ALL lib mentioned in lib_deps from both environments are copied to both .pioenvs/<env> folders
library ESP32WebServer should not be included in .pioenvs/nodemcuv2 folder

Even when compiling for env esp32 and than for nodemcuv2 (one at a time) the ESP32WebServer library is still included generating an error. I have to delete "sudo rm -r .piolibdeps" the folder to compile without error the nodemcuv2 environment.
But this is a second problem - not "cleaning" the .pioxxx folders

```
Compiling .pioenvs/nodemcuv2/lib/Ticker/Ticker.o
Archiving .pioenvs/nodemcuv2/lib/libTicker.a
Indexing .pioenvs/nodemcuv2/lib/libTicker.a
Compiling .pioenvs/nodemcuv2/lib/ESP8266WebServer/ESP8266WebServer.o
Compiling .pioenvs/nodemcuv2/lib/ESP8266WebServer/Parsing.o
Compiling .pioenvs/nodemcuv2/lib/ESP32WebServer/ESP32WebServer.o
In file included from .piolibdeps/ESP32WebServer/src/ESP32WebServer.cpp:28:0:
.piolibdeps/ESP32WebServer/src/ESP32WebServer.h:28:18: fatal error: WiFi.h: No such file or directory
#include <WiFi.h>
```

**Comment by ivankravets** [comment] 2017-11-02 23:05
Duplicate of https://github.com/platformio/platformio-core/issues/1153

**Closed by ivankravets** 2017-11-02 23:05 UTC
