### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by daz83** [platformio/platformio-core#2928] opened 2019-08-19 15:40 UTC
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 88, in main\n    cli(None, None, None)\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py\", line 30, in cli\n    return _print_boards_json(query, installed)\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py\", line 80, in _print_boards_json\n    for board in _get_boards(installed):\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py\", line 75, in _get_boards\n    return pm.get_installed_boards() if installed else pm.get_all_boards()\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 194, in get_all_boards\n    for board in self.get_registered_boards():\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 188, in get_registered_boards\n    return util.get_api_result(\"/boards\", cache_valid=\"7d\")\n  File \"c:\\users\\darre\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 383, in get_api_result\n    return json.loads(result)\n  File \"C:\\Users\\darre\\.platformio\\python27\\Lib\\json\\__init__.py\", line 339, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Users\\darre\\.platformio\\python27\\Lib\\json\\decoder.py\", line 364, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"C:\\Users\\darre\\.platformio\\python27\\Lib\\json\\decoder.py\", line 382, in raw_decode\n    raise ValueError(\"No JSON object could be decoded\")\nValueError: No JSON object could be decoded\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment] 2019-08-19 20:11
Duplicate of https://github.com/platformio/platformio-core/issues/2823

Please re-test with the development version of PIO Core via `pio upgrade --dev`.

**Closed** 2019-08-19 20:20 UTC
