### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by tchisaka** [platformio/platformio-core#1320] opened 2018-01-28 23:11 UTC
PIO Core Call Error: Library Storage: /Users/takamasa_chisaka/.platformio/lib

Error: Detected unknown package '/Users/takamasa_chisaka/.platformio/lib/ssd1306_ID1904 @ *'

**Comment by ivankravets** [comment] 2018-02-03 22:13
Duplicate of https://github.com/platformio/platformio-core/issues/1289

**Closed by ivankravets** 2018-02-03 22:13 UTC
