### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by pete1956** [platformio/platformio-core#2843] opened 2019-07-27 19:09 UTC
PIO Core Call Error: "a bytes-like object is required, not 'str'"

Error "Could not load PIO Account Information" Plus the Quick Start Project Wizard Will not allow a Project name to be typed in

this happens in both windows 7 and windows 10

**Comment by ivankravets** [comment] 2019-08-17 21:05
Duplicate of https://github.com/platformio/platformio-core/issues/2887

https://github.com/platformio/platformio-vscode-ide/issues/892

**Closed by ivankravets** 2019-08-17 21:05 UTC
