### ISSUE TITLE
add an esprissif board ESP32-S2-DevKitC-1 v1.0

### ISSUE THREAD

**Issue by Hassanphiri** [platformio/platformio-core#4984] opened 2024-09-24 20:47 UTC
I am trying to upload code into the new board I have ESP32-S2-SOLO-2

**Comment by ivankravets** [comment] 2024-09-25 16:19
Duplicate of https://github.com/platformio/platform-espressif32/issues

**Closed by ivankravets** 2024-09-25 16:19 UTC

**Comment by Hassanphiri** [comment] 2024-10-06 12:35
I checked that one out and it turns out that S3 doesnt support S2 . So please can you consider adding this one also, thankyou.
