### ISSUE TITLE
Arduino ESP32 Board Please Add

### ISSUE THREAD

**Issue by eddyhodak** [platformio/platformio-core#4714] opened 2023-08-14 03:54 UTC
What kind of issue is this?

- [X ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

The New Arduino ESP32 Board would be a great addition.

**Comment by maxgerhardt** [comment] 2023-08-14 06:49
What? This was already handled in 

https://github.com/platformio/platform-espressif32/issues/1162

**Comment by ivankravets** [comment] 2023-08-14 08:05
Duplicate of https://github.com/platformio/platform-espressif32/issues/1162

**Closed by ivankravets** 2023-08-14 08:05 UTC

**Comment by eddyhodak** [comment] 2023-08-14 15:52
Cheers, Ivan

eH!
Enjoying This Day






 

    On Monday, August 14, 2023 at 01:05:44 AM PDT, Ivan Kravets ***@***.***> wrote:  
 
 


Closed #4714 as completed.

**Comment by eddyhodak** [comment] 2023-08-14 15:57
Cheers, Maximilian

eH!
Enjoying This Day






 

    On Sunday, August 13, 2023 at 11:49:20 PM PDT, Maximilian Gerhardt ***@***.***> wrote:  
 
 


What? This was already handled in

platformio/platform-espressif32#1162
