### ISSUE TITLE
Home: UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by RWpolyakov** [platformio/platformio-core#2078] opened 2019-01-28 18:05 UTC
On a few PCs with Windows 10 I installed PlatformIO on VSCode and on Atom. When I'm creating a project with selected board STM32F103C8 I get this exception:

PIO Core Call Error: "<Exception instance at 0x55f1b08 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 57-63: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment] 2019-01-29 19:08
Do you see this error on every Windows 10 machine? What is your Windows 10 version? Locale?

**Comment by ivankravets** [comment] 2019-06-05 14:43
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Closed by ivankravets** 2019-06-05 14:43 UTC
Labels: bug, home
