### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Project-leopard** [platformio/platformio-core#2677] opened 2019-06-16 06:51 UTC
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\leopa\\Documents\\PlatformIO\\Projects\\Project_ZET6\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing ststm32\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\nststm32 @ 5.4.3 has been successfully installed!\r\nPackageManager: Installing toolchain-gccarmnoneeabi @ >=1.60301.0,<1.80000.0\r\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\ntoolchain-gccarmnoneeabi @ 1.70201.0 has been successfully installed!\r\nThe platform 'ststm32' has been successfully installed!\r\r\nThe rest of packages will be installed automatically depending on your build environment.\n\nError: Processing genericSTM32F103ZE (platform: ststm32; board: genericSTM32F103ZE; framework: libopencm3)\r\n\r\nPackageManager: Installing framework-libopencm3 @ ~1.1.0\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\nCorePackageManager: Installing tool-scons @ ~2.20501.7\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\ntool-scons @ 2.20501.7 has been successfully installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103ZE.html\r\nPLATFORM: ST STM32 > STM32F103ZE (64k RAM. 512k Flash)\r\nHARDWARE: STM32F103ZET6 72MHz 64KB RAM (512KB Flash)\r\nDEBUG: CURRENT(blackmagic) EXTERNAL(blackmagic, jlink, stlink)\r\nIOError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\leopa\\\\.platformio\\\\packages\\\\framework-libopencm3\\\\lib\\\\Makefile':\r\nFile \"C:\\Users\\leopa\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 169:\r\nenv.SConscript(\"$BUILD_SCRIPT\")\r\nFile \"C:\\Users\\leopa\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\r\nreturn _SConscript(self.fs, *files, **subst_kw)\r\nFile \"C:\\Users\\leopa\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\r\nexec _file_ in call_stack[-1].globals\r\nFile \"C:\\Users\\leopa\\.platformio\\platforms\\ststm32\\builder\\main.py\", line 91:\r\ntarget_elf = env.BuildProgram()\r\nFile \"C:\\Users\\leopa\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\r\nreturn self.method(*nargs, **kwargs)\r\nFile \"C:\\Users\\leopa\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 107:\r\nenv.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\r\nFile \"C:\\Users\\leopa\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\r\nreturn self.method(*nargs, **kwargs)\r\nFile \"C:\\Users\\leopa\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 319:\r\nSConscript(env.GetFrameworkScript(f), exports=\"env\")\r\nFile \"C:\\Users\\leopa\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 604:\r\nreturn method(*args, **kw)\r\nFile \"C:\\Users\\leopa\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\r\nreturn _SConscript(self.fs, *files, **subst_kw)\r\nFile \"C:\\Users\\leopa\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\r\nexec _file_ in call_stack[-1].globals\r\nFile \"C:\\Users\\leopa\\.platformio\\platforms\\ststm32\\builder\\frameworks\\libopencm3\\libopencm3.py\", line 181:\r\nget_source_files(root_dir)\r\nFile \"C:\\Users\\leopa\\.platformio\\platforms\\ststm32\\builder\\frameworks\\libopencm3\\libopencm3.py\", line 100:\r\nmkdata = parse_makefile_data(join(src_dir, \"Makefile\"))\r\nFile \"C:\\Users\\leopa\\.platformio\\platforms\\ststm32\\builder\\frameworks\\libopencm3\\libopencm3.py\", line 77:\r\nwith open(makefile) as f:\r\n [ERROR] Took 19.27 seconds"

**Comment by ivankravets** [comment] 2019-06-21 09:44
Duplicate of platformio/platform-ststm32#232

**Closed by ivankravets** 2019-06-21 09:44 UTC
