### ISSUE TITLE
Home: OS_COPY_FILE

### ISSUE THREAD

**Issue by deninzane** [platformio/platformio-core#2084] opened 2019-01-30 17:07 UTC
Server error: {"message":"[Errno 34] Result too large: '/private/var/folders/zl/lxyty1ms0m9d1y7ygv96m1wm0000gn/T/AppTranslocation/9AD5F3FE-A9B1-4AE0-A04C-F0656BFC8770'","args":[34,"Result too large"],"type":"OSError"}

**Comment by ivankravets** [comment] 2019-01-30 22:46
Duplicate of https://github.com/platformio/platformio-core/issues/2083

**Closed by ivankravets** 2019-01-30 22:46 UTC
