### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by scoace** [platformio/platformio-core#1563] opened 2018-04-14 06:18 UTC
PIO Core Call Error: Platform /home/andy/.platformio/platforms/ststm32
--------
Updating ststm32                         @ 3.8.0          [4.1.0]
Uninstalling ststm32 @ 3.8.0: 	[OK]
PlatformManager: Installing ststm32 @ 4.1.0
Downloading...
Unpacking...
ststm32 @ 4.1.0 has been successfully installed!
Updating tool-stm32duino                 @ 1.0.0          [Up-to-date]
Uninstalling framework-mbed @ 4.50703.1: 	[OK]

Error: Detected unknown package '/home/andy/.platformio/packages/framework-mbed@4.50701.0 @ 4.50701.0'

**Comment by ivankravets** [comment] 2018-04-15 02:47
Duplicate of https://github.com/platformio/platformio-core/issues/1282

**Closed by ivankravets** 2018-04-15 02:47 UTC
